### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by ipungcaem** [DeFiCh/dfips#10]
RFC

**Comment by ipungcaem** [comment]
Yes, I agree. Sign: dfip-4 yes
No, I do not agree. Sign: dfip-4 no
Neutral. Sign: dfip-4 neutral.

**Comment by ipungcaem** [comment]
# OWNER_ADDRESS being your masternode's owner address with the collateral
$ defi-cli signmessage OWNER_ADDRESS "dfip-4 yes"

**Comment by ipungcaem** [comment]
$ defi-cli signmessage 8cmz6gLGJD7sTcjhkS6xG3CKkf68zKQHqF "dfip-1 yes"
H7LnPPnRScYON/dbAAQ7qKYJw41D2QocPghFfWfNJAMnTVYL6lPMSPESPpXPTL7Gp4rJJAnKCmfEICIS+

**Comment by uzyn** [comment]
Invalid DeFiChain address.
