### ISSUE TITLE
Announcement: December 2021 special voting round

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#100]
## Key notes
1. This is an out-of-cycle special voting round to arrive at decision on actively discussed DUSD proposal. Only [one proposal](https://github.com/DeFiCh/dfips/issues/99 ) will be voted on. 
2. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal, 50 DFI for Vote of Confidence or 500 DFI for reallocation of block rewards. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
1. Once the fees are paid, update the issue with the txid.
1. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. Voting starts on Friday, 17 December 2021 23:59:59 UTC with masternode snapshot taken on the first block mined after the time.
1. Voting concludes on Monday, 20 December 2021 23:59:59 UTC. Final votes are to be posted on respective GitHub issue before the time.

**Comment by Dcshel** [comment]
Github is so damn confusing to use for me.  Where or how do we see a list of all the DFIB proposals and results on Github?  please help

**Comment by John-Gee** [comment]
> Github is so damn confusing to use for me. Where or how do we see a list of all the DFIB proposals and results on Github? please help

They're all right here, link for closed ones: https://github.com/DeFiCh/dfips/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed

Issues in here are not the best place to ask for such help, better to ask on TG or reddit.

**Comment by Dcshel** [comment]
Thank you!! I wished I could figure out how to navigate GitHub, but I've tried and tried and searching and looking for menu trees just to no avail. Always have to ask someone else. Not sure why GitHub is so dang hard to navigate. Have same issue with other Blockchain sites that use it too. 🤯

⁣David Shelton
"living and giving on the blockchain"

visit my passion  Mercy Ministries-AFM Africa ​
