### ISSUE TITLE
1. If everyone deposits their masternodes as collateral, there will be enormous price pressure on DFIs and DFIs will crash because many no longer need new DFIs and simply take the MNs. This is not good.

### ISSUE THREAD

**Issue by DefichainVoting** [DeFiCh/dfips#124]
1. If everyone deposits their masternodes as collateral, there will be enormous price pressure on DFIs and DFIs will crash because many no longer need new DFIs and simply take the MNs. This is not good.

2. The fellow masternodes at cake cannot participate and change this either. Unfair.

_Originally posted by @5gg2 in https://github.com/DeFiCh/dfips/issues/107#issuecomment-1027937308_

If the loan must be paid back in DFI, it will be a great possibility to burn more DFI in the future. So I don't see a price pressure on DFI.

**Comment by John-Gee** [comment]
I don't think you meant to create your own issue for this, did you?
