### ISSUE TITLE
Announcement: March 2022 voting round

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#135]
## Key notes
1. Please submit your DFIPs and CFPs by the cutoff dates to https://github.com/DeFiCh/dfips/issues. Use the CFP or DFIP template when you create the proposal.
1. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal, 50 DFI for Vote of Confidence or 500 DFI for reallocation of block rewards. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
1. Once the fees are paid, update the issue with the txid.
1. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. All proposals are to be submitted by Monday, 14 March 2022 23:59:59 UTC and have its fee paid by the first block mined after the time.
1. There will be one week of project presentations and Q&A.
1. Voting starts on Monday, 21 March 2022 23:59:59 UTC with masternode snapshot taken on the first block mined after the time.
1. Voting concludes on Monday, 28 March 2022 23:59:59 UTC. Final votes are to be posted on respective GitHub issue before the time.
1. Announcements of results should be in by Wednesday, 30 March 2022.

**Comment by prasannavl** [comment]
### All CFP payments processed. 

---

- https://github.com/DeFiCh/dfips/issues/137
    - dEjRbNANBJYVGu7LwyHGn9RE872PCDvM5k 12500
    - cc0fe6a1d8e709f2fd5e44c8f6937221968aa2d0e997194808b0324f2ea7ef44

- https://github.com/DeFiCh/dfips/issues/136
    - df1q5sa84d4tawwyuu6ek70usz8s5ee6j3al4u2djf 30000
    - 8b5ff0bcb0b8ab249aec164beaeab06df2d7d2e2854c19d1f65081334dc997ba
    - e636a383eeb2175a09c1f893ebc5b869bb842030234eb011e7f35616d6c9dd0b
    - b15622b60f85f33b20bd003aafb1af30da2790f073aa6e292af9ef0b0e8aa572

- https://github.com/DeFiCh/dfips/issues/134
    - df1qddmtaavsz03uked3sdq4uelsckrz0kahxxknqz 2000
    - fe0f07ab88005b6b3d67a412eff4f091bbcb07ad91b7b1cf28742a54c453f721

- https://github.com/DeFiCh/dfips/issues/133
    - df1qdx0mllcvvrdfcrstyvp2pu4szp2pct5njcgwev 1800
    - a12954fd91e7abda35b05f6c6c3b6c95c1a29a2fb6eccdce5158be83ef07ff81

- https://github.com/DeFiCh/dfips/issues/131
    - dWZxt3FGkzwsDyxLUAHAKokQbwTK8p4uSY 4500
    - 967a33ab14c4e984a78378abb7c4eb093580c58da1466fb9cf0288c5af60af74

- https://github.com/DeFiCh/dfips/issues/130
    - df1q2tw2h9huapmxvuxevdxxtk0n47lfhka9sgvaqz 650
    - fa2e40f818e295c3cd635ec94fec37c5b560fd418c008a387e3feb4a44c30d18

- https://github.com/DeFiCh/dfips/issues/126
    - dHcPxEmADCQAwvBMFruf394iSK6Rkhg3Ni 1510
    - b0d5cf0ee0af70227776cacc18b520fce8d72b363692163146c2830777a99d74

- https://github.com/DeFiCh/dfips/issues/125
    - df1q84myxzrrz7rkefre7w6vtj090grph7y999kgv7 2600
    - 05f62146508445b2636ccfae5f8900362ed422f97d0bb33b3ab527c027e24e7b

---

If there's any issues or discrepancies, please feel free to let us know. Thanks and cheers!
