### ISSUE TITLE
DFIP-2206-A: Burning interest rates and liquidation penalty in DUSD

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/dfips#162]
### DFIP Overview
1. Requester(s): ticker council
2. Reddit discussion thread (optional): https://www.reddit.com/r/defiblockchain/comments/vdp0td/solving_the_dusd_peg_result_of_twitter_space/
3. Proposal fee (50 DFI) txid: 5c48caf1a58e027497f360c6e1110139d98b2dae9752163576b50ffac7b381fb

### General information
To provide a longterm solution for a stable DUSD peg, we propose 6 points which are submitted as seperate DFIPs for the community to vote on. For the overall context please refer to the Reddit post and hear the Twitter Space.

### Describe your proposal
This DFIP is about point 1 of the overall proposal:

Increasing the utility of DUSD by converting interest rates for dTokens and liquidation penalties to DUSD before burning them. (right now they are swapped to DFI and then burned)

### How does this DFIP benefit the DeFiChain community?
By increasing the utility of DUSD by using it also as the target for interest- and auctionfee-burns, we add a lot of value to the DUSD itself. This also reduces excess DUSD from the system which will help stabilize the peg.

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by MasternodeOwner** [comment]
defi-cli signmessage 8VqHKJmGVPxDj2gZyD4cMnE5AvjrKPBgT6 "DFIP-2206-A-yes"
IAXaujLWH0hpY5YjitBh5rGrjVaH4BB+7qyNxWtS+86CfuVZwuOnQh5mGCiuHlA0CKGe2tNJFb2h2L2XvuXPPwI=

**Comment by rmcookie** [comment]
$ defi-cli  signmessage 8WhLwsQGJa5umXBipD2hap7pnFAm4aLq3r "dfip-2206-a-yes"
IFeByvn7v3gYA3pOHEBmS31KKSARVlGd2QVOGMko1sujJwpW5PKbXcIksBYbCoySy8GroM5VDXb5rk81zLophAs=
$ defi-cli  signmessage 8d65UV6LRj1wjgtaJhoAhdhaUYq6zrEndu "dfip-2206-a-yes"
IBO06d+5YVRxxHhThAmPfjLCfo47CuWlLcq5wl7Ov78uO3Xdj+IeHlyL7hXXUda2RwlWjOWSLPc3YI5iJFhJKxQ=
$ defi-cli  signmessage 8GX3eS9vbBKzQP6b3pEkzABYou71CUPpbm "dfip-2206-a-yes"
ILWU/WWX18sDskneMN+t5L5yqguH8JLTZhzI3P5pBlE+Y5INlfoG2rp83arO1qaqtduSTlImqAT+KQwLVY66zAE=

**Comment by Niecoo** [comment]
$ defi-cli  signmessage 8TqT5duF7oHniSdSH8Rh6Xz25r4GDLGzRU "dfip-2206-a-yes"
H3tJst4yWJ4/9kvDtHUksEp0NkCwYF4aC9vBQeKZK7Whf1QMYvckooqjsho2ddX49TrL/8N9mN4bQoW3QDhyG5k=

**Comment by Ppavlov0405** [comment]
$ defi-cli  signmessage 8U71AKaWBsR3oxo1EF4ngDxCxsX6qhoTK5 "dfip-2206-a-yes"
IOOXW4JLRzxyFtEk7Ug4eKpTkdL38yZVB9mbsYzxmqmTHQ3GXzXF0f44osDCsj6+LmEiUYHOcOGuebfdS0BCF3o=

**Comment by defichainislove** [comment]
$ defi-cli  signmessage 8QAHBHkLD96Qa846VnLeyXuykN1317fxti "dfip-2206-a-yes"
H7X8PdJtojqNOvGrkTvQmyxzxicUB+FZgGBS0vN+2o2/O7ei3ZIeJ8BJXXxNRp3oUqPHHDc9xfn/NrD1gfAmTwk=

**Comment by stolloli** [comment]
defi-cli signmessage "8UsgQBnNpjvjGoearXfXaVX6MNRxfdLGuK" "dfip-2206-a-yes"
H5rDPtNvYUW1qOtSr2Pj1MFtQTjLYgc+uv9IJK+E21swSr87hknSt2hQrrJ7FLRTxaYLDsgvXwJFOiNVg9UhBmA=
defi-cli signmessage "8LaQQZhfYiLukaZM9qekTB1b7UAR3Bapn2" "dfip-2206-a-yes"
H/KGroLcIBpIXAWE/G/9nXeSM87KfT++/eStmtBN/dPnPLpcwG/xFQ6Hrh8z3NkZ6xcSUaBQOhf/FoYfXnLqFUw=

**Comment by wmbst** [comment]
$ defi-cli  signmessage 8dmUcdG9RcDr5HQ6g5qShq7HzFrCJtAwVU "dfip-2206-a-yes"
IMEg1jNJsUdoeyq2G7cryp9oSlTwGLydHAWX62MkV/ylakuuP3nJrT0eGipZvuzQpVXQgP8ik4b7cFXsMQrwOu4=

**Comment by Reklov1408** [comment]
$ defi-cli  signmessage 8dK9kXfVP5e7CNiY7g6o1z7Vaq4esFPiQi "dfip-2206-a-yes"
Hxah/v7Qz2DiQFRRmL7ntuwaDF8lC58GsfpOhW9OBSkZZS1wMLKjKJaySoCFEiD+FU+PPASfon0/VPCD5JJGcvQ=
$ defi-cli  signmessage 8FaeehdYBWrNscaZdEXmzVu82DNmRp35PT "dfip-2206-a-yes"
IMNoyQYTbV8fmMdyeaGXA34JDwhR1kcxdKAral+NGVb/B835gKJ3W5DJb5yIOKL58liKYXmL7HtNQKnJOjbkvew=
$ defi-cli  signmessage 8UZ6v5oi6sbqGRihnLtZac1FYMWDHLeSBM "dfip-2206-a-yes"
IK1/cWcm/H/7n1S+JRQIIHN3dIWikk+5HBdE+l5W3i4hHWW4r/u1M3AGBuOd95KcwEjr0kGRY+rwfyRmWm0h4tU=
$ defi-cli  signmessage 8MaBGJJHZ21oV1hgzfg7bHee4tqDfqAMbY "dfip-2206-a-yes"
H5O2Y6Umk+/oHZFBog59N8UxkPTmIecuh2lB/zpxhUteK59y54MX+P8XJHTfKXeImXyZKrk+GGNjdZY4R6EOuSk=
$ defi-cli  signmessage 8awN6WdPPovinAoXqKTjXAaBkPJ8H7gPrW "dfip-2206-a-yes"
IJt8v+GbXaW2ulNpgJ5uQn5SPt3nv/0Qa+hk1t91ZtZ2Qa787rDa+bu/YLrVxKxntU+MElzZ9IRj7sI6nHDuTvg=
$ defi-cli  signmessage 8TNXjkrxucbByZL2uqWV7rSWmcuek3Jxeh "dfip-2206-a-yes"
HwmFZfOTX00FZ7+S8LpdKdW07ltXRPac0XCZ5dynPMGNdX4B1Y8kbAnQVWPMVJ5kj4OiLLREjcoX+KsA1pzQ9H0=

**Comment by Don2Camillo** [comment]
signmessage 8RNwLywUm8BHY1RqjdaZ9SaaurTLWFSJbx "cfp-2206-A-yes"
IGFJ6pRaAcbse90lcpooy+dWZempvgdQ5CtzvdrX95bPZqLOZtrHe2w5keOO9hfp8LCuHCbHq7LnBgqqoPbRdOA=

**Comment by Don2Camillo** [comment]
signmessage 8REfG2L75fS3nCBaUwKbEbMAvxVxuxj3Bi "cfp-2206-A-yes"
Hx6JCZoINjcaMycqL/MoInC7Yq83Tjz77QGIHdMKO00LDaxqBtpZYGziHpHZXm57EE/bZWXZTDOvHqMXvqi3ijI=

**Comment by Don2Camillo** [comment]
signmessage 8RNwLywUm8BHY1RqjdaZ9SaaurTLWFSJbx "dfip-2206-A-yes"
IC9sJKEnHXpJyc/K83ZsoTTnvFDKwp03sVrCp3NlAXQ5aY4ESfCxTHvjskGavpBH8Dz7YFpbBxjyzx4H2t1GEu0=

**Comment by MyVotes** [comment]
$ defi-cli  signmessage 8X92s4hh1dPjW7cZDRjZrKoLG8h7VeKNsA "dfip-2206-a-yes"
IPsLzO+Jlq7hhKhauzO5spgQAC07/fxwI1v8AslDrruKA7WULCFWCALn8yi6/uPW5WUTmmC488wkpDSn09UOex8=
signmessage 8WrcPiaoGhQgitWiBG6e3fW7dVTuZMvjot "dfip-2206-A-yes"
IGbNuT5fIYmmKyM4lj4ZKLSIuBHleKLAkQlmuv+oHNT1cm5SDmFSd6TXB5BoIh5uywS7pKOLLW6KtNgrwJLd6O4=

**Comment by oliverbosshard** [comment]
$ defi-cli  signmessage 8TLrwLmPssRzjQnZbQgs6T7h2aTPjPv5sP "dfip-2206-a-yes"
IBE/0eCW9eI8KTL5PXJwTsJu6fOvJPm5SjLqh99xPpYBbHLuggmMrYUiiOSDOfMrKH8sj/H2aMLqUxF5DcjaxUU=
$ defi-cli  signmessage 8TiSqpB1U9kpJjKznga6ShWULqTp3viVEQ "dfip-2206-a-yes"
ILtbwq+630MUUETFOrZ4WKMP7q/qW1NGxXvyhRwYHTkaXVhprgep5vXndAwn7JoUN3E1zTQ8XOWfw0LOCzYX/fU=
$ defi-cli  signmessage 8X3pH7qoauBHFCCVhEcVXAEg3N4dKNQHbM "dfip-2206-a-yes"
H6nb37CP/eUhl/T4v1Irriev6j8yR+XcpeojVGTsDlWzc0EcK0PBRhD/pJLzMQGKHHJtJy3BNBIeRJpS4hPlyBU=
$ defi-cli  signmessage 8cfzcwpwgwtYJAmgpVhRsU8G1YLTdbFCsv "dfip-2206-a-yes"
H7ITlTPb9/MxGjYwnFTgsYDqBNDk78WAHl8v8mCs7G4KEDPuHUFnMxdD3O8mD4kuW3GkfwZM2xygTYDpyJ1dDtE=

**Comment by Mir82** [comment]
$ defi-cli signmessage 8JdbYYdXc4VaTmihQndAbutHURWU1MLDat "dfip-2206a-yes"
H69DbLXkBYNebSO7FIiQMQNUKSiGE8A52Pp/56LYmoDHSEUJGk5YXzKKPy6UMd5BODUkJpvSPJCoDIzP5iHnk/g=

**Comment by MarkusNeusinger** [comment]
$ defi-cli  signmessage 8JNF4s8E6awasceNvFVwfDwkVtMx8CD6yE "dfip-2206-a-yes"
IOD9qrfR0uZ84PTYoC5IYvd2lNO6kbMTiRBG+0V0OePVYtPugCqJJP3EQWhSd2a3Fu++JqItAiADKAmK9iZBkCw=

**Comment by addictedtocookies** [comment]
$ defi-cli signmessage 8KZ41xJbsDJEeumtRYQZWBU7uiz67KRkak "dfip-2206-a-yes"
H7uhQnGhnB8/S6ViPTQQ3v5LzaPEbBgj/AY+tC0idGUiMx79v87GY3ztJhl+zAK03CGcovLwFo8ve2ZDQgT3IoM=
$ defi-cli signmessage 8WFeZ3AfSDymxTxiFYa19Y26HeTcASD6mF "dfip-2206-a-yes"
HzI1vRvsnQ5Pd9sQ4p44QJIc95lQegBNTNhDMl73+HsnELLmwco8lX89Z2nQaQui+ZY6e8LBDw/hS4gPxVABC0I=
$ defi-cli signmessage 8XMhraYjB8714nAzocf3kgzeHgWUMSjbcA "dfip-2206-a-yes"
H6rnX3TQiNe7oh466M1uOpm+3OzEPGdX/qQM6RIlvi47X7awJAMz71cnsU0dXFzePDwys06gSrd6XQFkfZPGi/c=

**Comment by gorg1919** [comment]
$ defi-cli  signmessage 8P22EWKPCn6PWHaJTUMhLnL2xxwRwxoXMS "dfip-2206-a-yes"
Hwgmnt9K+PKUY/i9o/2u1X5XWz1hCqEqcSiwnz4jFwZTCffB/O4mxYOM3jK/nWCUl+mU1fwUxf2oIgqBniayIb0=

**Comment by Sunnyville1234** [comment]
$ defi-cli  signmessage 8FAnZomHrhsfEegfsaZE8mKxFgncZCjvPW "dfip-2206-a-yes"
HyNF/vRN00BDIP8nApn3W4X8G025UoAWULiUuAFawfusVACz3OBMx8b8lrDwY1Q6BgTkF+9fMVA1j6iAz99m61M=
$ defi-cli  signmessage 8Nc3F3DorLEmnVJ6iyRzRPztGjLJ85tHzD "dfip-2206-a-yes"
IAOD2N/rWO1rPluJwxbaSoqHu8fvh4455ZibulIy2jFXA8YnrT/oZS+ovC+2twfaM2k9IuLSqtsUueBhXEXWh9s=

**Comment by SilverSurfer2000** [comment]
defi-cli signmessage 8daGYPTDTzMRtUx61uWRjg7p9GECMjuip8 "dfip-2206-a-yes"
H8SYtx0fiS+1w6wn2ZZk/YEOI9pTS25U3OpvIGKJNpkbBnliPA5EGDTHKB/1ZdLTTkIxmkSzvlzotaCFLc/wy2U=

**Comment by otto1593** [comment]
defi-cli signmessage 8QCBuwyuQFTMPxgZAaK6kQaVnnpye5nc4C "dfip-2206-a-yes"
ID4LgJAr1giU07iCoN4sUNExVhdpsXDvJ7PyDmSR2azAA/r3fZAQApo7c+OSLM7yWh3nqJpnHJCQsIUxcQuGQxo=

defi-cli signmessage 8UToj6ZjpiTL3E5GJQG2c4pWRyp3tTzBxy "dfip-2206-a-yes"
H8rhpqjmWKwsrgZNdgR6U5YrAuprxh5QAxikA9Z9nn+yKmDk/GfS0nkPZlWiWochKgW86O0J4mX+aIWBE6wdRIw=

**Comment by kneides** [comment]
$ defi-cli  signmessage 8bAFs5b14B6A2iddURMUnUyLffeTBNzf3P "dfip-2206-a-yes"
IPMyd5S9VwzhWeCNuyFswT6StNLH4NuT+lMbx4janmbgY9HXOuU+0Z2WDkXaylCnBVBujrSS/xpLgf768lJPNvQ=

**Comment by defiuser2** [comment]
$defi-cli signmessage 8Jyov8rftj4tJZ8Pfb8UWVpGcENvc54Bbv "dfip-2206-a-yes"
INKDsNK/sZ9DMPsk+QzHR5uzLoklmJdLSMpTeWHLc+sHGuEnK9eN6VWAJMjNWyuXEx6mIRy1SAm9WDiZcGsraA8=
$defi-cli signmessage 8NU1UrckihBcfkKzaQ3j1WXqyhphWGPRd4 "dfip-2206-a-yes"
IMtHgAGCCASgH7MuxPIuWeJDfGe/X/Of3veHahzL/ITTZ5THvQiEbrjAyHCDdOJiSlKsUuZ1KL/D27pCajkb+2w=
$defi-cli signmessage 8Fk9Tppih3a6UJE2xSJnuYPu7Bswxv4ELa "dfip-2206-a-yes"
IM9qa8BuPY6C2OU+BDKhyyHMsEU3vOGhrHIw7lSzGA4yTIi8mizLlFCGJFGUeog6P6sh0PIAIUGgEyaLyAIOx+U=

**Comment by yacrazyone** [comment]
$ defi-cli  signmessage 8N9itGuACQCojgt3mCPtLqGpsrtgXpn4Yz "dfip-2206-a-yes"
HzGRaGrkbmLoyAyY+RDzdbgL9TVC+V3aK4TTgglCaPGdQoJakZdDHk1y60lhE9okujZCPrlSCPTCltM2PhudYI0=

**Comment by angelocastiglione** [comment]
defi-cli signmessage 8dJLcKddBnwXzzXBLeZLYqzHehfeB8UWa2 "DFIP-2206-A-yes"
IPS5b9Crk+y0QtTNp9HmEeBpY9gN4NluNv8iEpP6DucTfQQU1rSfaX2Z6GIB+e2jROcTLv4qO4IMeeGpLuJ4dRQ=

defi-cli signmessage 8JgPSdyFpLTG1wAnxFHpuHjEoSmPBhHccg "DFIP-2206-A-yes"
H9FB08P9aW5Su4jThIGKf7Q342sGZoE0D2ebJ86FQLh1doyhW7WUxeQNfZWFE9/Ev7j1Z6e4dS+H3REFpvVV/9k=

**Comment by a1yz** [comment]
defi-cli signmessage 8Q16Xbmshorv75119E1criD49eAji7ZzvF "DFIP-2206-A-yes"
IHVgkxBknH/j7tT+nkGwdLFWmMMARWoqyKt/fwRFMMzCf258vfxQIr/pP4h5U6NCUUiSF/2jkARCkUE3+ndqZF8=

**Comment by Fragharvester** [comment]
defi-cli signmessage 8LvY9Py5pp8eqQ6tPaLxwH64osfdNppfXu "dfip-2206-a-yes"
IDAhD6sT7rs6BzS22lXUfhrKM0V3lMdM8XWt1wcEh8KYZAiofcUTz6vwQq+yMf0BwiTAUfjf0L2cA2ACdNtAW9g=

**Comment by mn-1632339193** [comment]
```
$ defi-cli signmessage 8NmuAZiKcGHZ7TKpezCk3QeY4tW158GWkn "dfip-2206-a-yes"
IFIpUPjs0pjGEtjMl/gJPFXFdLSL2lQxy5sYK6bA5uVJbu3LmbvC+Kp9e2oWbVQFFeFaRlXk70ZyYXl7FOdkk08=
$ defi-cli signmessage 8bxanazYLFqXz97MgTgr99cqbxBwTVmxnM "dfip-2206-a-yes"
H2cFgb+NxJbxMiyk3RUsZysRT9YqbYbXQA7iqjYHYALIHL/iaHbEFAnxhFTT7JMXfk77d76OQL1Mkrao+zaRqJo=
$ defi-cli signmessage 8S47AQMrSZeZJDresCHS1r8rL7C3DVimTN "dfip-2206-a-yes"
H/8xSfJYryUzMApia5CLpBaj2QAbPbGQHReC5NcwiKHkKTMIcZClZlle5xL7wX2y0lQHVOw19oHsOaw4l5hnoSo=
$ defi-cli signmessage 8YbFfTfWfqXAU7kYvL2DV3qkwJQTaHBTja "dfip-2206-a-yes"
H8DS7D0Ubt40VDdiVdep4Oem2VcXML+moW6uIt/2GwR2bFecW6+zY36RjiUT0IBt3VnBIvbhv/NuTfXLfYcfC50=
$ defi-cli signmessage 8VSoqn7PMEXsh43nZZLjgb8BsxYHq6XDWX "dfip-2206-a-yes"
IAQXgujfoyibbb0465U7cGbHjDn95lo9K28SbbsQmaq4Vqn8ZaqG7ZUZ9eg8WJNWt0pJlOQfenZK8ySNXtaNbJY=
$ defi-cli signmessage 8JJ6M335M69RYXUYnJAafSxr9SBru4NwM2 "dfip-2206-a-yes"
IGScRDo654P6XfTvASJRJZ3zOzACBGSM0Z2+JAZc6u/afF9zeAxUydLdo5X83un0iS0cP/ifhCZKR0iaR6s1+O4=
$ defi-cli signmessage 8ZdfYTKnpCj6eVejjAzt55y4YrGr2HEQFz "dfip-2206-a-yes"
H2hFel4E7C6tjGtuEXOa/FbTSqbQJ4FoYF7objAjivEtWgvxk2R8S0qt7cCcCUWaStPwOp8ZpncR2CNbPQfvZv8=
$ defi-cli signmessage 8Frg3g5dDFGDFqDTmaZBMAL7hoBwdrQdfF "dfip-2206-a-yes"
ID5n/bS7EjIAZEqhtwhNF+v9BEhK/jNRyiX4c1JDdbNtDC5Way7Fran34SYW5xAgnORNwSWaeXgwaBZ3IU+jBag=
$ defi-cli signmessage 8G5XhVoRvA6gyRYTKXo2cYHuQRKnbcXWGJ "dfip-2206-a-yes"
H8TaF/9KrZrwOSJ7cxiP8vyKnxqBeumwh+9LNsUL3uOQMg/rEbyyfmeXf/atsU+x2djjMH10L7nF38dIwNw4Zzc=
```

**Comment by Buschfunker** [comment]
$ defi-cli  signmessage 8UcLHts8dkbWdZ3FkebVCEQ4D5vTmFPXTj "dfip-2206-a-yes"
INNnqS7zIPsqnV8VICNOizT2B+W6q3yfoLaDmJVJooBLKMJouLN/xxlYQQo0UdUhEBj95ESRPn6hzeQx3HRpQB0=
$ defi-cli  signmessage 8Vu8wvBcsLV68tW7FDci7sJWQVNZhSXHnw "dfip-2206-a-yes"
H4hCH1jEs6rbydP37qgGwWswLAbl0+XnJW09WZbj7pX4KHU0qYf/lxHFAy88JrehHiZEGZD03cvw8Gn5bq8kSjw=
$ defi-cli  signmessage 8SYErnWpBC7vFy6tQUyQ1VHm9tP2fFmk7K "dfip-2206-a-yes"
IFCsf6l6gvFPexVSu/6s/5zm5BB203gxIMaJbi6SCwkQNLMn8j1Bn79sIYmio966rA9UoLoXbnfRbjC3RYAXU5Q=
$ defi-cli  signmessage 8bLibmeH2NpMQGuJbxXPhneU3TM8fcanxa "dfip-2206-a-yes"
H0iCA0EOvTY1TXEeY1kleM6Xhgoe3nceGDT0hLLcMIgzWLUW/XGXjk6bVnwXrnOlttxFszZXa9U4Nb8wrV9xzkE=
$ defi-cli  signmessage 8SKToJvfGAKG5iEiyaLprKikkoikDUZQXk "dfip-2206-a-yes"
H7cWA/REvy8qSAF4ShWqF4VOzZCqkBfyLcqUiqqRSytbWAT4rsxQCbigfOSBLPx8alyziHWi/EjMB0y73JmfGy4=

**Comment by JesusCryptos** [comment]
signmessage 8KQepBiuDrQi3JFqxkz1agdJSpp8PmRv43 "DFIP-2206-A-yes"
H4w9VSat/OlJI7/hCOTu7lBblL+iJV0Biz6wWv/JFMCVTdfEi837s8tapq4o48bSyOrrkM6udgjjD5GDojyR8GU=
signmessage 8QCWcqHEEPg8QkfwLyTAp5AZf6UEtVA8Ht "DFIP-2206-A-yes"
IAvgHjYY1AXWY8KdSKkvIDUOORD3cvJSTcm9/QqEjxT2Q5kAzMTsD11jTm1k2chQyp0dNyE0fkCMxIiTg6RXgpA=

**Comment by maxiimal** [comment]
$ defi-cli  signmessage 8L7grcnPHkS4Yahu5i1gBPGRvFCQFRDc9N "dfip-2206-a-yes"
IJuN/NTWyRBisjUaZ0sCwbmmlfHXGC+M1+MuYAfHchTSZklzpZ/jeaRvKPQ+a8/efduXOl/70jVa7i5J+6UMCDc=

**Comment by Nils-89** [comment]
$ defi-cli  signmessage 8P4CGnPt7r2nkxgY467rASz2f666xPK9ge "dfip-2206-a-yes"
IF8FR5e9Z789Glhj5nbse6a/SnMF4hOt+ECdKaN01vzRQTAbzXTE+HOuCxk0iF6AmAT9Uepzc222xiJ+zzva/GY=
$ defi-cli  signmessage 8RKgsRnAGBcmwouuFdSjMFitDNLH5qegY2 "dfip-2206-a-yes"
IGpvtSIv6KBZQ01Tm3qgy3LuGG40JhfYaK/nEgv2PAh0Z85zyPINC/KkYQMCMuwr0REyOzEGhd9Ra+le/l4tO9k=
$ defi-cli  signmessage 8dXgX2qd82eyF4qRUhanypMTrcvVf86rVN "dfip-2206-a-yes"
H2RwnkLx5Yrc2eNKegvs3NxxZqxx7mQTygmwj265ac7WWVWCKNk06S0w2aA1OVrZ9Onq/AfVQ++nD6ChcYN4NaE=
$ defi-cli  signmessage 8Y8kN74DNNGPZbxDHCCzH5yNW4nM1kJhtd "dfip-2206-a-yes"
IKZaNaAPTgrB7cxb17k51gMUVbbKxzHmQyeqN5FYkhfnSYCLhAkdANzxOQigTVj93IV1n4vao6Ujp4ChlTNz594=
$ defi-cli  signmessage 8aHyACpxxie5jd8dyWBW1kRe3zEj5tfBJi "dfip-2206-a-yes"
IMlopEOOyhtmyNXqfXBxFUbfs9eKa35lCGEe6nY78+BEBL2eoxfjMR7dSDYJIV/b26/QzEGMa7D7oPay3JbufZ4=

**Comment by Nahdonnis** [comment]
defi-cli signmessage 8Wk9Yfeyd7C4Nh6FTs6tmGobhBmPzmhmFM "dfip-2206-a-yes"
IKqoVefjIOo84ez075Lo6gwCWYlRLdqKCrayUl3VL8Pka+XgjhpilmEzfdyRMxXwxK6um7EJR1Vx70IljR5Tg2Y=

**Comment by rox1338** [comment]
$ defi-cli  signmessage 8RcPSc794gtawceiQ8wvZgqSf397D3UoQg "dfip-2206-a-yes"
IFxSocZl1lj17c1mAwLq/G0iSzTKgcAeX6Slk2IJQfb2BCJNxExoV9Whc0y7+xbbPQEE52bZAjSQCyx+0jhxpII=
$ defi-cli  signmessage 8YKmnwAhtMehDkfj9nK5edQ1XwtzMivbsW "dfip-2206-a-yes"
ILOh8JhJeY8xPgqV8yJljIcdFe8OIOKg+LweiDBGyjcjUg1ila1rHAMJeB+nEVRsp2EhNrZvGpDNdCOytRiOtp8=
$ defi-cli  signmessage 8SeCx4BhhQDBmzgKesMd7q6hhhpdLfiiy1 "dfip-2206-a-yes"
IOhZmEt5PmUauXDdl4x/3yEGWw5MEE46uIBjVvlhocPiGzL+JROBmcy2Z0CbRlWUBAB74dkJo1RFKkK6vVrKOMY=
$ defi-cli  signmessage 8RRPpPfu2tUNEVM4KdQsGhu8uA5HJLgPzx "dfip-2206-a-yes"
H3uAgDLyglEdWZCTWL1xsSOedAgkvYAxnLEymRHQfKZgSDCThhDZ4OZ1m3IM8bQiv2QClBMxLdZCK7zAL1bs+EA=
$ defi-cli  signmessage 8V5eMiZu3ddbtDVktEzx2V6TaZbRids7Fb "dfip-2206-a-yes"
IO5bP92X8fO5kFS/LprsyYlCZc2DhEulFAwCyDokm2HiVW34l4dZqhy5HLa1LRRsx9WUMaY92L2TIAAfqDP1Eo8=
$ defi-cli  signmessage 8YPsH6z292nLHMssQMsGzm2QyhGeAYgJsa "dfip-2206-a-yes"
H28eBFLBekJ+DbkUVuD7YEE8RrXhbX4P9uOID2sZMzzFfrTR0nAAsEtrRijp0Qhpg1glkYgXdDLnXPHMogpoS7c=
$ defi-cli  signmessage 8cbdNvsCPzp1rYz3enjrdb7UeTy1A33knz "dfip-2206-a-yes"
HwdrnxCPvT7PnLspu7LfwxuQSXtCtzo/cTT+CZsrlRSrZ+kOAkUEnyTBfI6KJYyF6cD23oFglchs2sXGvZmCP7U=
$ defi-cli  signmessage 8G5f9wYGiTULo9hb1UW1MyrEgbWJWNcTa7 "dfip-2206-a-yes"
HyRpZJqi6ctVw8QJRvDIFKtGFRakodAo6J9i+VAXoXThfYIa4Pit/KhU4Cf+QlLCWIvmu2Di+DSOwtaj7tcq4jk=

**Comment by meta136** [comment]
$ defi-cli  signmessage 8FMproxkvrSheWifx1mpeCNvamLN9dPGeF "dfip-2206-a-yes"
IOiuvZatBzrm53GGsZH8I1TwrXlytg2PFvsNpXJmtJx5e0LskmKUgoWiIcG4/ETbP5XaTnJOpREUrtOT+vPQkcI=

**Comment by ms-01** [comment]
signmessage 8X9mSBVoeFfsk7XyAJmYCGu4SgrQzMj7Ud “dfip-2206-a-yes“
HwjGQe5KQstvG/qI8BPgMC8XoZodiH+CxdS7H22ROCGYSJS5i2uaBJ3EVz9+aTOnv6Xvo3XYh8G3un8tg6TeYkc=

signmessage 8K5EUbUbdpRWH1Tx1tTSpJgXs1x8Bck5vN “dfip-2206-a-yes“
HytZ/Bt0yf0WtMfSvCS8HEkt8ydqhDgnra8HxiENF4XXLVXuYsl97WvKTlVD75jldbNncF0pbl9bevhbTf43jD0=

signmessage 8SQaHvzkrHik3o9vwF1MdKf2LkdgcicNTD “dfip-2206-a-yes“
H2+en2h/GPV6+XtlKqlhBXxfSu3JfLdOu+LtfoEkYI31IqwAC3FARXfp2gcwoMmFFPRlGG6b9JhGxZpJf+G0DWs=

signmessage 8cfqCfRmN697jMavNmgbJH61tRXNhBXCiM “dfip-2206-a-yes“
IFqzyeIdk5oFN5Jg4HhsSk0bO9qpOzu5ba8CiBUm5c7bWXGbkLcyw67OnxuhMN8GAKuXXjuSZVh1eBFqO/tFrag=

signmessage 8c3Rdmz1hCSvvSRittYUYQtQQLurX8dzzQ “dfip-2206-a-yes“
IKpxc8Rzg3ZsIAZ+p4ZOpjn/yHpqpqET6Kv1vYYOTmsfNxL4FwN5ykRXcZdMyayrOTZbFIScsZ96XWW2gM41rMo=

signmessage 8F8fVhgSHs71NUFvEmhVeYatzayo6YQ1Zw “dfip-2206-a-yes“
HzFUDN1tXizCQLcVCQS2WnvrWywNb2UbR1SN1+1adiv4Gjd6UXH6jkXgGIwNncOGR2jbAKeslVl/uxJbSX2xLYQ=

signmessage 8WnUuKZ7U55HNxmnwZMwzJHggRSy1ZKUKs “dfip-2206-a-yes“
IAkocfRLgcdSXOMS9N6x85zZ/XADukaUSM8QQuzjTM5IS1NidaorPtlZlkyGOtcZkyx+UhNVlwxNsLk4fM2Ay7w=

signmessage 8XFTnhwwbyM3MA7jLosmiupJfzKvuC8XM8 “dfip-2206-a-yes“
IF/pExFycjsjN9xjy7sFEQhm65vzwIELtRj7r5jgyeLPdHr5YjDsTfkVn/9brpBdPRzArfuAw7ecFF9oXdwy2Eg=

signmessage 8LiEQLQCLkv2eTcQ5vmMWszMCXEYBk9GK3 “dfip-2206-a-yes“
IJA/jc0UOyxSNG0xTnUE9MQyNasn+7qY3AxEtgNjlQdBYx7pPgIhAErWnEWlFVQ4tQ1jb39opvbeGPiH84OaSVI=

signmessage 8YfZo7Qow2G6aZFWAzEoWAvxufA7AyYb4i “dfip-2206-a-yes“
H19YM5Cdu3+2uKEgMumhl8XLH/ig1rq/+EjpQ8Oo6sbdX3H43xn5t+nwAWZ8IIKOGgU+NeHXfBZd42DWtRWmczo=

**Comment by mintbluegold** [comment]
$ defi-cli  signmessage 8WvZMpGeVoH41fRLh5rrFXFnFqxWs9wb4A "dfip-2206-a-yes"
IJHqPighxiAuGiJFmkDW4GenFdoC9WqKzHUgdcHfi9fsFT3HGIV/3lGJiMRGyTRWljGRX6mBcigrYA4yEVloSwQ=
$ defi-cli  signmessage 8WVqN8QfWsCPUyYqgDAkbSSPad998ZsJ7K "dfip-2206-a-yes"
H76o1FtD8Hiuanc+X2a8hnrtqovgpAXKXpsf1I+K8NN7Fd/tF+cbBQlpv/b3I8g1tnAV0XgysGddodsrRum5RaI=
$ defi-cli  signmessage 8bXUUW3jT3DnG9ZviSpSvxSBKcWpmDFEAH "dfip-2206-a-yes"
IGDEzN8LIZfCRwCbB4ZjfBf6CHxSbHNFt0j8ev7Z5DcSLMcCyZgc/d7MdEyngngcbJDkcc7RR8Q9cqhSrug1HTE=
$ defi-cli  signmessage 8aofKcKDwW3ZAQ9nS1XZmGk7c2j6YM6m3p "dfip-2206-a-yes"
INR6YcDyBtOB/+Lf9nESJj95PKAl6ExqyWBVt2XlqIzIH+8zDrDP8FOgzU7F+3c3h/u+xNI0mn1qf7vvfEttVCo=
$ defi-cli  signmessage 8eETFGSUdWmCYCp8SKCiewBUc27Hi5La2b "dfip-2206-a-yes"
H/dLBHO8hiNicXPCbZqjjCn/PmBuu43LE/VkNayWx421T8VsuXuNtiEEhV6kkysuH6jEaBzjJqOhRPf2q91q2Cc=
$ defi-cli  signmessage 8c2Bknr6QkpJz4uVGVVEirXrmUnVkQ8BnD "dfip-2206-a-yes"
H7+Q7wmnHt6bk9X9CoreBQGsY1eo1/xQJ8oMkMbxZ0LmUErckYriKUo1nE8AI3jmLaaaThIkuq7ULZHUCeCf6DY=
$ defi-cli  signmessage 8RLuJNRzNyyYCVUK4rSKTz4jE5eogJuS9m "dfip-2206-a-yes"
H6BFD/9fRNlNDyjBbAvfgGLfNV9LTyk32gisRKx4GNOvVxoDl3Xkw2F0nPwYmqfpJiyvML8odO4PtearwjWTvo4=

**Comment by surangap** [comment]
```
RESULTS for dfip-2206-a
===========================
dfip-2206-a is approved by 408 votes majority
YES: 408
NO: 0
Neutral: 0
Total valid votes: 408
Total rejected votes: 59
===========================
```
[mnstate_validate.log](https://github.com/DeFiCh/dfips/files/8963901/mnstate_validate.log)
[validate_dfip-2206-a_failed.log](https://github.com/DeFiCh/dfips/files/8963902/validate_dfip-2206-a_failed.log)
[validate_dfip.log](https://github.com/DeFiCh/dfips/files/8963903/validate_dfip.log)
