### ISSUE TITLE
DFIP #7: Destruction of all of DeFiChain Foundation-owned DFI

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#17]
## Overview

Foundation-owned DFI was initially set aside for use towards adoption and development of DeFiChain. With the establishment of on-chain governance of DeFiChain and the intention of further decentralization of DeFiChain, DeFiChain Foundation should no longer play the custodian of such coins and should therefore be destroyed.

## Proposal

Destruction of all of foundation DFI, which is currently sitting at addres: `dJEbxbfufyPF14SC93yxiquECEfq4YSd9L` and holds  273,713,999.9999 DFI as at block 769,000.

Upon approval, this proposal will be implemented during one of the the upcoming hard forks.

## Stage

- [x] Voting
- [x] Results

## Voting

Masternode snapshot will be taken on the first block after Wednesday, 14 April 2021, 12:00 UTC.

Voting will open for 1 week, until first block mined after Wednesday, 21 April 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `dfip-7 yes`
- No, I do not agree. Sign: `dfip-7 no`
- Neutral. Sign: `dfip-7 neutral`.

## Results

TBC

**Comment by aentan** [comment]
Can't wait to start voting!

**Comment by bpid** [comment]
> Can't wait to start voting!

Dito

**Comment by AltCoiFish** [comment]
**#dfip-7 yes**
**votes:** 2 
```
# MN-01 
./defi-cli signmessage 8aYs7CbU7tJX3GWR8LLh5zdGy8aum93EtF "dfip-7 yes"
IBnAxstZCpPKPvn5k/UYqctAoGttKv+O96dImtye0KLCHZwR+prM67Yl0x/8sqW5zUTt6Pdg9NLHsxVjUExZmv4=

# MN-02
./defi-cli signmessage 8QsqxT7kBPNNxM4pJEUSKDUFQHVmzVM8xm "dfip-7 yes"
HzCeELEMQ1eAQvVn9uhjIFQgIo/nLknyRQlmC/dfD1YpPm3rnXxDi3ZLE7HK4zvTBWINewHzRbAvBc/ty9hTA3Q=
```
**comment:** Trying it make an impact with my two votes, we as the community only are running aprox. ~50 Masternodes out of the 15.000 total Masternodes.

**Comment by Fragharvester** [comment]
./defi-cli signmessage 8TdJfHtssZRguWq4GHkWQriP3SXCjMkmrY "dfip-7 yes"
ILtV5dwbasTZtN05YHe6t/rd5Uay4XOg0WDgChuXJDdALtV2CtH5TP72+tXlUl7FCHb22MBpxTnKTB9pl0Yz5Xg=

**Comment by mydefichain** [comment]
signmessage 8KGzpaCiYmsQV92MB6NcQa8YSyJthCBp9p "dfip-7 yes"
IKrUMwy7be2SxxPVFEPLF96DH0nV/hltK6cyIIdWa/pYGlEOpGnQ4Oatl/pf459h9LL6pz7GIR18BwlwW9OfvNQ=

signmessage 8WE22fhsM3qLGxSUC24xvumLFYhuyKArFG "dfip-7 yes"
IHfS00cNEyuIz5hRTwVCJUSmJPdJ1A5sWeiufQ9Oldq3WE80tm7m0ahitQT2UBW6p4bs4BZ+hhfzn+G1xpPi2Fw=

**Comment by mydefichain** [comment]
signmessage 8TQ91Xpu16CXajzbju37tMAvEvGFnw8ryk "dfip-7 yes" 
IEULZ3S1o96tr2+5O8HPDHPIq8X1AZYe6mAsYqVMM0H8L06hg0FKrNCqb/9AIKrLWCg1YIIrm58Rs/jaQhoFoiQ=

**Comment by bpid** [comment]
signmessage 8UckaUyAE1zE9UHYjNNadTRuiXoYquxyAB "dfip-7 yes"
H/e0Qo2DwwuvjDvHT+yyXXdbfW8HbfU5ysxL9p+Ex2nnfFCmPgLAP37txLIGTANcGLmj+GZTH6L0Z0NxVSzDs1o=

**Comment by bpid** [comment]
signmessage 8UckaUyAE1zE9UHYjNNadTRuiXoYquxyAB "dfip-7 yes"
H/e0Qo2DwwuvjDvHT+yyXXdbfW8HbfU5ysxL9p+Ex2nnfFCmPgLAP37txLIGTANcGLmj+GZTH6L0Z0NxVSzDs1o=

**Comment by DeFiChain-Masternode-Owner** [comment]
./defi-cli  signmessage 8GxgZF426Ps1mAgaxxojVyAyXoBb1WmDVD "dfip-7 yes"
IJi/MDDbe9B3Gyj8LmaHr6iNoFdgEHWkEy7IBxwaLIkkRgKlXC0Gk/GS7n3CVkgXHxWrIXotuH5Q38kbhuCBJNI=

./defi-cli  signmessage 8MbEx6XVgDtLzcTac4DmFY7x7xoqzGxhJQ "dfip-7 yes"
IL5bI3g4dRBxocdV0p1wFQN+OO4ok2MbZ2ixGHP9+/AxO9HPwNxAooa57Lr7mqDCdPqI8VUCt9yolZEy2kO0cWA=

./defi-cli  signmessage 8Nkru2thjfymJfL4BRndnUdVrYLrWALdge "dfip-7 yes"
IKGcytr+wmxFTTbJnZIQsSK33CoIlPctZH9JkqQ0fh1yPV7U1xU0Z5M+U8JtvNoF5p9RmXVNQq4WBw0x8S6aCcI=

**Comment by Tempofranz** [comment]
PS C:\Users\tempo> C:\Users\tempo\defichain-1.6.3\defichain-1.6.3\bin\defi-cli -conf="C:\Users\tempo\.defi\defi.conf" signmessage 8LMvQ674xy8uP9YQ2xhr8FTAjoFavo9J9y "dfip-07-yes"
IKZ5H5muTirS3dohJEtvnwiXpl9SGOQLh4kSFngob7rDGmOFAcBISmSo4fY846YFVMMrkaIv5+jYMFuTquMly6k=

**Comment by mydefichain** [comment]
signmessage 8bGK3WhTYEPqTryf4kNE1CCws8SMQfr524 "dfip-7 yes"
H6VtXbMX+oJP2NJdcjRtvwgeG4FhxR/HED0SuqWd83ISOwqqkJ1lhsqj4kWkYJSc+v5Iu/4yIAycDwpPa+u+YAs=

**Comment by mydefichain** [comment]
signmessage 8VZARaBZdA1wnykw92mdWcQKW7wVA8qADB "dfip-7 yes"
H4lsR6GeEkbrZjZoH2ML5iRI2ljj1JRveRxbMRz25/X9Rh0NlKjXIOG2evFJ+kWBNw8Al81Psu9xeaKU612nWYk=

**Comment by Tempofranz** [comment]
signmessage 8LMvQ674xy8uP9YQ2xhr8FTAjoFavo9J9y "dfip-07 yes"
H82XGM//28glTR3L7uR7sxRsHq5Xi/au0NmUgpZzskOlfbrgSjfs995d4TN1FcebjulxB8ro/v/Av5d3nBPckFA=

**Comment by Klein-Magnus** [comment]
./defi-cli signmessage 8G4z72BsZgji1Bf7XezKGwtdwon5QrFL15 "dfip-7 yes"
IP+c6bjahTwmcYZdFxhvAwOtCbM3ZaH126WvlmfmWmVhPyvO3E/pDiDua0wal+c8zxe/XOE71/ZYmV/RwuEyIhM=

**Comment by Muromez23** [comment]
What a great example of direct democracy:) Greeting from Switzerland:)

**Comment by andreattafabio** [comment]
**Raw voting results - Cake**

Survey is carried out by Cake DeFi to their stakers.

Raw voting results: https://docs.google.com/spreadsheets/d/1QlI4Vd8tJvrIwuPWqZSluw7OQbNxqwcUS68y1tbu9Fc/edit?usp=sharing

**Comment by surangap** [comment]
```
RESULTS for dfip-7
===========================
dfip-7 is approved by 741 votes majority
YES: 746
NO: 5
Neutral: 0
Total valid votes: 751
Total rejected votes: 2
===========================
```

**Comment by surangap** [comment]
```
Rejected votes
Verify message failed for "defi-cli  verifymessage 8UckaUyAE1zE9UHYjNNadTRuiXoYquxyAB H/e0Qo2DwwuvjDvHT+yyXXdbfW8HbfU5ysxL9p+Ex2nnfFCmPgLAP37txLIGTANcGLmj+GZTH6L0Z0NxVSzDs1o= "dfip-7 yes""
Verify message failed for "defi-cli  verifymessage 8LMvQ674xy8uP9YQ2xhr8FTAjoFavo9J9y H82XGM//28glTR3L7uR7sxRsHq5Xi/au0NmUgpZzskOlfbrgSjfs995d4TN1FcebjulxB8ro/v/Av5d3nBPckFA= "dfip-7 yes""
```

**Comment by smitpau** [comment]
Shouldn't the results "TBC" by updated?
