### ISSUE TITLE
Announcement: June 2022 special voting round for DUSD

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#170]
## Key notes
1. This is an out-of-cycle special voting round to arrive at decision on actively discussed proposals related to DUSD. 
2. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal, 50 DFI for Vote of Confidence or 500 DFI for reallocation of block rewards. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
1. Once the fees are paid, update the issue with the txid.
1. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. Voting starts on Sunday, 19 June 2022 23:59:59 UTC with masternode snapshot taken on the first block mined after the time.
1. Voting concludes on Wednesday, 22 June 2022 23:59:59 UTC. Final votes are to be posted on respective GitHub issue before the time.

**Comment by uzyn** [comment]
Following the discussion on:

- [Twitter Space](https://twitter.com/defichain/status/1537011515156484096)
- [Reddit](https://www.reddit.com/r/defiblockchain/comments/vdp0td/solving_the_dusd_peg_result_of_twitter_space/)

The DFIPs to be voted on for this special round are:

1. https://github.com/DeFiCh/dfips/issues/162
2. https://github.com/DeFiCh/dfips/issues/163
3. https://github.com/DeFiCh/dfips/issues/164
4. https://github.com/DeFiCh/dfips/issues/165
5. https://github.com/DeFiCh/dfips/issues/166
6. https://github.com/DeFiCh/dfips/issues/167

**Comment by wmbst** [comment]
https://github.com/DeFiCh/dfips/issues/160 should be added to this special voting round. As it 100% serves the same purpose as the dfips listed here. I guess you forgot to add it as I don't see any reason why it should not be included.

**Comment by uzyn** [comment]
@wmbst We can, it wasn't initially added so that it can have a full voting round, if you would like #160 to be included in this special round we can do that as well.
