### ISSUE TITLE
Announcement: August 2022 voting round

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#199]
## Key notes
1. Please submit your DFIPs and CFPs by the cutoff dates to https://github.com/DeFiCh/dfips/issues. Use the CFP or DFIP template when you create the proposal.
1. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal, 50 DFI for Vote of Confidence or 500 DFI for reallocation of block rewards. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
1. Once the fees are paid, update the issue with the txid.
1. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. All proposals are to be submitted by Monday, 22 August 2022 23:59:59 UTC and have its fee paid by the first block mined after the time.
1. There will be one week of project presentations and Q&A.
1. Voting starts on Monday, 29 August 2022 23:59:59 UTC with masternode snapshot taken on the first block mined after the time.
1. Voting concludes on Monday, 5 September 2022 23:59:59 UTC. Final votes are to be posted on respective GitHub issue before the time.
1. Announcements of results should be in by Wednesday, 7 September 2022.

**Comment by kynkong91** [comment]
# Confirm Proposal for Voting
- 3 DFIPs
- 19 CFPs

## DeFi Improvement Proposals (DFIPs)
1. [DFIP-2208-A: Payout 50% of DEX-fee to DUSD loans & introduce real negative interest rates #195](https://github.com/DeFiCh/dfips/issues/195)
2. [DFIP-2208-B: Move further rewards from DUSD-DFI to USDT-DUSD / USDC-DUSD Pools #201](https://github.com/DeFiCh/dfips/issues/201)
3. [DFIP-2208-C: CFP proposal fees should be in proportion to the amount requested & fee distribution to voters #211](https://github.com/DeFiCh/dfips/issues/211)

## Community Funding Proposals (CFPs)
1. [CFP-2208-01: Expansion to the Russian Community (CIS countries) (40 000 DFI) #188](https://github.com/DeFiCh/dfips/issues/188)
2. [CFP-2208-02: For moderation and technical improvement concerning the Telegram group: Crypto Steuern DACH (DFI 7860) #192](https://github.com/DeFiCh/dfips/issues/192)
3. [CFP-2208-03: Chain.report - Complete DeFiChain tax integration (115 000 DFI) #193](https://github.com/DeFiCh/dfips/issues/193)
4. [CFP-2208-04: Animated series for the DefiChain (7000 DFI) #194](https://github.com/DeFiCh/dfips/issues/194)
5. [CFP-2208-05: Hackathon for DeFi Meta Chain (350 000 DFI) #197](https://github.com/DeFiCh/dfips/issues/197)
6. [CFP-2208-06: Deepcoin.com listing (11 000 DFI) #198](https://github.com/DeFiCh/dfips/issues/198)
7. [CFP-2208-07: International Staking Provider - (300 000 DFI) #200](https://github.com/DeFiCh/dfips/issues/200)
8. [CFP-2208-08: DeFiChain Italia - Italian Community Expansion (20 000 DFI) #202](https://github.com/DeFiCh/dfips/issues/202)
9. [CFP-2208-09: DefiChain YouTube Italian formats - ITA DeFiChain News Show + Video Tutorial (20 000 DFI) #203](https://github.com/DeFiCh/dfips/issues/203)
10. [CFP-2208-10: DefiChain Swiss Army Knife - The Ultimate multi-tool for daily activities (15 000 DFI) #204](https://github.com/DeFiCh/dfips/issues/204)
11. [CFP-2208-11: Top 10 Exchange Listing (566 772 DFI) #205](https://github.com/DeFiCh/dfips/issues/205)
12. [CFP-2208-12: Additional Trade Show Smartcon (27 057 DFI) #206](https://github.com/DeFiCh/dfips/issues/206)
13. [CFP-2208-13: Learn & Earn Execution (512 658 DFI ) #207](https://github.com/DeFiCh/dfips/issues/207)
14. [CFP-2208-14: DeFiChain Lottery Pot (20 000 DFI) #208](https://github.com/DeFiCh/dfips/issues/208)
15. [CFP-2208-15: Historic Defichain Data, A Powerful Explorer, Correct Tax Reports (no-one has them) and Public Free API for Everyone (80 000 DFI) #209](https://github.com/DeFiCh/dfips/issues/209)
16. [CFP-2208-16: Economical Simulation Framework to Predict Effects of Consensus Changes on the Ecosystem (30 000 DFI) #210](https://github.com/DeFiCh/dfips/issues/210)
17. [CFP-2208-17: DefiCFP.org - cfp-tracking website (39 000 DFI) #213](https://github.com/DeFiCh/dfips/issues/213)
18. [CFP-2208-18: Auto-compounder & Automated Delta Neutral Strategy to attract TVL & help repeg DUSD (75 000 DFI) #216](https://github.com/DeFiCh/dfips/issues/216)
19. [CFP-2208-19: DeFiChain Captain - JellyfishSDK integration and performances improvements (5100 DFI) #217](https://github.com/DeFiCh/dfips/issues/217)

**Comment by prasannavl** [comment]
### All CFP payments in progress. Expected to be completed with 24 hours.

---

Progress:

- https://github.com/DeFiCh/dfips/issues/197
  - **[df1qwyjxqedndd0pcxke6kcpmp3xe2j5tsfdqkcxz9](https://defiscan.live/address/df1qwyjxqedndd0pcxke6kcpmp3xe2j5tsfdqkcxz9) 350000** // (35 * 10000) + 0
    - [94de776131bb045079584030b47672bdf0cbc9ce916d7139986bc13c14ac7605](https://defiscan.live/tx/94de776131bb045079584030b47672bdf0cbc9ce916d7139986bc13c14ac7605)
    - [d09134895bf3d9ea5c24d3c76544daa9435f157923a77297924932da33385e94](https://defiscan.live/tx/d09134895bf3d9ea5c24d3c76544daa9435f157923a77297924932da33385e94)
    - [8fe01d063f07b30a51e84120541bff2129c395aa715bb142467d917e8475f66e](https://defiscan.live/tx/8fe01d063f07b30a51e84120541bff2129c395aa715bb142467d917e8475f66e)
    - [9531063b61ea4ec057e2ab2a76a954f3cd002ac3917dd2dc36fe69935672c5db](https://defiscan.live/tx/9531063b61ea4ec057e2ab2a76a954f3cd002ac3917dd2dc36fe69935672c5db)
    - [1dd2cb183974e527df02c882f44f0a8f131487bb11dfb420da34ac8535a762f8](https://defiscan.live/tx/1dd2cb183974e527df02c882f44f0a8f131487bb11dfb420da34ac8535a762f8)
    - [86c1ab41b75ab6ea927879540235f44d7480eda3e9f72898b45fa6dd45905e6c](https://defiscan.live/tx/86c1ab41b75ab6ea927879540235f44d7480eda3e9f72898b45fa6dd45905e6c)
    - [148ad8eac8395e87d9ba25387a33630e8fe2c38b396036258a93f8a0680a6ff3](https://defiscan.live/tx/148ad8eac8395e87d9ba25387a33630e8fe2c38b396036258a93f8a0680a6ff3)
    - [cf91cc5998cf63cb351d6697dda4ce010acf532c208948d765e1059760254422](https://defiscan.live/tx/cf91cc5998cf63cb351d6697dda4ce010acf532c208948d765e1059760254422)
    - [60e1b6e463c5a6d09f1d62d25802f4ff0ee2fd51161b8b28c394eb9847669b2e](https://defiscan.live/tx/60e1b6e463c5a6d09f1d62d25802f4ff0ee2fd51161b8b28c394eb9847669b2e)
    - [062836abfe23c805e4b89396b9239689e3448923b893af150a53c355394c834d](https://defiscan.live/tx/062836abfe23c805e4b89396b9239689e3448923b893af150a53c355394c834d)
    - [8bca7130d2abf3fdb60c8a8f12305e4f93f5f4d34f9652d5ce398c3f76401b03](https://defiscan.live/tx/8bca7130d2abf3fdb60c8a8f12305e4f93f5f4d34f9652d5ce398c3f76401b03)
    - [e84121880f96c0cf870085a16c71c8f41c1d76a0b680c2d4ab690799cf0c2dc5](https://defiscan.live/tx/e84121880f96c0cf870085a16c71c8f41c1d76a0b680c2d4ab690799cf0c2dc5)
    - [d3c71aad450095011c732dbf900a19d5ed408f725c686a380098d4882011187f](https://defiscan.live/tx/d3c71aad450095011c732dbf900a19d5ed408f725c686a380098d4882011187f)
    - [d79f4b6f9f8303fe388214ac3df63666319ff290e08e876ae11946db7d4d2fe5](https://defiscan.live/tx/d79f4b6f9f8303fe388214ac3df63666319ff290e08e876ae11946db7d4d2fe5)
    - [3194c0dff0ff524054e5a9b86c9c3438de8cc1406b11c2eed4bffcd21300a3a8](https://defiscan.live/tx/3194c0dff0ff524054e5a9b86c9c3438de8cc1406b11c2eed4bffcd21300a3a8)
    - [2b146ab2b33ce10832f25aa56cce81f76d6ed0263ebeb591289e8634c621d99a](https://defiscan.live/tx/2b146ab2b33ce10832f25aa56cce81f76d6ed0263ebeb591289e8634c621d99a)
    - [4fd495f66d03931e32a8da19de6f2bb73a484f8c37409734feddb858497fba30](https://defiscan.live/tx/4fd495f66d03931e32a8da19de6f2bb73a484f8c37409734feddb858497fba30)
    - [daad8b9d00b08e515f8e2d44853ec8a5507636fa2e81c8b80f2ed7170c8ade2e](https://defiscan.live/tx/daad8b9d00b08e515f8e2d44853ec8a5507636fa2e81c8b80f2ed7170c8ade2e)
    - [7715fcdb0fa67ac0b81781f595de5614cd738aa076965c244003b63ba2462d33](https://defiscan.live/tx/7715fcdb0fa67ac0b81781f595de5614cd738aa076965c244003b63ba2462d33)
    - [23a4dd78fd511b404bb410291fb613196bdbd29fa2132f16e7da1241c0459690](https://defiscan.live/tx/23a4dd78fd511b404bb410291fb613196bdbd29fa2132f16e7da1241c0459690)
    - [9fb4110c7b58f016cf51a5253382897ab7828c69fbd95b43de33928502785d7c](https://defiscan.live/tx/9fb4110c7b58f016cf51a5253382897ab7828c69fbd95b43de33928502785d7c)
    - [9b27303d0f01eab62f34c325195ef1bcdb5a86a7b4f54184790af06391f783b8](https://defiscan.live/tx/9b27303d0f01eab62f34c325195ef1bcdb5a86a7b4f54184790af06391f783b8)
    - [7d9406fb4d3306404f48259b992229c1b1f247f40998e03a10dc131f406f211e](https://defiscan.live/tx/7d9406fb4d3306404f48259b992229c1b1f247f40998e03a10dc131f406f211e)
    - [b10fcaf187adb18eec713274cf2a7b9b67c95e3839dfbbd21ee549da604f7891](https://defiscan.live/tx/b10fcaf187adb18eec713274cf2a7b9b67c95e3839dfbbd21ee549da604f7891)
    - [8c6e08139b8847f2c38c35ee9ac835de050303a6bd9075c26bc1995c5d1ac2db](https://defiscan.live/tx/8c6e08139b8847f2c38c35ee9ac835de050303a6bd9075c26bc1995c5d1ac2db)
    - [0b3527104045b8958747657f65f1fe11cec33e87e90735a2557b66ba78efdd95](https://defiscan.live/tx/0b3527104045b8958747657f65f1fe11cec33e87e90735a2557b66ba78efdd95)
    - [57aa7ff1b3808e4c585922c9b1e2f556567906ac54c940c84d6b82e62f2299b8](https://defiscan.live/tx/57aa7ff1b3808e4c585922c9b1e2f556567906ac54c940c84d6b82e62f2299b8)
    - [43f69d2c4b061a6ce1c30c495f109a66a5e97bbd2bcc61e300ffc8822551e59f](https://defiscan.live/tx/43f69d2c4b061a6ce1c30c495f109a66a5e97bbd2bcc61e300ffc8822551e59f)
    - [2f67f4f6bfe8680d488f31b2da1910a75a095b6b1b2edc3bee15394545eddec3](https://defiscan.live/tx/2f67f4f6bfe8680d488f31b2da1910a75a095b6b1b2edc3bee15394545eddec3)
    - [1150ce7321dcd4c141906ecf98bd9e3d3afac69e9dca6d670df9172afb0c2e4e](https://defiscan.live/tx/1150ce7321dcd4c141906ecf98bd9e3d3afac69e9dca6d670df9172afb0c2e4e)
    - [ce9faf2b512dc63f65094132bd3e86b664e2dc79a3d4662e15857fbe78a60e75](https://defiscan.live/tx/ce9faf2b512dc63f65094132bd3e86b664e2dc79a3d4662e15857fbe78a60e75)
    - [98840a112e6a7257510f148facfb55b0f598284787bbc97d3545faa40d55fbc4](https://defiscan.live/tx/98840a112e6a7257510f148facfb55b0f598284787bbc97d3545faa40d55fbc4)
    - [4b0aca802982467bc7c8281d30e44b3c9c487f229f70eccbba9e2d14931a2f8d](https://defiscan.live/tx/4b0aca802982467bc7c8281d30e44b3c9c487f229f70eccbba9e2d14931a2f8d)
    - [225ed8137ca64f4fdc8a5630a3c379d8332c8a4bdee9bc43b9e4cff17cd4c715](https://defiscan.live/tx/225ed8137ca64f4fdc8a5630a3c379d8332c8a4bdee9bc43b9e4cff17cd4c715)
    - [edcaa60d335edf8bff92067c732cdb522d20cdae2a9d65bb6b7841df993142d0](https://defiscan.live/tx/edcaa60d335edf8bff92067c732cdb522d20cdae2a9d65bb6b7841df993142d0)
- https://github.com/DeFiCh/dfips/issues/202
  - **[dX1mtvoRE6tYghLCBfb215TXXH5P4K7yrz](https://defiscan.live/address/dX1mtvoRE6tYghLCBfb215TXXH5P4K7yrz) 20000** // (2 * 10000) + 0
    - [a701ed9457ab67f6333074ec4abfb861c370086d21f1e5542d6c6e15ff423a3c](https://defiscan.live/tx/a701ed9457ab67f6333074ec4abfb861c370086d21f1e5542d6c6e15ff423a3c)
    - [06296d49e5926bf7aba63fdd170eaadc8c7c2f947584161f6874f9f0e29e1180](https://defiscan.live/tx/06296d49e5926bf7aba63fdd170eaadc8c7c2f947584161f6874f9f0e29e1180)
- https://github.com/DeFiCh/dfips/issues/203
  - **[dPyRuQG2ZCaDHPRwxX7hhsvoXXmvaPPGTt](https://defiscan.live/address/dPyRuQG2ZCaDHPRwxX7hhsvoXXmvaPPGTt) 20000** // (2 * 10000) + 0
    - [2009d54bfb6c8777e89f8bd4aabf70cb034eecdcfa978207b353c4e4ff0ede17](https://defiscan.live/tx/2009d54bfb6c8777e89f8bd4aabf70cb034eecdcfa978207b353c4e4ff0ede17)
    - [856395690bc6530ba596837f8b76793c39afa5ab25cc632d5f2624a65ac75ac6](https://defiscan.live/tx/856395690bc6530ba596837f8b76793c39afa5ab25cc632d5f2624a65ac75ac6)
- https://github.com/DeFiCh/dfips/issues/205
  - **[df1qp530rjj8p0yan5wxnqvn2ssnhmedm024zpjs69](https://defiscan.live/address/df1qp530rjj8p0yan5wxnqvn2ssnhmedm024zpjs69) 566772** // (56 * 10000) + 6772
    - [9e7b7bd00abf9f4bdbea687ea5ae3191ec549ae1d8d8f8d4bb69164eb4d39175](https://defiscan.live/tx/9e7b7bd00abf9f4bdbea687ea5ae3191ec549ae1d8d8f8d4bb69164eb4d39175)
    - [22dbc75d8a2bc25804ea94b7df9d894683b0c2314992164a72479d8e94e22f5f](https://defiscan.live/tx/22dbc75d8a2bc25804ea94b7df9d894683b0c2314992164a72479d8e94e22f5f)
    - [e7679bf984d7d34fa40a425cfb6361b0128e07c8af1e40e4d04471eb1c2531da](https://defiscan.live/tx/e7679bf984d7d34fa40a425cfb6361b0128e07c8af1e40e4d04471eb1c2531da)
    - [0e1c0fe141e3874020aa490ba7084f9c66dde6aaf36d70bb6702a98a8fd34607](https://defiscan.live/tx/0e1c0fe141e3874020aa490ba7084f9c66dde6aaf36d70bb6702a98a8fd34607)
    - [c9db971ecc35197e381f39ce496431caa512785f48c092dd9b708b1372cc942c](https://defiscan.live/tx/c9db971ecc35197e381f39ce496431caa512785f48c092dd9b708b1372cc942c)
    - [565124acfe630057050c8b342e8d8cbdfe4bf3ec9ada8a4ba3b4b5ca0551c15f](https://defiscan.live/tx/565124acfe630057050c8b342e8d8cbdfe4bf3ec9ada8a4ba3b4b5ca0551c15f)
    - [ba19ec257f039e968505e885518af97ab3ab4de7b71847e381de964c6940bebe](https://defiscan.live/tx/ba19ec257f039e968505e885518af97ab3ab4de7b71847e381de964c6940bebe)
    - [5bec4bf57d467b9aa42de92ffa3730b754c49ea536b1b5054f2a3c840f8a49db](https://defiscan.live/tx/5bec4bf57d467b9aa42de92ffa3730b754c49ea536b1b5054f2a3c840f8a49db)
    - [de413feee266ab4032ed39e87eff5117073503f279f664f6e182054eae957b0a](https://defiscan.live/tx/de413feee266ab4032ed39e87eff5117073503f279f664f6e182054eae957b0a)
    - [a80e262f47af4ebaf4089052620b141a124f1ea1af42fe9da10ca2736de3ba80](https://defiscan.live/tx/a80e262f47af4ebaf4089052620b141a124f1ea1af42fe9da10ca2736de3ba80)
    - [161fcd6d24ea089bcdc5aded1190be683d4dedeeeca13c0b7028a85116c9779d](https://defiscan.live/tx/161fcd6d24ea089bcdc5aded1190be683d4dedeeeca13c0b7028a85116c9779d)
    - [07da1715e4894532b4440c37150461fbd836ca108ce4aedae94332df33ae3078](https://defiscan.live/tx/07da1715e4894532b4440c37150461fbd836ca108ce4aedae94332df33ae3078)
    - [f0b1082559868c2924805668c0ff5f1c9c2d34d6c649e5337c0863912a51b335](https://defiscan.live/tx/f0b1082559868c2924805668c0ff5f1c9c2d34d6c649e5337c0863912a51b335)
    - [833112356779cf081068627d94b55a12ef5799149af77fc3a48e8a3bc4ef63a6](https://defiscan.live/tx/833112356779cf081068627d94b55a12ef5799149af77fc3a48e8a3bc4ef63a6)
    - [47bf0e141909340103ec5330cad44191d0aa609aad8755860eb09d4a71bb665d](https://defiscan.live/tx/47bf0e141909340103ec5330cad44191d0aa609aad8755860eb09d4a71bb665d)
    - [1122298c84f4d13bf2990a1a0d5df9d2147607e72f6eaf615c55a36f5cb5c455](https://defiscan.live/tx/1122298c84f4d13bf2990a1a0d5df9d2147607e72f6eaf615c55a36f5cb5c455)
    - [b55b782cd8eea5685227fa48b44dc14602a8108e37b93718eae17b8597347239](https://defiscan.live/tx/b55b782cd8eea5685227fa48b44dc14602a8108e37b93718eae17b8597347239)
    - [0bbcd43b3676aefae6edc05474921084ab53cfadc25135fe661e207f9ecb815b](https://defiscan.live/tx/0bbcd43b3676aefae6edc05474921084ab53cfadc25135fe661e207f9ecb815b)
    - [2fac4424ef183d09d7269a93dd823392fdf5fd58f41666185a27788db701a24b](https://defiscan.live/tx/2fac4424ef183d09d7269a93dd823392fdf5fd58f41666185a27788db701a24b)
    - [2979b7a4ad38be7b87d68713a1c5111caca15e58e0f60d7d12513e054cf0724e](https://defiscan.live/tx/2979b7a4ad38be7b87d68713a1c5111caca15e58e0f60d7d12513e054cf0724e)
    - [3006d163eab7358bbed9feff543ae4e1fe2778c9160711dcfc6cf8388b5dbdc8](https://defiscan.live/tx/3006d163eab7358bbed9feff543ae4e1fe2778c9160711dcfc6cf8388b5dbdc8)
    - [377b4c58c17989c66be5603e54776cd676d27becbebbd7bb5ac29b865ce69621](https://defiscan.live/tx/377b4c58c17989c66be5603e54776cd676d27becbebbd7bb5ac29b865ce69621)
    - [c965b1eab9072d0c3b7a02396a93ec4ad2b217ef3d64f76f3c8b10e1b0c86559](https://defiscan.live/tx/c965b1eab9072d0c3b7a02396a93ec4ad2b217ef3d64f76f3c8b10e1b0c86559)
    - [cb8dbefafa0fa9e0888d2a38dcde28ecc47b06823ffcdba1c50f49b93b1ab458](https://defiscan.live/tx/cb8dbefafa0fa9e0888d2a38dcde28ecc47b06823ffcdba1c50f49b93b1ab458)
    - [0d98bebd891fc4786ab358a1a4866fe764646a169cfa16fb02635a5cfb520467](https://defiscan.live/tx/0d98bebd891fc4786ab358a1a4866fe764646a169cfa16fb02635a5cfb520467)
    - [9d17c0bfab9025a6d4609c15b4305efff1e65aa28a66c92db1a5258ac8f99933](https://defiscan.live/tx/9d17c0bfab9025a6d4609c15b4305efff1e65aa28a66c92db1a5258ac8f99933)
    - [2dc193dfc97973c2e06f2ce29a95962ec4e105f93b6f1d7ab8b3d67fc3de0eda](https://defiscan.live/tx/2dc193dfc97973c2e06f2ce29a95962ec4e105f93b6f1d7ab8b3d67fc3de0eda)
    - [ac2f56fd41c8398bb73fc11d9fd6845e1a660b8f87c463bfa24d58e9530bad7e](https://defiscan.live/tx/ac2f56fd41c8398bb73fc11d9fd6845e1a660b8f87c463bfa24d58e9530bad7e)
    - [5cf2746579d120190883f7b1eb9220808789123492ef43375f0795d5e2e0b825](https://defiscan.live/tx/5cf2746579d120190883f7b1eb9220808789123492ef43375f0795d5e2e0b825)
    - [e90bb84911c758f91fd6f8da40bc478b000c5547714c2301906dc07d153e1803](https://defiscan.live/tx/e90bb84911c758f91fd6f8da40bc478b000c5547714c2301906dc07d153e1803)
    - [2f76026a5fd1fff4ec92a5a9be526879250634ebad232fc743a2068327484ecb](https://defiscan.live/tx/2f76026a5fd1fff4ec92a5a9be526879250634ebad232fc743a2068327484ecb)
    - [5db6f6ac82d9bf016f8f78a6d399d57221d0b222d3b41cb20b44a014a712230f](https://defiscan.live/tx/5db6f6ac82d9bf016f8f78a6d399d57221d0b222d3b41cb20b44a014a712230f)
    - [5ae6a9e520ad6b4beedd31fa88428e0be6914fdb3c6e68b6c3f26a64186318f7](https://defiscan.live/tx/5ae6a9e520ad6b4beedd31fa88428e0be6914fdb3c6e68b6c3f26a64186318f7)
    - [6faca5efaf05bc5d3d4769302a80e9de72628f029717d942d0448955838ccd3f](https://defiscan.live/tx/6faca5efaf05bc5d3d4769302a80e9de72628f029717d942d0448955838ccd3f)
    - [bdaf8163c196eb1f07cd99d00f0b2049994baafb6b5288977ad22dbb6e774c36](https://defiscan.live/tx/bdaf8163c196eb1f07cd99d00f0b2049994baafb6b5288977ad22dbb6e774c36)
    - [3fafe66910ca04fe0fdbc5efbcaa3ee74359297b8650b1c1eb9e6b97c869ae75](https://defiscan.live/tx/3fafe66910ca04fe0fdbc5efbcaa3ee74359297b8650b1c1eb9e6b97c869ae75)
    - [ab471f4c431ba2ec10e8904b160e4ec764a060fc045d535fcb974362f4211906](https://defiscan.live/tx/ab471f4c431ba2ec10e8904b160e4ec764a060fc045d535fcb974362f4211906)
    - [acbbf52d86fd85007694456c3f471d7212960922b17e297d7f46f096a77cc8c0](https://defiscan.live/tx/acbbf52d86fd85007694456c3f471d7212960922b17e297d7f46f096a77cc8c0)
    - [1684abc5c80b711067e1521a4f8532fff88147313800db55c7fa5a7dfd490024](https://defiscan.live/tx/1684abc5c80b711067e1521a4f8532fff88147313800db55c7fa5a7dfd490024)
    - [0a8ac24d0a5f03602b88d4cc5250186ee4b7063dfdb988326345b4d421d895fd](https://defiscan.live/tx/0a8ac24d0a5f03602b88d4cc5250186ee4b7063dfdb988326345b4d421d895fd)
    - [7228d23b194b00a2617c2962bd7b1ad2838198adf206637d0d9bb3e5b7a6982c](https://defiscan.live/tx/7228d23b194b00a2617c2962bd7b1ad2838198adf206637d0d9bb3e5b7a6982c)
    - [03e9b77ea4c4097da4d53137bbb9fb08fc1422db3721d72d47d9557f263376bd](https://defiscan.live/tx/03e9b77ea4c4097da4d53137bbb9fb08fc1422db3721d72d47d9557f263376bd)
    - [f94693efce83e1a3ae44d9877f710a264441e4741ccbf3fa327409f5e60bc579](https://defiscan.live/tx/f94693efce83e1a3ae44d9877f710a264441e4741ccbf3fa327409f5e60bc579)
    - [729ea1f29d7334b2646deada6269879c3f2ce5ac01c27328230c7635e1e45ffc](https://defiscan.live/tx/729ea1f29d7334b2646deada6269879c3f2ce5ac01c27328230c7635e1e45ffc)

---

If there's any issues or discrepancies, please feel free to let us know. Thanks and cheers!
