### ISSUE TITLE
DFIP #2: DeFi incentive funding

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#2]
## Overview
DeFiChain will be launching various decentralized financial (DeFi) transactions soon. As with all financial services, centralized or decentralized alike, liquidity is key in adoption. An exchange with a bare order book would not be attracting much trading action. 

Yield Farming is created for the same reason, to drive adoption and action for many DeFi activities, especially that of new protocols and services. DeFiChain requires a mechanism for us to drive adoption.

### Increasing miner reward
With the recent move by DeFiChain Foundation to unstake all its 288 nodes, and placing them into a single [publicly-verifiable address](http://explorer.defichain.io/#/DFI/mainnet/address/dJEbxbfufyPF14SC93yxiquECEfq4YSd9L), staking reward for DeFiChain has seen a major increase in yield. Before this move, stakers receive about 25% - 28% of mining reward p.a., since the unstaking of foundation nodes, stakers now receive 50% - 60% of mining reward p.a.

## Proposal

25% of miner reward to be set aside into a smart contract for DeFi incentive funding. 

If this proposal and the previous one (#1) passes, block reward would look as follows:

- 135 DFI as mining reward for masternode
- 45 DFI goes to DeFi incentive funding smart contract
- 19.9 DFI goes to community fund
- 0.1 DFI goes to Bitcoin anchor reward smart contract

Upon approval, this proposal will be implemented during the next hard fork.

## Stage

- [X] Request for Comment (RFC)
- [X] Voting
- [X] Result - PASSED

 This proposal is currently on RFC stage for discussion. Once it gets the initial general understanding and acceptance, it will then proceed to voting stage. Voting will be conducted by masternodes. As this is likely one of the first votes of DeFiChain, voting instructions will be announced in due time.

## Voting

Masternode snapshot will be taken at block 294,000 of DeFiChain mainnet.

Voting will open until Monday, 21 September 2020 00:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `dfip-2 yes`
- No, I do not agree. Sign: `dfip-2 no`
- Neutral. Sign: `dfip-2 neutral`.

## Results

21 votes received.

20 masternodes voted for yes. 1 voted for no.

DFIP #1  passes.

**Comment by corneliakrause** [comment]
If you like to grow a business you have to invest in it. So I agree

**Comment by robcoins** [comment]
I would like to see Pool By Cake giving us plenty of slices in a long term.  I would go for it.

**Comment by wkadar** [comment]
We need more user numbers led to more volume and capital.
To get more capital we have to open the gates.
Can we assume that the open gates will be safe?
The value in Cake Defi Trust has a big opportunity to grow. 
I vote for it.

**Comment by PerDom** [comment]
I like the idea. I'll vote for it.

**Comment by mksigyt** [comment]
dfip-2 neutral

**Comment by uzyn** [comment]
Masternode votes from Cake DeFi (https://cakedefi.com) for DFIP #2

## Raw voting results 

Survey is carried out by Cake DeFi to their stakers.

Details: https://medium.com/@cakedefi/cakes-processing-of-defichain-s-dfips-1-2-bfacb66dc986

Raw voting results: https://docs.google.com/spreadsheets/d/13xxMhm5_-wA_Yogng-mtU3p0zRUJ-tG7NeOHOJj0q8A/edit?usp=sharing

### 20 masternodes for **YES**

```
$ defi-cli signmessage 8VEcBnvWg4HrC1Qt1iYQJ3Vvuf252msaRU 'dfip-2 yes'
H+uWDe9vUxafnx9EwbGY48uyIKen1x4CmLoYpALC3sP/V1CWbuYiREAha//C/0n/VLfzGm67YTgLJUtVvbrrrTw=

$ defi-cli signmessage 8GDQwiYrQxomXNgtrnn1Rtd2r7sCBsuoDt 'dfip-2 yes'
H2OnSYk5Upb+yxeeQMyi1Omlf8egBR9IOlCbd6ZZ1LPmFeDdvcFqqwpl1y6296as/OU9qfFhcRvaNjsUBcZwiAU=

$ defi-cli signmessage 8UirEzTmzJe3qFjKNCamNi4BxWZhKNK2vM 'dfip-2 yes'
ILX4L5mCNv9TWarwm5Bia/WRTyHf0rIvl/IMuwL8YRlmQPUe/TtoN2isBsTtPwrL+kg7lU8Q67QVugxfAURueYI=

$ defi-cli signmessage 8Pyhd746fsFPtAdbCdn2dBkthCeFty9jmX 'dfip-2 yes'
IKKierkJzVPkDBlgxEQ/anY8JC64GTP2GWCFzKdqfNkVKs4OvSW+V4HO6k6YjpM/+eqxXKq0UcPl6RK0h025pYU=

$ defi-cli signmessage 8Pv6Tydvq58f8koa3rEXrz7aRV658SdsCJ 'dfip-2 yes'
H4NWCtcjgsYr3KUIGVxadlnWvvJI3Y1qSrOBJIBCBnGBa7YVud4hi67GJT0l9kplu3s+MszkrSyUTUWbAgocIxo=

$ defi-cli signmessage 8Wq5Vm6Y9HtsCw4ziLiHcmtcqGJEHmtJ6N 'dfip-2 yes'
IPbX5HHxTj7DxzaRIuigVpc3IZ1B/E0zUxb7R4wu4BIPX3oe6B7VH+N2NWKwN6Yg6/9swsxH51fsxDepM39FMwU=

$ defi-cli signmessage 8KeF3owaWK3icc37HPWsPtUq5jrCiDa3sK 'dfip-2 yes'
H85nGGkocGsuDjxYZtfgexwPC8iGWRHIhUzDFp69mqcffd51oKkTlJidzmf7vy851tWHhpJJZ6le/adPEOJmbp0=

$ defi-cli signmessage 8FQ67ZMTNMEbpQEUzZ5MbAFKKfJTo1uLNx 'dfip-2 yes'
HxEnaKo8xq44ehqPCQmEGU97gJ/xu4pch8MUNgOevkX9ZtFIkuzWCXMBITyXi6sDZDwJTGtB5sg+cqLJRMjQf2M=

$ defi-cli signmessage 8aw7NdLgTMRE7T59U4qPTbQNcuc2cC7rGB 'dfip-2 yes'
IL5+K2xZUgQp8y5DdWopmtqR63HXaLDxjG8QLl9NohkoCcAivgZW//YsFQGJZlpFyLl2WeKu1LXLchG/Y3hwMus=

$ defi-cli signmessage 8FphQuBa25UGYAK9F6HB3bh6ukRSbRsGMn 'dfip-2 yes'
IDYgG0NgVFVyDvHrF5jC+I84IXXlVC03nKKBPyqIP765B0IrMrP1O8p5n9+yyk68nqNwqxtc6Vo9n9qzyCsTotQ=

$ defi-cli signmessage 8WU4jSULSSc7Lz8xi6T8Qe6RXYmEno3YfZ 'dfip-2 yes'
HxE3X63WzSDqBZQSAkypoRDbcu2c/U+yYQZq/3KYwAVQLOutxU7fODlwSL83WaPlmddiwAtFsQTeg/nedPvKs9s=

$ defi-cli signmessage 8PTT1Yk89hbmUfgizxDyiCV8iMj46Uod3f 'dfip-2 yes'
ILzuG/78NQMitp4rTyKjYcG9eFd9MYyX5FG9GXs0PuRcK6qbpVepBlnhP9hmum4fuCWIwTbwv1QhhLjHt1jLBnw=

$ defi-cli signmessage 8RgFCLH6A99sZiiZdoamhbUJgCvMTWJuMk 'dfip-2 yes'
ILIIA5zaRbg4iFoojgL7zWZRYzmeHlw5eREkiD7HmAGjP7fKQE0Yeu9v7nXqO+lO91YTORTP/1KO+SzcOKhs1Ew=

$ defi-cli signmessage 8Wm14DjR6kiohatcmigKZUsAB6e9padB5j 'dfip-2 yes'
IGVfO+Y4OcND7GKXseO4MVMhgyo8bXqBXY2qzl2R0DlXXkxSbdon4qy0d3eD+rka4qhRb+bvuvwXinZpZGb77qk=

$ defi-cli signmessage 8S6dXTmZxb6hxEe9k4DEJbANDmqUqEjtFW 'dfip-2 yes'
H8K+NwYMh3N6Etivm0hOxahvcyhFmotB+4Lgec4+ghWbFQMVYiP/xritCcUfrRwHA5B9gzdey+ZQ+sMYvnco1TY=

$ defi-cli signmessage 8LnqhZQzFVwwaX7TUrTw3ckUffuz1pLYTf 'dfip-2 yes'
H0oqMbfneDgpSO/LZHF56KVVJ3QayS9FNSkg8oRjh3CSdy8eX+GEZxbdE/xhz5I8UwtUnXBA6JJBC84HS+1Y9bI=

$ defi-cli signmessage 8LiBz8jzjipCbZ3tMpivWYbP5DjCaK2dCp 'dfip-2 yes'
Hw1+h7MiQmy8jZ3eS//RVhdf0hd3lj+OhNT/Sxbt3UPHCbVXed7aYUphCedm3FipWbDzpq/Gm7y+JLhMd4OyvZM=

$ defi-cli signmessage 8VwszPSzgpJ7mDrck3GKdC5EVPpbifyPES 'dfip-2 yes'
IL8wSMCDq3j6m+D5hTgAUPXQ058J60r5cw6T8Zn0r3FhAZCUr07Jx5i6OXsnGVBi+ywGree0eDUHnG6ruFWhlCg=

$ defi-cli signmessage 8GarTcQUsmXoPtFN3Ty25Dbn5RgmTpfeAj 'dfip-2 yes'
H91YEBzNM6c+UJr/BqMNX3379TLY46RSVq9KcHNl+SZrNDfaIz/nDbdwQlQ8HudLd4xiT2vRACi0jTRCL5DgeDs=

$ defi-cli signmessage 8TWEeZAbijMzoHqCBC48jnEykpktZNoJvo 'dfip-2 yes'
HwN/l+fbe4NSQuUbvLmrjpkt5G02sV245U6MBPWY9yEIUbcoy5LL/pgxxZIqXKGAP1g5UO9AFe5ThKyBGsn8Gvw=
```

### 1 masternode for **NO**

```
$ defi-cli signmessage 8K4RTe6TnYDf5VtuuQw7MkZMU8cW4Pimfz 'dfip-2 no'
H+oJX83EDc9xeCYfIv1G6afa6C3k5dJ7ywYjsfAMKAHkb9UhiyOLqcjqgcO+y5AUhtWctoQqpsPQvkWPZi5RJRY=
```
