### ISSUE TITLE
Community Funding Proposal (CFP) [Draft]: Contribution to DeFi Wallet [2,000 DFI]

### ISSUE THREAD

**Issue by sergejmueller** [DeFiCh/dfips#21]
# CFP Summary
- Github account: [@sergejmueller](https://github.com/sergejmueller)
- Requester: Sergej Müller
- Amount: 2,000 DFI
- Receiving Addresses: TBD
- Purpose: Contribution to the DeFi Wallet

**Please read through the thread thoroughly for the proposal.**

## Voting
Masternode snapshot will be taken on the first block after _TBD_.

Voting will open for 1 week, until first block mined after _TBD_. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options
1. Yes, I agree. Sign: `cfp-8 yes`
2. No, I do not agree. Sign: `cfp-8 no`
3. Neutral. Sign: `cfp-8 neutral`

## Results
TBC
___

## Original proposal
Sergej Müller contributed to the following wallet features and bug fixes:

### Pull Requests
- [Feature: Sidebar UI improvements](https://github.com/DeFiCh/app/pull/441)
- [Fix: tslint issues](https://github.com/DeFiCh/app/pull/448)
- [Fix: New wallet footer buttons alignment](https://github.com/DeFiCh/app/pull/444)
- [Fix: DE translations for „Tokens“](https://github.com/DeFiCh/app/pull/440)
- [Fix: Decimal string at tokens page](https://github.com/DeFiCh/app/pull/368)
- [Fix: Reorder „from“ & „to“ amounts at pagination bar](https://github.com/DeFiCh/app/pull/367)
- [Fix: Make „Enter word“ placeholder translatable](https://github.com/DeFiCh/app/pull/366)
- [Fix: Finalized translations for DE](https://github.com/DeFiCh/app/pull/365)
- [Fix: i18n output for searchBar placeholder ](https://github.com/DeFiCh/app/pull/362)
- [Fix: Add required Node.js version to package.json and .nvmrc](https://github.com/DeFiCh/app/pull/361)

### Issues
- [GitHub Workflow for Mac Build is broken](https://github.com/DeFiCh/app/issues/442)
- ["npm run start:electron" don't start the Electron app](https://github.com/DeFiCh/app/issues/438)
- [JS Error on the wallet page (empty wallet)](https://github.com/DeFiCh/app/issues/369)
- [JS Error on the "verify mnemonic seed" page](https://github.com/DeFiCh/app/issues/355)
- [JS Errors occurs on token create page](https://github.com/DeFiCh/app/issues/354)

**Comment by uzyn** [comment]
Appreciate your work there @sergejmueller but it shouldn't be for submission of pull requests. 

That's just my opinion. 
For this round we have sealed it as we have presented it. You can still submit it on the next round when we move to on-chain request.
