### ISSUE TITLE
DFIP: Getting rid of the Ticker Council immediately

### ISSUE THREAD

**Issue by DFI-Community-Vote** [DeFiCh/dfips#218]
### DFIP Overview
1. Requester(s): Someone who deeply cares about DFI
2. Reddit discussion thread: Not needed
3. Proposal fee (50 DFI) txid: 9968a596bddc5b0d23d6b17a83c3863185a37ebd2350d1f3e45ede6bdfa0c2c2

### Describe your proposal
DeFi is about DECENTRALIZED finance.
Right now, the power is mainly focused on one person,
who's misused the trust of the community.

### How does this DFIP benefit the DeFiChain community?
After getting rid of the centralized part of the blockchain,
I'd like the community to focus on what's good for DFI
(compared to what's good for Cake's agenda).

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by wmbst** [comment]
this TXid is fake and stolen from an other DFIP.

**Comment by sandrich** [comment]
what a muppet

**Comment by prasannavl** [comment]
Closing due to invalid tx id.

**Comment by prasannavl** [comment]
Reopening for an opportunity to fix tx to participate in regular voting cycle.
