### ISSUE TITLE
DEX Kommission für kleine Fische

### ISSUE THREAD

**Issue by Darkchicken1991** [DeFiCh/dfips#22]
Hallo DefiChain Community,
nachdem ich vor mehreren Wochen auf der DefiWallet meine Coins in das Liquidity Mining gesteckt habe, habe ich nun meine Kommissionen überprüft, da ich fast ausschließlich auf DFI Kommissionen erhalten habe.

Dabei habe ich festgestellt, dass man als kleiner Fisch deutlich weniger in der DEX profitiert als ein größerer Fisch oder Wal.

Hier einmal eine Beispiel Rechnung mit 500,- € ( ~ 83 DFI / 0,005 BTC ). Dies entspricht einen Poolanteil von 0,0002%

Jemand tauscht 0,001 BTC gegen DFI und zahlt darauf 0,002% Gebühren. Dann wäre mein Anteil:
0,001 BTC * 0,002% Gebühren * 0,0002% Pool Anteil = 0,0000000004 BTC
Dies ist weniger als 1 Satoshi und daher erhalte ich keine Kommission. Ich müsste um mindestens 1 Satoshi zu erhalten das 25fache im Pool haben, was ca. 12.500€ entspricht. Was für einen Menschen aus der Mittelschicht nicht wenig ist.

Mit dem Poolanteil würde ich also erst ab Transaktionen im Wert von 0,025 BTC erhalten. Ein weiteres Problem ist, wenn die Transaktion 99% höher ist, dann erhalte ich trotzdem nur 1 Satoshi, um dies zu vermeiden müssen auch deutlich höhere Summen investiert werden.

Da ich stark davon ausgehe, dass die Werte von BTC und DFI und auch den anderen Coins steigen so wie die Gesamtmenge im Pool, wird der Punkt ab dem man überhaupt eine Kommission erhält immer weiter nach oben gehen.

Auch wenn wir kleine Fische sind, ist unser Kopfanteil in der Community wahrscheinlich sehr groß. Mein Vorschlag wäre, wovon auch die Wale ein wenig profitieren würden:

Wenn sich die DEX Kommissionen auf einer Adresse sammeln und nur alle 100 oder 1000 Blöcke auf einmal anteilig ausgezahlt werden, verringert sich das benötigte Kapital deutlich, so wie die Abstufungen der Kommissionen.

Mir ist bewusst, dass ich das Problem mit Anbietern wie Cake umgehen kann. Dies sollte aber keine Lösung für ein dezentrales System sein.

**Comment by John-Gee** [comment]
That seems like a very valid concern!

Where does the surplus from not paying the small investors like OP actually go?

**Comment by Darkchicken1991** [comment]
> That seems like a very valid concern!
> 
> Where does the surplus from not paying the small investors like OP actually go?

To my understanding, these will be burned immediately

**Comment by uzyn** [comment]
Simple reason, blockchain can't pay out less than 1 satoshi worth of DFI. 

I'm leaving this open for a bit more, but this is not DFIP and should be closed. We can use Reddit for discussions like these.

**Comment by Darkchicken1991** [comment]
I was told that the commission is currently only 0.1% of the over 100% APY. So I don't see any need for action at the moment. I think in the course of time the bonus should decrease and the commission should get higher, then at some point it will be tight for the small fish.

@uzyn 
You are right. I will close it.

**Comment by tommuhm** [comment]
> Simple reason, blockchain can't pay out less than 1 satoshi worth of DFI.
> 
> I'm leaving this open for a bit more, but this is not DFIP and should be closed. We can use Reddit for discussions like these.

What happens to the satoshi which can not be paid out due to the 1 satoshi limit?, are the burned or do they just in the pool?
