### ISSUE TITLE
CFP-2211-09: Defichain Academy (20 000 DFI)

### ISSUE THREAD

**Issue by KevinMuttenthaler** [DeFiCh/dfips#232]
### Overview
1st Requester(s): Kevin Muttenthaler and Katharina Karner
2. amount requested in DFI: 20 000 DFI
3. receiving address: df1q4994udj5fc8c53uz5h8vx56p9nrekc67mlp3pr
4. reddit discussion thread: https://www.reddit.com/r/defiblockchain/comments/ynzvag/cfp_defichain_academy_20000_dfi/
5. proposal fee (200 DFI) txid: b3a6bcfbd5d6dd1094546cea29a3086454d7873d933bbceb2c401ddd6b713c59

### Describe the purpose

Dear DeFiChain Community!

We are Katharina and Kevin, both 27 years old and from Austria. Kevin is an enthusiastic DeFiChain investor from the very beginning and therefore he knows the whole project very well. Katharina has been invested in DFI since 2021, has studied marketing and is also working there professionally. Now we would like to finally also deliver added value to DeFiChain and actively engage in the project. However, in order to implement our following idea, we need the support of you, which we ask for with this CFP.

Since we have been involved with DFI for a long time and have experienced all the ups and downs, we know the DeFiChain world very well. What has particularly struck us during this time is the great complexity that this blockchain now has and which is also constantly increasing. With the increasing growth of DeFiChain, the amount of time you have to invest to stay up to date everywhere also increases. In our circle of friends, we also hear again and again that functions such as Vaults or the dToken are not used because they are too complex for many and they lack the time to familiarize themselves with these topics. And this is exactly where we want to start and deliver a high added value for the DeFiChain and its users with our CFP. 

We would like to build up a "DeFiChain Academy", in which the DeFiChain and all its functions are explained in a simple and understandable way. Simple and short tutorials should show the users, across all functions, the most essential things in a nutshell and offer instructions to follow. Clearly arranged and nicely sorted on a website. These are easily accessible and quick to find for everyone, so that you have a short and understandable explanation and instruction ready for every special topic. In addition the most essential questions regarding DeFiChain should be summarized and displayed in an easily and quickly accessible way. For those who are particularly interested, a continuous course will be offered, where you can dive from the basics to the deepest functions of DeFiChain and learn everything about it. The entire content will be primarily in German. If it turns out that there is demand, all explanations, videos, tutorials and courses will also be translated into English.

To ensure that this is used by many and to strengthen the community in the long run, it will be accessible to the user free of charge.

### How will the fund be spent?

The creation of an appealing and clear website as well as the creation of well explained tutorials and courses and the administration of these means a lot of time and money. 

We are asking the community that these essential costs for the "DeFiChain Academy" be funded from the Community Fund.

We are asking for 20,000 DFI to run 1 masternode. This masternode will then be immediately frozen for 10 years. From the running rewards (currently about 500€ per month) all costs, which arise during the creation of the website and for necessary programs and equipment, will be covered. In addition, a small part of the rewards serves as an expense allowance for us. If there is something left over from the rewards, for example because the running costs are lower or DFI has increased in price, it will be used for advertising for the Defichain Academy and Defichain in general. Because it is important that new investors quickly become aware of the "DeFiChain-Academy" to quickly understand the DeFiChain and learn the functions. This will avoid unnecessary mistakes and financial losses, which will then also make the users more positive towards the whole project. 

### How does this CFP benefit the DeFiChain community?

With this proposal we would like to offer a platform to new investors but also to people who have been invested for a longer time, where they can find short tutorials for a quick understanding. But also general answers to questions and courses to be able to understand the whole DeFiChain in detail.

It is important for the whole DeFiChain community that especially the new investors are given a simple and understandable access to the functions and that they are not driven away again by the complexity of the Chain. But also for everyone who wants to understand the DeFiChain to the last detail, the "DeFiChain-Academy" will be a valuable site, where all information and courses are clearly and quickly accessible.

No matter if someone is only interested superficially, only in a special topic or wants to explore the depths of the impressive DeFiChain, the "DeFiChain-Academy" offers the perfect access to these possibilities and is completely free for the users.

Are you ready to support us in this? Then please vote with "yes" for this CFP.

Thank you and maybe we will see you next time in the Academy 😉

Katharina and Kevin

**Comment by AleksDoesCode** [comment]
Commenting here cause the linked reddit post is only a headline, I assume there is something going wrong / your post being flagged by a bot.

1. Do you or your partner have any prior experience in creating educational?
2. What kind of equipment are you guys planning on buying?
3. When do you think you can deliver the first tutorial?
4. Are you developing the website by yourself? If so, does any one of you have a technical / IT background?
5. In which languages will the content be available?
6. 20k is a hefty price tag, especially since you are unknown / dont have prior projects to validate yourself (If you do have prior projects, please tell me ;D ). Why dont you ask for 6 or 12 months á 500€ in advance? That would lower the risk that you abandon the project once you get the 20k (not accusing you of planning something like these, there simply have been some black sheep in CFP rounds already)
7. Do you have a outline about what topics / how many tutorial or sessions are planned?
8. Can you provide a roadmap, so that we know which topics can be expected in which timeframe?

Looking forward to receiving your answers!

**Comment by KevinMuttenthaler** [comment]
First of all, thank you for these good questions and the opportunity to elaborate on our idea and discuss it with you. The following is our input to the questions posed:

1. In my time as a student I (Kevin) have given several tutoring sessions for different age groups and could already gain experience in transmitting knowledge in a simple and understandable way. However, I must admit that I have never offered video lessons. However, we are looking forward to such a new challenge.

2. Equipment costs include, for example, a good camera, microphone and lighting to achieve good video quality. And editing software (however we will use here at the beginning a Freeware product) and costs for creation and running of a website. 

3. The question about an exact time of the first video is not easy to answer. We want to provide content that is tailored to the target group and offers them the best possible support. For this reason, it is first important for us to engage intensively with the target group and to find out what challenges people face in contact with the Defichain. Only then we can create a concrete roadmap. Our rough goal is to go online in February with a first pre-test of the website and at least 3 videos. At the moment our goal is to create one video per week (depending on the complexity of the topic or depending on the current news on Defichain). For more information on a roadmap, see question 8.

4. First and foremost, we would like to create the website ourselves using Webgo and Wordpress.  Good results can be achieved here in an efficient way. Since we are aware of how important a good website is, we will of course resort to professional help if necessary.

5. The content will be created in German at the beginning, but we want to offer all content in English later if the demand is there.

6. Of course we can understand these concerns, because we have never appeared publicly in the community. But we want to change this now. The 20,000 DFI was chosen to be dynamic. We think it is smart to have the dollar value of the rewards increase right along with the interest in Defichain. Currently we are in a bear market and want to use this time to build and shape the Defichain Academy. As soon as there is more hype and the price of DFI rises again, we will have more financial means for targeted marketing at the right time to make people aware of the Defichain Academy and Defichain in general. This allows us to be flexible and create more awareness for Defichain at times when it is most important. Because the most important thing is that new people become aware of the Defichain-Academy quickly, so that they have an easy access to Defichain and are not immediately driven away by the complexity again.

7. Planned are as many tutorials and courses as it takes to cover all functions of the Defichain. This is of course very extensive and will be an ongoing process in which the users will be consulted again and again. First, we will start with the basics and continuously more complex topics will be covered. As soon as new functions are added to the chain, content will be created about them. Therefore the Defichain-Academy will develop as long as Defichain exists and will produce content continuously.

8. To name concrete dates is unfortunately difficult, because we also want to get input from newcomers before the first video, what challenges they had to overcome exactly and what content they would like to have so that the entry is as easy as possible for them. The process will therefore be as follows: first all relevant URL's will be protected, then there will be an analysis phase as well as a survey of users to tailor the content exactly to the target group and to finalize the project. Then the website and the first videos will be created and put online. We want to continuously integrate community feedback into the videos to generate the highest added value. In general, a recurring target group survey is planned in order to uncover ongoing challenges and to be able to support them with suitable content. As already mentioned in question 3, our goal is to go online in February with a pre-test of the website and the first videos.

We would like to add that this is our basic idea, but we are always open for improvements and adjustments. After all, we don't want to simply implement this concept, but to create a project that offers the greatest added value for the entire Defichain community. In this sense we are looking forward to further questions and constructive criticism.

**Comment by KevinMuttenthaler** [comment]
> Commenting here cause the linked reddit post is only a headline, I assume there is something going wrong / your post being flagged by a bot.
> 
> 1. Do you or your partner have any prior experience in creating educational?
> 2. What kind of equipment are you guys planning on buying?
> 3. When do you think you can deliver the first tutorial?
> 4. Are you developing the website by yourself? If so, does any one of you have a technical / IT background?
> 5. In which languages will the content be available?
> 6. 20k is a hefty price tag, especially since you are unknown / dont have prior projects to validate yourself (If you do have prior projects, please tell me ;D ). Why dont you ask for 6 or 12 months á 500€ in advance? That would lower the risk that you abandon the project once you get the 20k (not accusing you of planning something like these, there simply have been some black sheep in CFP rounds already)
> 7. Do you have a outline about what topics / how many tutorial or sessions are planned?
> 8. Can you provide a roadmap, so that we know which topics can be expected in which timeframe?
> 
> Looking forward to receiving your answers!

First of all, thank you for these good questions and the opportunity to elaborate on our idea and discuss it with you. The following is our input to the questions posed:

1. In my time as a student I (Kevin) have given several tutoring sessions for different age groups and could already gain experience in transmitting knowledge in a simple and understandable way. However, I must admit that I have never offered video lessons. However, we are looking forward to such a new challenge.

2. Equipment costs include, for example, a good camera, microphone and lighting to achieve good video quality. And editing software (however we will use here at the beginning a Freeware product) and costs for creation and running of a website. 

3. The question about an exact time of the first video is not easy to answer. We want to provide content that is tailored to the target group and offers them the best possible support. For this reason, it is first important for us to engage intensively with the target group and to find out what challenges people face in contact with the Defichain. Only then we can create a concrete roadmap. Our rough goal is to go online in February with a first pre-test of the website and at least 3 videos. At the moment our goal is to create one video per week (depending on the complexity of the topic or depending on the current news on Defichain). For more information on a roadmap, see question 8.

4. First and foremost, we would like to create the website ourselves using Webgo and Wordpress.  Good results can be achieved here in an efficient way. Since we are aware of how important a good website is, we will of course resort to professional help if necessary.

5. The content will be created in German at the beginning, but we want to offer all content in English later if the demand is there.

6. Of course we can understand these concerns, because we have never appeared publicly in the community. But we want to change this now. The 20,000 DFI was chosen to be dynamic. We think it is smart to have the dollar value of the rewards increase right along with the interest in Defichain. Currently we are in a bear market and want to use this time to build and shape the Defichain Academy. As soon as there is more hype and the price of DFI rises again, we will have more financial means for targeted marketing at the right time to make people aware of the Defichain Academy and Defichain in general. This allows us to be flexible and create more awareness for Defichain at times when it is most important. Because the most important thing is that new people become aware of the Defichain-Academy quickly, so that they have an easy access to Defichain and are not immediately driven away by the complexity again.

7. Planned are as many tutorials and courses as it takes to cover all functions of the Defichain. This is of course very extensive and will be an ongoing process in which the users will be consulted again and again. First, we will start with the basics and continuously more complex topics will be covered. As soon as new functions are added to the chain, content will be created about them. Therefore the Defichain-Academy will develop as long as Defichain exists and will produce content continuously.

8. To name concrete dates is unfortunately difficult, because we also want to get input from newcomers before the first video, what challenges they had to overcome exactly and what content they would like to have so that the entry is as easy as possible for them. The process will therefore be as follows: first all relevant URL's will be protected, then there will be an analysis phase as well as a survey of users to tailor the content exactly to the target group and to finalize the project. Then the website and the first videos will be created and put online. We want to continuously integrate community feedback into the videos to generate the highest added value. In general, a recurring target group survey is planned in order to uncover ongoing challenges and to be able to support them with suitable content. As already mentioned in question 3, our goal is to go online in February with a pre-test of the website and the first videos.

We would like to add that this is our basic idea, but we are always open for improvements and adjustments. After all, we don't want to simply implement this concept, but to create a project that offers the greatest added value for the entire Defichain community. In this sense we are looking forward to further questions and constructive criticism.
