### ISSUE TITLE
Incentive to buy DFI by increasing negative interest on dUSD

### ISSUE THREAD

**Issue by kynkong91** [DeFiCh/dfips#245]
### DFIP Overview
1. Requester(s): [@mrgrauel]
2. Reddit discussion thread (optional): [[Provide a link to Reddit discussion thread](https://www.reddit.com/r/defiblockchain/comments/zqor00/incentive_to_buy_dfi_by_increasing_negative/)]

### Describe your proposal
To direct 50% of the dUSD that is held by the buy-and-burn-DUSD-bot as additional negative interest to incentivize buying pressure on DFI.

### How does this DFIP benefit the DeFiChain community?
This will increase the demand for DFI and DUSD which also hastens the pace at which DUSD is being burnt

### Context
![image](https://user-images.githubusercontent.com/55274293/214750329-07b50e74-a72b-4d40-882c-3bc322f27846.png)

![image](https://user-images.githubusercontent.com/55274293/214750363-7f968df2-2a54-4c83-899c-1800bad2aac6.png)

### Summary of Implementation Details
- No changes to the network consensus
- No changes to the current bot mechanism
- 50% of the burned DUSD by the buy-and-burn-DUSD-bot is reintroduced into negative interest rate calculation.

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by Righteouxxx** [comment]
Add
