### ISSUE TITLE
CFP: DeFiChainWiki (9000 DFI)

### ISSUE THREAD

**Issue by Graciaho** [DeFiCh/dfips#248]
### Overview
1. Requester(s): Joshua Kummer ([0ptim](https://twitter.com/0ptim_))
2. Amount requested in DFI: 9,000 DFI
3. Cycles: 1
4. Receiving address: df1qr48ve9ufwl7r94y267mw6merw0ylwpv2ktkjmn
5. Reddit discussion thread (optional): https://www.reddit.com/r/defiblockchain/comments/10l6451/cfp_defichainwiki_9000_dfi/

I created a new wiki from scratch, which should greatly improve upon the already existing wiki.

Instead of me outlining again why I created this new wiki and what features it offers, please take a look at the announcement Reddit Post I've written.

[🎉 Announcement Post](https://www.reddit.com/r/defiblockchain/comments/zbm3sy/new_wiki_defichainwiki/)

The first update has already been released. You can read all about it here.

[🚀 Update 1](https://www.reddit.com/r/defiblockchain/comments/100p138/defichainwiki_update_1/)

<img width="860" alt="Screenshot 2023-02-01 at 11 00 21 AM" src="https://user-images.githubusercontent.com/99634821/215934642-51fb060f-c152-43d4-b630-124452199c18.png">

<img width="814" alt="Screenshot 2023-02-01 at 11 01 56 AM" src="https://user-images.githubusercontent.com/99634821/215934860-9f5af174-2f25-4147-b14d-aa7eb8fe7d53.png">

<img width="816" alt="Screenshot 2023-02-01 at 11 02 10 AM" src="https://user-images.githubusercontent.com/99634821/215934924-80ba40a8-fd1e-4aaa-b430-2e8445bfdd3c.png">

## Describe the purpose
All the work outlined has already been done. This is a compensation for the hours of work I put in to making this project a reality.

Why not do the CFP before the work? I don't like people requesting a lot of money and then don't deliver. I wanted to first deliver a product and then ask for money. It just makes more sense this way for me.

An accepted proposal will also indicate to me that the direction this project has taken is approved by the Masternodes, and I will continue working hard on the wiki as described above on what might come in the future.

### Current efforts

- 🔥 I'm currently experimenting with AI (Things like ChatGPT/GPT-3) to create a chatbot which can answer every question you might have about DeFiChain. If I'm successful, I'm planning to add the bot to the wiki, where it can be accessed with a chat-window.

- Coordinating work which needs to be done for contributors.

- Improving wiki content structure and adding new pages.

- Adding more languages/translations.

- Improving welcoming/onboarding of new DeFiChain members with guided step-by-step learning path.

- Improving SEO, so DeFiChain content will pop up on Google Search results more often.

##  How will the fund be spent?
Up to this point in time (2023-01-22) I've worked 140 hours on this project. You can have a look at [this↗](https://1drv.ms/x/s!ApZPT0eTrMYwhoM408Owo5mdG2h1tw?e=MifanV) table where I've tracked everything I've done. Also, have a look at the GitHub project. There you can see all the [Commits↗](https://github.com/0ptim/DeFiChainWiki/commits/main) (code edits) I've made.

I'm very open to feedback on where this project should go in the future. Just reach out to me on Twitter or Telegram.

## How does this CFP benefit the DeFiChain community?
Our modern wiki should become your go-to source for all things DeFiChain. We strive to provide accurate, easy-to-understand information and serve as a user-friendly entry point for those new to the DeFiChain ecosystem.

**Comment by 0ptim** [comment]
Hey @Graciaho 👋🏼
Why was this submitted here?

**Comment by Graciaho** [comment]
Hi Optim! 

Thanks for checking in. With the implementation of Governance on DeFiChain, we now accept proposal discussion on Reddit to encourage participation within the DeFiChain community. Unfortunately, Reddit is unable to track changes should there be any updates made. As such, our team will assist in creating a GitHub issue for all Reddit submissions as a form of reference. 

As a proposer, no further action is required on your end. Thanks!

**Comment by John-Gee** [comment]
> Unfortunately, Reddit is unable to track changes should there be any updates made.

How do you mean? Reddit shows when a post has been  edited.

**Comment by Graciaho** [comment]
Hi John-Gee, 

Yes, Reddit will allow users know if the post has been edit but unfortunately, they are unable to see which part(s) of the post are edited, including the moderators in the sub. Hope this clarifies!

**Comment by John-Gee** [comment]
Yeah that makes sense. It's something we could build though, there are already plenty of tools to find deleted/before edition posts, it shouldn't be too hard.

**Comment by Graciaho** [comment]
Thanks John-Gee for the suggestion! This definitely makes sense. If you have heard of any recommended tools, or have been using, feel free to let us know too! Thank you!

**Comment by 0ptim** [comment]
@Graciaho I'd really prefer that I'm the creator of the GitHub issue, too. If you're okay with that, I will create an issue myself. What do you think?

**Comment by Graciaho** [comment]
Hi Optim, 

If there are no changes to the original post on Reddit (url link you provided when submitted on-chain), please feel free to do so. After which, I will remove this post. 

fyi: You do not have to re-submit on chain.

**Comment by 0ptim** [comment]
@Graciaho I created #251. Please take a look and let me know if all is correct. I think you can then safely close this issue.

**Comment by Graciaho** [comment]
Thanks Optim. Had a look and all is good. Will proceed to close this issue. Thank you!
