### ISSUE TITLE
CFP: Continue DFI rewards on BSC DFI-BNB pool on BSC/ACSI.finance (20000 DFI)

### ISSUE THREAD

**Issue by rossi256** [DeFiCh/dfips#256]
**### Overview**

1. Requester(s): Michael (rossi256) for/with ACryptoS Team (BSC Yield Optimiser, Stableswap, Balancerv2 AMM on BSC)
2. Amount requested in DFI: 20000
3. Cycles: 1
4. Receiving address: df1q0v6depmsdxk27ly7fp0nf7xjgxj73sm0pzx4z2
5. Reddit thread: (first+second proposal which was voted YES, I was asked multiple times by the community to keep this going!)
https://www.reddit.com/r/defiblockchain/comments/se3eiz/cfp_liquidity_pool_partnership_for_bsc_20000_dfi/

**### Describe the purpose**

Continue with DFI rewards for the Pool on ACSI.finance to provide good swap slippage + rewards on BSC. 
Back when the pool(s) were on, on 1INCH, 40-50% of Swaps routed through the very efficient DFI-BNB pool on ACSI.finance. 
check here yourself for various swap sizes (NOTE the pool on ACSI.finance is without DFI rewards at the moment and has much lower liquidity but is still used in swaps): https://app.1inch.io/#/56/classic/swap/BNB/DFI

**Stats of previous CFP:**
https://github.com/DeFiCh/dfips/issues/106
- distributed 20k DFI in rewards over 90 days to Liquidity Providers on DFI-BNB pool (+ added ACSI rewards cause this is a DUAL reward farm) + DFI distributed on ONSEN Farm as additional pool to ACS-ACSI-BNB-BUSD pool.
- Twitter announcements + promo DONE
- Twitter video contest DONE
- Coingecko AD DONE
- 1M+ total swap volume
- 40-50% of swap volume went through ACSI.finance pool when checking 1Inch.

**How will the fund be spent?**
- Rewards for DFI Liquidity Providers in DFI-BNB Pool on ACSI.finance
- 2x Twitter campaign for the LP
- video contest, coin gecko ad or similar (adjusted with what gives the best output depending on market conditions)
- 1x AMA on Acryptos or Defichain TG communities

**How does this CFP benefit the DeFiChain community?**
- continuing to have a highly efficient additional dex with liquidity on BSC.
- 1inch and openocean linked
- another, alternative rewards source for DFI Liquidity providers.
- trustworthy partner on BSC helping to spread the word in the BSC community.
- Acryptos will provide ongoing ACSI token rewards (still running since first proposal!)

**Comment by rossi256** [comment]
@Graciaho could you remove that "draft" label - seems I can't

**Comment by Graciaho** [comment]
Updated! Thanks for the heads up!
