### ISSUE TITLE
250 DFI - Appreciation for successfully submitted, agreed to, and implemented DFIP

### ISSUE THREAD

**Issue by Graciaho** [DeFiCh/dfips#257]
### DFIP Overview
1. Requester(s): [u/DEFICHAIN_EPIC](https://www.reddit.com/user/DEFICHAIN_EPIC/)
2. Reddit discussion thread (optional)(https://www.reddit.com/r/defiblockchain/comments/117crmd/250_dfi_appreciation_for_successfully_submitted/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

<img width="810" alt="Screenshot 2023-02-23 at 1 37 53 PM" src="https://user-images.githubusercontent.com/99634821/220829115-bc4a9996-bb53-48f2-a6c3-d41bf7cb8c9c.png">
<img width="772" alt="Screenshot 2023-02-23 at 1 38 38 PM" src="https://user-images.githubusercontent.com/99634821/220829122-7e59aa0a-26fb-4e0b-9a34-b945865b913f.png">

### Describe your proposal
I've been thinking a lot lately about why we don't reward people who contribute to improving DeFiChain more. Currently, everyone who submits a DFIP has to pay 50 DFI submission fee. I think that is perfectly reasonable at the current price of $0.60 per DFI.

Still, I don't think it's fair that someone who had a good idea, posts it on Reddit, gets feedback, explains his idea to the community in videos and tweets, faces sometimes harsh and unconstructive criticism from other people (unfortunately often those who never contributed even the slightest added value to DeFiChain), and pays 50 DFI for the proposal, end up going empty handed.

The psychological effect of this is as follows:

"So...now I've submitted an idea that adds massive value to DeFiChain, taken all the steps necessary to make it happen, incorporated feedback and spent a lot of time...and as a thank you I get to pay 50 DFI for it."

I personally don't feel that is fair.

Let's make an example to show the necessity of my DFIP:

Let's assume a scenario where DFI is at $5. A smart person comes up with a brilliant idea to improve DeFiChain. He already has a child, has just finished his master's degree, and by buying an apartment, his wife and he have taken out a $200,000 loan and also borrowed money from her parents.

He is considering submitting his proposal as a DFIP. This would cost him, in our example, (50DFI * $5) = $250. He believes in his idea but is not sure if he should submit it,. His wife also says that it is too expensive at the moment, as the loan, the debt to the parents and the new stroller for the child have priority. He has already talked to other community members about his idea and they have offered to file the DFIP for him. Out of pride, because he doesn't want to admit that his financial situation is difficult and also because he would like to have the credit for his idea, the idea ends up as a Word document on his hard drive and stays there without ever being published.

Now let's imagine an extreme example to further illustrate the problem:

DFI stands at $50 (RoadTo50).

If this happens, then someone who wants to put a DFIP and thus contribute to the improvement of DeFiChain will have to pay $2,500 without receiving anything in return. Who else can afford to do that? I certainly can't.

Therefore here is my suggestion:

Everyone who successfully submits a DFIP, gets an approval from the Masternodes in the voting, and whose DFIP is then implemented on the blockchain should receive 250 DFI from the Community Fund.

Now some people will be angry because of the amount. Some because they are fundamentally opposed to it, because they fear that a flood of DFIPs awaits us as a result.

The others because they consider 250 DFI to be much too low and demand a much higher sum for the fact that someone may (and this is not uncommon) have provided DeFiChain with an improvement that may be worth much more money now or in the future.

I myself still feel 250 DFI is shamefully low to reward people who improve DeFiChain. It would be a start though.

Let's take our example again:

DeFiChain stands at 5$. Our friend with the family and the credit from his apartment has a brilliant idea.

He is aware of the $250 cost, but tells his wife that he will get $1250 back should his proposal be approved. Since his wife believes in him, after some time she agrees that he should invest the $250 in his idea. His motivation to explain his idea to the community is particularly high because he can use the money well and because he is still convinced that it will add value to DeFichain.

### How does this DFIP benefit the DeFiChain community?
For the RoadTo50 scenario, it would still be a $2,500 submission fee, but also $12,500 if the proposal is approved.

In my opinion, we will not see a flood of DFIPs as a result of this proposal. The effort is too great and the Masternodes are far too critical to agree to a DFIP that doesn't make sense.

Therefore, I will be submitting my DFIP!

I want to make it clear that I personally do not benefit from this at all. It will probably be the only DFIP in my life that I ever submit. I lack the technical understanding of Phigo90, Tommy, Kügi, Andreas and other smart people. However, if these talented community members at least get a little appreciation for their work, then I would find that much fairer than before.

Bene aka DEFICHAIN EPIC

Edit:

I would like to add Ralf's idea: Anyone who submits a DFIP, gets approval from the masternodes, but ends up not being implimented, gets 50 DFI from the community fund. This ensures that the investment of 50 DFI goes back to the DFIP creator.

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by 12Gitcat** [comment]
LeWve
