### ISSUE TITLE
CFP: defichain-trader.com (5400 DFI)

### ISSUE THREAD

**Issue by ghost** [DeFiCh/dfips#258]
### Overview
1. Requester: DefichainTrader
2. Amount requested in DFI: 5400 DFI
3. Cycles: 1
4. Receiving address: dG6hmNZwSb1eV318LQ4rLGSEBhmfdEGvx5
5. Source code: https://gitlab.com/groups/defichain-trader.com/-/archived

### IMPORTANT
Please clone or fork the source code projects. They won't be available indefinitely.

This project concluded at August 31, 2023. Remaining funds were returned to the community fund.

### Describe the purpose
Maintenance of [defichain-trader.com](https://defichain-trader.com) consisting of:
- making sure the current functionality remains in working order
- fixing bugs
- supporting users

### How will the fund be spent?
Funds will be sold for dollars and used to:
- increase server capacity to reduce stress in certain areas
- pay hosting costs

### How does this CFP benefit the DeFiChain community?
Users will be able to use the service for another year and I will continue to improve [defichain-trader.com](https://defichain-trader.com).

People use [defichain-trader.com](https://defichain-trader.com) for:
![showcase](https://user-images.githubusercontent.com/126125563/221650309-428a137d-999b-4b65-ad0f-b3de186d2653.png)

**Comment by Graciaho** [comment]
Hi @defichaintrader , will proceed to remove the draft label for this proposal as this is already live on-chain.

**Comment by ghost** [comment]
> Hi @defichaintrader , will proceed to remove the draft label for this proposal as this is already live on-chain.

Thanks!
