### ISSUE TITLE
Announcement: CFP Payment Completed for BH 2701440

### ISSUE THREAD

**Issue by Graciaho** [DeFiCh/dfips#259]
**CFP Payments for approved on-chain proposals that ended on BH 2701440 (24th Feb 2023) has been completed**. 
Txid for proposals as follows: 

- https://defiscan.live/governance/e65e6e47e5033fbb18cbc21f27abfd440088db479304431e35db7e3a9cb8e777
  - **[df1qr48ve9ufwl7r94y267mw6merw0ylwpv2ktkjmn](https://defiscan.live/address/df1qr48ve9ufwl7r94y267mw6merw0ylwpv2ktkjmn) 9000.00** // (0 * 10000) + 9000.00
    - [be3a8c5da97221028ae3278260bf6c690f17f163a71e7adfe2a011f772d3b8d1](https://defiscan.live/tx/be3a8c5da97221028ae3278260bf6c690f17f163a71e7adfe2a011f772d3b8d1)
- https://defiscan.live/governance/6a9f7313a40e234320b25c7b69523750225b5e95bd80c04640506730d0c39584
  - **[df1qz0pr424az5hn23ucarmehngh3mqqa9qs9t5ph5](https://defiscan.live/address/df1qz0pr424az5hn23ucarmehngh3mqqa9qs9t5ph5) 9000.00** // (0 * 10000) + 9000.00
    - [e9b727967f3e71262ea9b60246a303b130c748391de1ebbf15d4dd914a779791](https://defiscan.live/tx/e9b727967f3e71262ea9b60246a303b130c748391de1ebbf15d4dd914a779791)
- https://defiscan.live/governance/120fe8d2f3c2e5794449eab952c3acd449b216fef61e67f1a26446817604cbdc
  - **[df1qs8ragd0w59uqjmupqne9shf004ws4j5trgx2cd](https://defiscan.live/address/df1qs8ragd0w59uqjmupqne9shf004ws4j5trgx2cd) 200000.00** // (20 * 10000) + 0
    - [e8693ebbfb6fd529b7229ac35e3539bf9f2fe82c05bd58bf763a303d376dd431](https://defiscan.live/tx/e8693ebbfb6fd529b7229ac35e3539bf9f2fe82c05bd58bf763a303d376dd431)
    - [755a841d7b695f044ef21bab72fad89c3e296f5c432f1e3de1a1618b48500f1a](https://defiscan.live/tx/755a841d7b695f044ef21bab72fad89c3e296f5c432f1e3de1a1618b48500f1a)
    - [a5eba96e985138fb6ee947ce4493054abbb85b49b0146de8681aff543067c7a3](https://defiscan.live/tx/a5eba96e985138fb6ee947ce4493054abbb85b49b0146de8681aff543067c7a3)
    - [21d04792dff6ecdb56978f66bb701344ee16d2bb297e3868e1fb697b9424970f](https://defiscan.live/tx/21d04792dff6ecdb56978f66bb701344ee16d2bb297e3868e1fb697b9424970f)
    - [bc48af4c1a64db0ba73f4ee98702459b21006bdd04ebf7f468d46f8bcb1939de](https://defiscan.live/tx/bc48af4c1a64db0ba73f4ee98702459b21006bdd04ebf7f468d46f8bcb1939de)
    - [c37b2a1b0d556902f48569a907eb351a1719480529d72644a5e133a8e133947c](https://defiscan.live/tx/c37b2a1b0d556902f48569a907eb351a1719480529d72644a5e133a8e133947c)
    - [e4fe018df8c09a299e8be0fcec23e6e035919b584d76787dfd218db366dc9e1c](https://defiscan.live/tx/e4fe018df8c09a299e8be0fcec23e6e035919b584d76787dfd218db366dc9e1c)
    - [1cfb42a1dd9ec8472f54ec78261fa0f221cdb5b053b1633f045e8522c92c53fb](https://defiscan.live/tx/1cfb42a1dd9ec8472f54ec78261fa0f221cdb5b053b1633f045e8522c92c53fb)
    - [c51806a95fd12dfb160ac76cd66fdfd5296f4f97c4732eb878b889d56a1376ca](https://defiscan.live/tx/c51806a95fd12dfb160ac76cd66fdfd5296f4f97c4732eb878b889d56a1376ca)
    - [301d8bf2eebaaac4a0fd5cf8059da6cbea2d6ac71411b56d8ea8ec04d15e5ca4](https://defiscan.live/tx/301d8bf2eebaaac4a0fd5cf8059da6cbea2d6ac71411b56d8ea8ec04d15e5ca4)
    - [fcfe851d5110c5253cdd989f33e1a5521f1558fee6d613aba993f1f87436c837](https://defiscan.live/tx/fcfe851d5110c5253cdd989f33e1a5521f1558fee6d613aba993f1f87436c837)
    - [36135c954eba21e6bf2d84dd12d2d40e49299c15b7c92f1eb43226461d028d0a](https://defiscan.live/tx/36135c954eba21e6bf2d84dd12d2d40e49299c15b7c92f1eb43226461d028d0a)
    - [505b0b31d844e8b7cd3c400d37bdbe70591dfefdd92b3284942801ca5e754bec](https://defiscan.live/tx/505b0b31d844e8b7cd3c400d37bdbe70591dfefdd92b3284942801ca5e754bec)
    - [36999981943d77bd74d1b942858d89d9e99cafd1c5f5a17b02135922a2dedbff](https://defiscan.live/tx/36999981943d77bd74d1b942858d89d9e99cafd1c5f5a17b02135922a2dedbff)
    - [401dd26971c03e226d6e4a451f94666a26f9a9913b179ec8fa660216c04a6570](https://defiscan.live/tx/401dd26971c03e226d6e4a451f94666a26f9a9913b179ec8fa660216c04a6570)
    - [644a50fb5adb0717100f7ed98c34c09a39caa7d2e4bd94fa5bed1838c74e2d71](https://defiscan.live/tx/644a50fb5adb0717100f7ed98c34c09a39caa7d2e4bd94fa5bed1838c74e2d71)
    - [5d229c06a72a98c07a54d3f28ecfef6ae9668da232463d126f7db614b69e22f3](https://defiscan.live/tx/5d229c06a72a98c07a54d3f28ecfef6ae9668da232463d126f7db614b69e22f3)
    - [819ff47ddd2205cee5a6a252c9cb6c5a693ebaf4282eb44a78c3bdb20b307346](https://defiscan.live/tx/819ff47ddd2205cee5a6a252c9cb6c5a693ebaf4282eb44a78c3bdb20b307346)
    - [ad121c6d5477f78371d11407d0a6277ea1750774b13982f67b35ab20e96d4bbb](https://defiscan.live/tx/ad121c6d5477f78371d11407d0a6277ea1750774b13982f67b35ab20e96d4bbb)
    - [fad0e404cfb86c8e590e9e259292813437b24aab07e4c1d2fd8db0c6716af6ae](https://defiscan.live/tx/fad0e404cfb86c8e590e9e259292813437b24aab07e4c1d2fd8db0c6716af6ae)
- https://defiscan.live/governance/e0a62d1e206e45a559bc37ecd8b71dadf7aa117c192ab94f9b426169f8f1bae8
  - **[df1qaw6xs2jhj5y6ssdvm4vl2gsd6hvnw65g9vkw2t](https://defiscan.live/address/df1qaw6xs2jhj5y6ssdvm4vl2gsd6hvnw65g9vkw2t) 500000.00** // (50 * 10000) + 0
    - [d12439cdd2492a40652484bfdd8b7cabcb9a1e5b220dec2a79610b07277c9c62](https://defiscan.live/tx/d12439cdd2492a40652484bfdd8b7cabcb9a1e5b220dec2a79610b07277c9c62)
    - [50da4b23e1a892de4a9ee85c51db0c123bc3d82e84a9e9541916a51654a5b643](https://defiscan.live/tx/50da4b23e1a892de4a9ee85c51db0c123bc3d82e84a9e9541916a51654a5b643)
    - [5272f74692c5817c18a417aad54cbcd03a15a5341e07d4b18b595d2b5cb7f098](https://defiscan.live/tx/5272f74692c5817c18a417aad54cbcd03a15a5341e07d4b18b595d2b5cb7f098)
    - [6dadcf05773434f8ac6949f4e8b07d8003e94910de9f95eae9bbd95dd0579672](https://defiscan.live/tx/6dadcf05773434f8ac6949f4e8b07d8003e94910de9f95eae9bbd95dd0579672)
    - [025c22b71985b873399d497d5a250e8248d4d27a03e0f0e50c26a115a32db753](https://defiscan.live/tx/025c22b71985b873399d497d5a250e8248d4d27a03e0f0e50c26a115a32db753)
    - [0ce17614c8bf18c8ec7d53481a540dbc0a31ba81f91bd948e2c431f7b9fa5423](https://defiscan.live/tx/0ce17614c8bf18c8ec7d53481a540dbc0a31ba81f91bd948e2c431f7b9fa5423)
    - [0a98182535b1e01b8208eea3acb21a918f57e4f6ff9afc0496df6b6e4b793604](https://defiscan.live/tx/0a98182535b1e01b8208eea3acb21a918f57e4f6ff9afc0496df6b6e4b793604)
    - [cde04a0adaacac7b4d14d76cb20934dcc6dc92612bc6a38b21d349bfaec9310a](https://defiscan.live/tx/cde04a0adaacac7b4d14d76cb20934dcc6dc92612bc6a38b21d349bfaec9310a)
    - [29bbc7ef1e1d9bbb9676389b19271d28d39e9e5e9930e8a17ffae50af308b143](https://defiscan.live/tx/29bbc7ef1e1d9bbb9676389b19271d28d39e9e5e9930e8a17ffae50af308b143)
    - [7d4b388049413d5e189bd6d71e9c20fabbcc62095a59855fc164fd0bc9a0c100](https://defiscan.live/tx/7d4b388049413d5e189bd6d71e9c20fabbcc62095a59855fc164fd0bc9a0c100)
    - [87b3a72151b0f436fd7f0d3dc4cad1b32b9e42fd6b1869bf8e6e2780b2b6be80](https://defiscan.live/tx/87b3a72151b0f436fd7f0d3dc4cad1b32b9e42fd6b1869bf8e6e2780b2b6be80)
    - [0b2a2081de48c0eaa3fb4bde7f03ff45bceda1de8ab13ac1312396f80f1a94d0](https://defiscan.live/tx/0b2a2081de48c0eaa3fb4bde7f03ff45bceda1de8ab13ac1312396f80f1a94d0)
    - [6da32e120082a110891824ada337a374663f2f4e00c9363a68d0f5c0bfb56889](https://defiscan.live/tx/6da32e120082a110891824ada337a374663f2f4e00c9363a68d0f5c0bfb56889)
    - [2ff1904655a2c1a10500ad2e849c67444865f32156b60675cde174c99ba5fb69](https://defiscan.live/tx/2ff1904655a2c1a10500ad2e849c67444865f32156b60675cde174c99ba5fb69)
    - [cac9e01c1bedcd39e546a61b41f9f64bd2657d38f1d94f9d5d5261610a946484](https://defiscan.live/tx/cac9e01c1bedcd39e546a61b41f9f64bd2657d38f1d94f9d5d5261610a946484)
    - [5bc560e162a94212727921a8cbeb3aed8c28d4c2776b0ae3aeb8b2263a82d0a6](https://defiscan.live/tx/5bc560e162a94212727921a8cbeb3aed8c28d4c2776b0ae3aeb8b2263a82d0a6)
    - [c5e7901aeccdf2434ef764ae0120d4d7915f1c59dc7e12d47b6382a4d6fac550](https://defiscan.live/tx/c5e7901aeccdf2434ef764ae0120d4d7915f1c59dc7e12d47b6382a4d6fac550)
    - [e5d6d1992bde6133de6df378033cf602e1c69a68d72d686144ed11a99b794d4d](https://defiscan.live/tx/e5d6d1992bde6133de6df378033cf602e1c69a68d72d686144ed11a99b794d4d)
    - [b9c42a28b01244786f008cbc671c4ca27f2be87e84899814fe50b366f45f22c9](https://defiscan.live/tx/b9c42a28b01244786f008cbc671c4ca27f2be87e84899814fe50b366f45f22c9)
    - [0865d603e5ec01086af549eb3e1121312bc0e75d183cd788b64eb833c5998f05](https://defiscan.live/tx/0865d603e5ec01086af549eb3e1121312bc0e75d183cd788b64eb833c5998f05)
    - [e796ac0583b16573245bdc3d2eb815b39222cf9e78073db658a0a73e8e7a2bd9](https://defiscan.live/tx/e796ac0583b16573245bdc3d2eb815b39222cf9e78073db658a0a73e8e7a2bd9)
    - [55d99060ef8388b85fc6689bc6ef954591ffbeb4418d6cc0dd227cc700b287b9](https://defiscan.live/tx/55d99060ef8388b85fc6689bc6ef954591ffbeb4418d6cc0dd227cc700b287b9)
    - [2cdf07560e74e27f653f9452ea1972ac458d858573dae909384b5b72b233f243](https://defiscan.live/tx/2cdf07560e74e27f653f9452ea1972ac458d858573dae909384b5b72b233f243)
    - [e8d64b566c9cdd0fb7945c8970f7755311950c39485f9764096c697b610e1ffb](https://defiscan.live/tx/e8d64b566c9cdd0fb7945c8970f7755311950c39485f9764096c697b610e1ffb)
    - [cbaae72034914f4150562893c1bcf09e9891cef431dffebae0fa6a14ea4c2b61](https://defiscan.live/tx/cbaae72034914f4150562893c1bcf09e9891cef431dffebae0fa6a14ea4c2b61)
    - [36162e9e323513258a25f7a767b69151aae8f148fcbda5489848c302e15c71d3](https://defiscan.live/tx/36162e9e323513258a25f7a767b69151aae8f148fcbda5489848c302e15c71d3)
    - [457348646e326cef5ed832c611ca020bd8d1733232b9805897fb5070e74f8428](https://defiscan.live/tx/457348646e326cef5ed832c611ca020bd8d1733232b9805897fb5070e74f8428)
    - [27493c287ca927dfcc5fa4209575aa720cd64540f9c3df03d26dadb8811c85ab](https://defiscan.live/tx/27493c287ca927dfcc5fa4209575aa720cd64540f9c3df03d26dadb8811c85ab)
    - [ff5a2c7070146246a129b52aace700065b6ca38c4257df91162eb1f7164ce42e](https://defiscan.live/tx/ff5a2c7070146246a129b52aace700065b6ca38c4257df91162eb1f7164ce42e)
    - [2d50358f805b5f37c889289f88810351f7a6b6ba1fd687cc38dd1e2b1ffb1836](https://defiscan.live/tx/2d50358f805b5f37c889289f88810351f7a6b6ba1fd687cc38dd1e2b1ffb1836)
    - [2b6b87963f06a61d913eed112cc5c9cbf72438042a0fc52393cd8e2ec3c19b3b](https://defiscan.live/tx/2b6b87963f06a61d913eed112cc5c9cbf72438042a0fc52393cd8e2ec3c19b3b)
    - [77f8ebe6e899cc3a832c5fee7151cdc5af2e2db8e1b05fca86e8afb049e140c8](https://defiscan.live/tx/77f8ebe6e899cc3a832c5fee7151cdc5af2e2db8e1b05fca86e8afb049e140c8)
    - [72bfacd54b186e97de950bb187a4aa1198273bdc8f46c45fac762ba9d0da784f](https://defiscan.live/tx/72bfacd54b186e97de950bb187a4aa1198273bdc8f46c45fac762ba9d0da784f)
    - [519bf1f51e6863bfca77af34640d94e0d063571273a77472d71588fadd4ac4bd](https://defiscan.live/tx/519bf1f51e6863bfca77af34640d94e0d063571273a77472d71588fadd4ac4bd)
    - [ee00d48a2130ba2b569f9e29ec35d561ccc7320c507bb9be050f91c46cc33e5f](https://defiscan.live/tx/ee00d48a2130ba2b569f9e29ec35d561ccc7320c507bb9be050f91c46cc33e5f)
    - [42b0eaf7b4b3e81f46a900371e12acd0bfc837b1bc42d98d34d4436342d042f7](https://defiscan.live/tx/42b0eaf7b4b3e81f46a900371e12acd0bfc837b1bc42d98d34d4436342d042f7)
    - [480f2858b24ae870bc61db4779fff21255601f1f00096e9b88cfd413222b2aad](https://defiscan.live/tx/480f2858b24ae870bc61db4779fff21255601f1f00096e9b88cfd413222b2aad)
    - [7726f9b4465240159d1350596768681c07e89f1b68d048e2f7bac7c6c63f082e](https://defiscan.live/tx/7726f9b4465240159d1350596768681c07e89f1b68d048e2f7bac7c6c63f082e)
    - [c361d3c0fcd5c5742aa2e34c2fad3b442aaea701bb895e83a8390fe5cdac703f](https://defiscan.live/tx/c361d3c0fcd5c5742aa2e34c2fad3b442aaea701bb895e83a8390fe5cdac703f)
    - [f693efbeb283662288848d6afd7813e2bc3605d86729434e0eff789fe68bfcfe](https://defiscan.live/tx/f693efbeb283662288848d6afd7813e2bc3605d86729434e0eff789fe68bfcfe)
    - [74370476aff81b4d417fead2c3be4665cfd706ec8c08bf4c43475d48d64c18aa](https://defiscan.live/tx/74370476aff81b4d417fead2c3be4665cfd706ec8c08bf4c43475d48d64c18aa)
    - [f7f7cc81c760bc881d1df2a66556142f06491a4f2cdc062278d3cd45cc493ce1](https://defiscan.live/tx/f7f7cc81c760bc881d1df2a66556142f06491a4f2cdc062278d3cd45cc493ce1)
    - [c188523d1178fb7d3dc6efec0a4d23a301fd883f243a115e3801e367178c3b1f](https://defiscan.live/tx/c188523d1178fb7d3dc6efec0a4d23a301fd883f243a115e3801e367178c3b1f)
    - [2eccda349bff323ff3506bbcc98ff9cdf9fd67945709f7e150b17af2cc506f64](https://defiscan.live/tx/2eccda349bff323ff3506bbcc98ff9cdf9fd67945709f7e150b17af2cc506f64)
    - [a06fbb020329451fd7ad8f30ee597926561e8744e813e2e56d8ed0c6330d427a](https://defiscan.live/tx/a06fbb020329451fd7ad8f30ee597926561e8744e813e2e56d8ed0c6330d427a)
    - [d835418d3ac0b8792deb2dace9b3ad9c7004db687aa7f92563f25bdfa1778525](https://defiscan.live/tx/d835418d3ac0b8792deb2dace9b3ad9c7004db687aa7f92563f25bdfa1778525)
    - [bf44fc45a57ffcf61257e2c0d3b2c81da1d5078947d488dfe0b66d78df6856f5](https://defiscan.live/tx/bf44fc45a57ffcf61257e2c0d3b2c81da1d5078947d488dfe0b66d78df6856f5)
    - [96cb9fe4065b6dbcec8937aa606e70299b0d7cb9638459b0e850e5f84fe858a1](https://defiscan.live/tx/96cb9fe4065b6dbcec8937aa606e70299b0d7cb9638459b0e850e5f84fe858a1)
    - [933684f3a722e97508268a2fec59f18f06d81a6c57160806bf8c06ce0984e1f8](https://defiscan.live/tx/933684f3a722e97508268a2fec59f18f06d81a6c57160806bf8c06ce0984e1f8)
    - [894f557daf60a88ecd590b7667ea16a7642a8d4da6c79a9f9d3b17288a17f38e](https://defiscan.live/tx/894f557daf60a88ecd590b7667ea16a7642a8d4da6c79a9f9d3b17288a17f38e)

**Comment by 0ptim** [comment]
Maybe I missed this. But how are payments being done? Manually?
