### ISSUE TITLE
DFIP: Flexible Reward based on amount of frozen coins in masternodes

### ISSUE THREAD

**Issue by ThanatosOsomiak** [DeFiCh/dfips#26]
# Overview

Shared decentralized masternodes need the ability to partially unstake locked DFI to guarantee the masternode keeps running and the network stays decentralized.

Also with shared masternodes the ability to decrease the amount locked without closing the masternode will give some flexibility to the masternode owner and takes away some risks for all participants in that masternode.

# Proposal

Requirement: This Proposal requires Collateral Staking ![DFIP #11](https://github.com/DeFiCh/dfips/issues/25)

Masternode reward is based on the total amount of DFI locked. The minimum amount of staked DFI remains at 20.000 DFI, as in DFIP #4 defined. To give some buffer to unstake DFI, the masternodes need some incentive to increase the total locked DFI. Therefore the reward will be in direct relation to the locked DFI with the maximum possible reward at 30.000 DFI. More or less DFI will cause a loss in reward.

## Funding

The masternode owner will create an initial funding target (e.g. 25,000 DFI), based on this the funding takes place. After the masternode is running the owner can promote a refund to increase the DFI locked, from the initial funding wallets or from new wallet (max. 2 at the same time). 

## Reward Function

![RewardFunction](https://github.com/ThanatosOsomiak/DFIP-11-12/blob/main/RewardFunktion.png?raw=true)

![RewardFunctionPlot](https://github.com/ThanatosOsomiak/DFIP-11-12/blob/main/DFIP12Reward.png?raw=true)

### Example

<table>
  <tr>
   <td>Locked DFI
   </td>
   <td>Share of Maximum Reward
   </td>
  </tr>
  <tr>
   <td>20.000
   </td>
   <td>~85%
   </td>
  </tr>
  <tr>
   <td>30.000
   </td>
   <td>100%
   </td>
  </tr>
  <tr>
   <td>40.000
   </td>
   <td>~92%
   </td>
  </tr>
  <tr>
   <td>100.000
   </td>
   <td>~23%
   </td>
  </tr>
</table>

This will force the Masternodes to increase the locked DFI to 30.000 to gain maximum rewards and create a buffer to unlock up to 10.000 DFI without decreasing the network’s decentralization. 

## APY Change

Also the APY should not be affected due to the fact that the amount of the masternodes will decrease about ⅓ to generate maximum reward, so the reward will increase ⅓ compared to the current situation.

## Remaining Rewards

The reward not rewarded to the masternodes should be burned to “donate to everyone”: “Lost coins only make everyone else's coins worth slightly more. Think of it as a donation to everyone” - Satoshi Nakamoto. This will also help keeping the staked DFI per masternode at the 30.000 level.

**Comment by uzyn** [comment]
This is interesting. Thanks for the DFIP. It makes sense. 30k seems like the counter-productive direction (more instead of less).

Development-wise though, I would suggest after the much effort this time around with the emission rate and downsizing of masternode, we dedicate more engineering effort on the use-case – future offering. 

Still would take this as a DFIP and I appreciate this proposal. Thanks for making it.

**Comment by DerFuchs** [comment]
@uzyn Yep, that 30k thing has also been discussed within the german masternode channel. They did not like it. But I think that the 30k is just an example. @ThanatosOsomiak has been very kind and delivered an easy to implement mathematical function to set every amount you like.

The two proposals as a package would be very nice. The will enable very much people to stake their coins by themselves. Staking right from the Desktop App would be a very nice feature and this idea is appropriate to enable a feature like that.

**Comment by Juergen321** [comment]
I believe that the current system is fully adequate.

**Comment by uzyn** [comment]
Closing this in the mean time to prepare for the next round of DFIP. Please re-open if it should be part of the next DFIP.
