### ISSUE TITLE
DFIP discussion Vault adjustments

### ISSUE THREAD

**Issue by Graciaho** [DeFiCh/dfips#275]
### DFIP Overview
1. Requester(s):[u/Glittering_Jicama_95](https://www.reddit.com/user/Glittering_Jicama_95/)
2. Reddit discussion thread (optional): 
3. https://www.reddit.com/r/defiblockchain/comments/13504t6/dfip_discussion_vault_adjustments/

### Describe your proposal
The high negative interest rates made it very attractive to take a DUSD loan to generate a basicaly risk free return. The intented reason to grant high returns was to attract DFI to be locked in vaults. The original usecase for the DUSD is to build a settlement coin on the defichain without the volatility of the native DFI-Token.Meanwhile the actionable value of DUSD is - for a main part - to generate high risk free returns on „loans“ by depositing a few DFI in a vault and taking a loan in DUSD, putting these DUSD in the vault as well to take an even higher loan and so on until the DFI-vault-ratio drops to 50.01 % and maximise the loan and putting the DUSD in the vault as a safety margin. This is not intended!To countersteer this developement we have to change the vault regulations for DUSD-loans:„DUSD is no longer allowed as collateral for DUSD-loans. In vaults with just dAssets as loan DUSD remains in place as collateral. Minimum 66.7 per cent of DFI is required as collateral for DUSD-loans.“

for technical reason the headline had to be reduced to "DUSD collateral not allowed for DUSD-loans"

After approval of the DFIP the new regulation should be implemented at a good pace to force the demand of other collateral (hopefully mainly DFI to increase the demand – and the price). Therefore every 2880 blocks the value of DUSD in vaults is reduced by 10 cent. There is no reason for a generous transitional arrangement, because loans can be paid back if someone has no additional collateral on hand.

The additional adjustment to a 2/3 DFI requirement should prevent just a reallocation from liquiditymining pairs into a vault, because that has not the intended effect as well.

edit after further diskusion:

Some people don't like the change in the DFI -requirement from 50% to 2/3 - Because the main point is the DUSD ban as collateral I deleted this part .

### How does this DFIP benefit the DeFiChain community?
Describe how do you think this DFIP could potentially benefit the DeFiChain community

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by prasannavl** [comment]
Closing stale issue, as things have moved on chain.
