### ISSUE TITLE
NI B: The negative interest rates should be canceled

### ISSUE THREAD

**Issue by Graciaho** [DeFiCh/dfips#278]
### DFIP Overview
1. Requester(s): [u/Glittering_Jicama_95](https://www.reddit.com/user/Glittering_Jicama_95/)
2. Reddit discussion thread (optional): https://www.reddit.com/r/defiblockchain/comments/12wj18i/dfip_negative_interest/?sort=new&onetap_auto=true

### Describe your proposal
As the Community knows there are a lot of different views on negative interest rates in vaults. Because the discussion on Twitter and several other platforms is already matured, I think it's time to get a vote on this topic to end the discussion as it was announced in one of the first DFIPs (reevaluation)

Just a short abstract:

Some community member think, the negative interest rates motivate people to increase the TVL and more loans are better for the ALGO-rate of DUSD. The ALGO-rate for these group is more important than to reduce the debt of the system (burning DUSD).

They have to vote in favour of DFIP A.

„The negative interest rates on DUSD-loans should stay as they are now!

Some community member think, the negative interest rates were uneconomical and have no long term impact on the system health. It's just a donation to DUSD loan-“owner“. They think it's weird to change an obligation into a risk free investment. The whole amount should be burned.

They have to vote in favour of DFIP B.

„The negative interest rates on DUSD-loans should be canceled and the DUSD should be burned as well.“

Some community member think, the negative interest rates were uneconomical and have no long term impact on the system health. It's just a donation to DUSD loan-“owner“. They think it's weird to change an obligation into a risk free investment. But on the other hand: they see that service provider can provide nearly risk free interest on several cryptos. For this reason a negative interest rate is somewhat beneficial, but to reduce the donation and provide benefit to the system they want to cap the negative interest at 15 per cent and if the parameter result in a higher percentage the exceeding amount should be burned as well. As long as these is not technical implemented the whole amount should be burned and not paid as negative interest.

They have to vote in favour of DFIP C.

„The negative interest rates on DUSD-loans should be limited to 15 per cent and any higher amount of DUSD should be burned. As long as a limitation is not possible, the whole amount should be burned“

If non of these DFIPs receive the necessary quorum, it's obvious that the majority didn't want to proceed with paying out or burning and so the amount reserved for negative interest rates goes into the community fund for future decisions.

If more than one DFIP will be approved, the most restrictive one should be realized, because if someone is against NI he might vote for B and C in case B will not get the needed quorum.

Edit after discussion:

I decided not to submit these 3 DFIPs - not only because it's not possible with a light or desktop wallet, but because of the extremly low partizipation in the discussion and the very low amount of upvotes.

But I think the NI is useless and the BBB helps more, so - with the help of a community member - I will provide two of them:

„NI B: The negative interest rates on DUSD-loans should be canceled and the DUSD should be burned as well.“

for technical reason the headline had to be reduced to "NI B: The negative interest rates should be canceled"

„NI C: The negative interest rates on DUSD-loans should be limited to 15 per cent and any higher amount of DUSD should be burned. As long as a limitation is not possible, the whole amount should be burned. In case the DFIP NI B gets approved as well, it takes precedence over this DFIP NI C“

for technical reason the headline had to be reduced to 2NI C: The negative interest rates on DUSD-loans should be limited to 15 per cent"

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by prasannavl** [comment]
Closing stale issue, as things have moved on chain.
