### ISSUE TITLE
Special DFIP: Stake dETH-backing ETH on Bake to buy & burn DFI

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#285]
### DFIP Overview
1. Requester(s): @julianhosp & @uzyn 
2. Reddit discussion thread (optional): https://www.reddit.com/r/defiblockchain/comments/15qidez/emergency_dfip_staking_90_of_collateral_to/ 

### Describe your proposal
[The Reddit thread](https://www.reddit.com/r/defiblockchain/comments/15qidez/emergency_dfip_staking_90_of_collateral_to/) covers a wider discussion, but this special DFIP is specifically only about ETH.

Proposal:
1. Use 90% of the idle ETH that are sitting at the [backing address](https://etherscan.io/address/0x94fa70d079d76279e1815ce403e9b985bccc82ac) to stake ETH at [Bake](https://bake.io). 
1. Periodically, at least once a month, use the ETH reward from staking to buy DFI from DeFiChain DEX and burn the resulting DFI. This should be conducted via a bot for automation. 

Trackability:
1. Bake to provide an independent and trackable on-chain address for ETH nodes.
1. Bake is to provide monthly statement on rewards and nodes for full transparency.
1. Bot is fully trackable.

Implication:
1. Bake will be charging the regular fees that Bake customers are paying to cover node and operation costs. 
2. This also implies acceptance of Bake's latest terms and conditions related to staking, including the inherent risks related to ETH staking.

### How does this DFIP benefit the DeFiChain community?
This will add support to DFI price by adding utility and buying pressure of DFI.

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by Oldman12345** [comment]
Waiting for the next ones...
