### ISSUE TITLE
Special DFIP: Add DOT-, SOL-, MATIC- DFI pairs to DEX + Stake 90% of their backings for DFI buy & burn

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#286]
### DFIP Overview
1. Requester(s): @julianhosp & @uzyn 
2. Reddit discussion thread (optional): https://www.reddit.com/r/defiblockchain/comments/15qidez/emergency_dfip_staking_90_of_collateral_to/ 

### Describe your proposal
[The Reddit thread](https://www.reddit.com/r/defiblockchain/comments/15qidez/emergency_dfip_staking_90_of_collateral_to/) covers a wider discussion, but this special DFIP is specifically only about DOT, SOL & MATIC.

Proposal:
1. Use 90% of the idle DOT, SOL & MATIC that are sitting at the respective backing addresses at to stake at [Bake](https://bake.io). 
1. Periodically, at least once a month, use the reward from staking to buy DFI from DeFiChain DEX and burn the resulting DFI. This should be conducted via a bot for automation. 
1. DeFiChain DEX to add: dDOT-DFI, dSOL-DFI, dMATIC-DFI pairs with the standard 0.2% swap commission for liquidity providers but no additional block rewards. 

Trackability:
1. Bake is to provide monthly statement on rewards and nodes for full transparency.
1. Bot is fully trackable.

Implication:
1. Bake will be charging the regular fees that Bake customers are paying to cover node and operation costs. 
3. This also implies acceptance of Bake's latest terms and conditions related to staking, including the inherent risks related to staking.

### How does this DFIP benefit the DeFiChain community?
This will add support to DFI price by adding utility and buying pressure of DFI.

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by prasannavl** [comment]
Closing stale issue, as things have moved on chain.
