### ISSUE TITLE
Connecting wallet by scanning QR code is not available.. please build this features..

### ISSUE THREAD

**Issue by atanu2531** [DeFiCh/dfips#292]
### DFIP Overview
1. Requester(s): [Names and optionally GitHub usernames of requesters. e.g. John Doe @johndoe]
2. Reddit discussion thread (optional): [Provide a link to Reddit discussion thread]

### Describe your proposal
A clear and concise description on your proposal.

### How does this DFIP benefit the DeFiChain community?
Describe how do you think this DFIP could potentially benefit the DeFiChain community

 
### Non-obligation
I understand that vote of confidence for DFIP carries no obligations by any developers to implement the proposals. DeFiChain is a community projects. Pull requests can be submitted by community and reserved to be evaluated for safety and general community acceptance.

**Comment by John-Gee** [comment]
This is not a DFIP. This should be a request for the app not the network.

**Comment by atanu2531** [comment]
why  ? developers and product managers can create user stories  or feature details  always from this

**Comment by John-Gee** [comment]
If you really think it's a DFIP then you're missing the payment for opening
it.

**Comment by Benkben** [comment]
Sometimes i can not connected to Dapp
