### ISSUE TITLE
CFP: Public Community Liquidation Bot & DFI Liquidity for SeahorseFi.xyz Lending & Borrowing Market.

### ISSUE THREAD

**Issue by 0xAschente** [DeFiCh/dfips#298]
### Overview
1. Requester(s): 0xAschente ([SeahorseFi team's Twitter ](https://twitter.com/SeahorseFi)) @0xAschente] 
2. Amount requested in DFI: 600,000 DFI
3. Cycle(s): 1
4. Receiving address: df1qtlrngvmcjee0hdeg3cqt45f6el7hkwhzj8khqc

### Describe the proposal
We ([SeahorseFi](https://www.seahorsefi.xyz/)), a leading lending/borrowing money market protocol on the MetaChain EVM layer with over 700k USD in Total Value Locked (TVL) would like to request 600,000 DFI from the Community Fund for the following reasons:

1. Operate a large-scale liquidation bot, fulfilling the role as a Public Good on the MetaChain EVM ecosystem layer.
2. Support DFI liquidity on the market, currently demand for DFI is off the roofs and is providing above 140% in APY to DFI suppliers.
3. Create a pathway for the Community Fund to generate some form of returns.

### How will the fund be spent?

1. Infrastructure expenses associated with running the liquidation bot
2. Funds for liquidating future underwater positions, as well as for gas consumption.
3. Supplied as liquidity in SeahorseFi's primary DFI market and potentially, other markets.
4. Misc expenses such as marketing activities

### How does this CFP benefit the DeFiChain community?

50% of the liquidation incentives earnings from the liquidation bot will be converted back to DFI and be accumulated in a separate wallet address for traceability purposes. These earnings will go on perpetually until an accumulated amount of 600k DFI, which will then be awarded back to the Community Fund. 

The remaining 50% will be used to supply for liquidity in other markets that requires liquidity.

We are here to build as we see massive potential in not just the dTokens system, but also the strength and supportiveness of the community.  We understand that not all CFP funds requested are required to be returned, but we would like to do so in the proposed sustainable manner. Thank you and we hope to see you in the bright future ahead.

**Comment by prasannavl** [comment]
Closing, as completed on chain: https://defiscan.live/governance/908e9a4e4dd507f005781038a97497d8a5988d0375fb3332eec12612fd49aa3b
