### ISSUE TITLE
Announcement: June Voting round 

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#31]
## Key notes
1. We will be having another round of manual DFIPs and CFPs in June.
2. Please submit your DFIPs and CFPs by 31st of May to https://github.com/DeFiCh/dfips/issues. Use the CFP or DFIP template when you create the proposal.
3. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal or 50 DFI for Vote of Confidence. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
4. Once the fees are paid, update the issue with the txid.
5. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. All proposals are to be submitted by 1st June 2021 and have its collateral paid by the first block on 2021-06-02 00:00:00 UTC.
2. Voting will start on the 8th of June 2021 with masternode snapshot taken on the first block on 2021-06-08 00:00:00 UTC.
3. Voting will conclude on the 15th of June 2021 with the last valid vote in by the first block on 2021-06-16 00:00:00 UTC.

**Comment by uzyn** [comment]
I've submitted one as well for the community. You can refer to it: https://github.com/DeFiCh/dfips/issues/30

**Comment by supervolot** [comment]
Will it then be possible to vote via the wallet?

**Comment by uzyn** [comment]
> Will it then be possible to vote via the wallet?

Yes it will be possible

**Comment by Stonygan** [comment]
For the german speaking people, i make a little video "HowtoVote".
https://mydeficha.in/video/defichain_voting.mp4

**Comment by dpfaffenbauer** [comment]
For all MN Owners, I made an app to make it easier to sign the messages: https://github.com/saiive/defimnsigner

**Comment by uzyn** [comment]
# Confirmed proposals

## Community Funding Proposals 

- CFP 2106-01: DeFiChain Promo (21,000 DFI) #28 
- CFP 2106-02: DeFiChain bug bounty fund pre-allocation (10,000 DFI) #30 
- CFP 2106-03: DeFiChain Notification Service (5,000 DFI) #32 
- CFP 2106-04: DeFiChain Rewardhelper (4,000 DFI) #33 
- CFP 2106-05: DeFiChain Masternode Monitor (7,500 DFI) #34 
- CFP 2106-06: DeFiChain News Team (12,000 DFI) #35 
- CFP 2106-07: mydefichain Masternode Service (50,000 DFI) #36 
- CFP 2106-08: The "DefiNode" for more decentralization (8,800 DFI) #37 
- CFP 2106-09: Liquidity Mining Calculator (987 DFI) #38 
- CFP 2106-10: DeFiChain Fiat Exchange (150,000 DFI) #40 

## DeFi Improvement Proposals (Vote of Confidence)

- DFIP 2106-01: Long-term (5y & 10y) lock-in of staking DFI in exchange for higher staking returns #39
- DFIP 2106-02: Interim ticker council establishment for asset tokenization #41

**Comment by uzyn** [comment]
>  Voting will start on the 8th of June 2021 with masternode snapshot taken on the first block on 2021-06-08 00:00:00 UTC

Snapshot block is taken at [block 902,900](https://explorer.defichain.io/#/DFI/mainnet/block/66cc204ba28b89919474459a9fae155cf0e231b4e824bb5ef8ed7ae2eb3f431b).

**Comment by uzyn** [comment]
#40 is for 15k DFI and not 150k DFI. Proposal was updated 1 week ago.

**Comment by uzyn** [comment]
Thanks for all the votes.

Detailed voting breakdown can be found on the respective threads posted by @surangap.

# Voting results

## Community Funding Proposals 

Requiring >50% majority votes.

- CFP 2106-01: DeFiChain Promo (21,000 DFI) #28 **APPROVED**
- CFP 2106-02: DeFiChain bug bounty fund pre-allocation (10,000 DFI) #30  **APPROVED**
- CFP 2106-03: DeFiChain Notification Service (5,000 DFI) #32  **REJECTED**
- CFP 2106-04: DeFiChain Rewardhelper (4,000 DFI) #33 **APPROVED**
- CFP 2106-05: DeFiChain Masternode Monitor (7,500 DFI) #34 **APPROVED**
- CFP 2106-06: DeFiChain News Team (12,000 DFI) #35 **APPROVED**
- CFP 2106-07: mydefichain Masternode Service (50,000 DFI) #36 **APPROVED**
- CFP 2106-08: The "DefiNode" for more decentralization (8,800 DFI) #37 **APPROVED**
- CFP 2106-09: Liquidity Mining Calculator (987 DFI) #38 **APPROVED**
- CFP 2106-10: DeFiChain Fiat Exchange (15,000 DFI) #40 **APPROVED**

## DeFi Improvement Proposals (Vote of Confidence)

Requiring >66.67% majority votes.

- DFIP 2106-01: Long-term (5y & 10y) lock-in of staking DFI in exchange for higher staking returns #39 **APPROVED**
- DFIP 2106-02: Interim ticker council establishment for asset tokenization #41 **APPROVED**
