### ISSUE TITLE
DFIP #3: Maintain liquidity mining rewards at 100 DFI per block with airdrop fund and rewards ratio adjustments.

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#5]
## Overview

Shortly after launching the Decentralized Exchange in November, the Liquidity Mining Rewards had been increased to 100 DFI / block in order to kick everything off and drive fast growth.

And with over $68 Million Total Value Locked (TVL) after a mere month, very much successfully so.

These incentive rewards are currently being funded through what was decided in DFIP 2, where the community approved to set aside 25% of staking rewards for the upcoming liquidity mining.

That fund will be able to run for approximately another 3 weeks, before rewards then would settle to the regular 45 DFI / block.

## Proposal

2 parts to this proposal:

1. That the incentive rewards of 100 DFI per block be sustained, with the additional fund coming from the [remaining airdrop fund](https://explorer.defichain.io/#/DFI/mainnet/address/dMysnhSbg8VbJJjdj273bNQi6i69z4WL6Z), AND

2. And with the recent increase of ETH’s market cap, that the ratio of rewards be changed from:

    - BTC-DFI: 85%
    - ETH-DFI: 10%
    - USDT-DFI: 5%

    To:

    - BTC-DFI: 80% _(reduction of 5%)_
    - ETH-DFI: 15% _(increment of 5%)_
    - USDT-DFI: 5%

Upon approval, this proposal will be implemented during one of the the upcoming hard forks.

## Stage

- [X] Voting
- [x] Results

## Voting

Masternode snapshot will be taken at block 556,100 of DeFiChain mainnet.

Voting will open until Monday, 11 January 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `dfip-3 yes`
- No, I do not agree. Sign: `dfip-3 no`
- Neutral. Sign: `dfip-3 neutral`.

## Results

DFIP 3 passes with 15 yeses to 1 no.

ETH-DFI DeFi incentives have been adjusted to 15% (+5% from 10%), and BTC-DFI to 80% (-5% from 85%). https://github.com/DeFiCh/dfips/issues/5#issuecomment-758670855

**Comment by HE1-SIM** [comment]
> ## Overview
> Shortly after launching the Decentralized Exchange in November, the Liquidity Mining Rewards had been increased to 100 DFI / block in order to kick everything off and drive fast growth.
> 
> And with over $68 Million Total Value Locked (TVL) after a mere month, very much successfully so.
> 
> These incentive rewards are currently being funded through what was decided in DFIP 2, where the community approved to set aside 25% of staking rewards for the upcoming liquidity mining.
> 
> That fund will be able to run for approximately another 3 weeks, before rewards then would settle to the regular 45 DFI / block.
> 
> ## Proposal
> 2 parts to this proposal:
> 
> 1. That the incentive rewards of 100 DFI per block be sustained, with the additional fund coming from the [remaining airdrop fund](https://explorer.defichain.io/#/DFI/mainnet/address/dMysnhSbg8VbJJjdj273bNQi6i69z4WL6Z), AND
> 2. And with the recent increase of ETH’s market cap, that the ratio of rewards be changed from:
>    
>    * BTC-DFI: 85%
>    * ETH-DFI: 10%
>    * USDT-DFI: 5%
>    
>    To:
>    
>    * BTC-DFI: 80% _(reduction of 5%)_
>    * ETH-DFI: 15% _(increment of 5%)_
>    * USDT-DFI: 5%
> 
> Upon approval, this proposal will be implemented during one of the the upcoming hard forks.
> 
> ## Stage
> * [x]  Voting
> * [ ]  Results
> 
> ## Voting
> Masternode snapshot will be taken at block 556,100 of DeFiChain mainnet.
> 
> Voting will open until Monday, 11 January 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.
> 
> Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.
> 
> ### Vote options
> * Yes, I agree. Sign: `dfip-3 yes`
> * No, I do not agree. Sign: `dfip-3 no`
> * Neutral. Sign: `dfip-3 neutral`.
> 
> ## Results
> TBD

**Comment by HE1-SIM** [comment]
Yes, I agree. Sign dfip-3 yes

**Comment by pixell72** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by krishna-83** [comment]
Yes, I agree. Sign dfip-3 yes

**Comment by SchmaDias** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by Petra-bit** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by Petra-bit** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by Petra-bit** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by marsmanXmachina** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by SidPayton** [comment]
Hi @uzyn, would it be possible to change upcoming proposals? I would like to suggest that instead of simply prolonging the 100DFI reward, we double the time but slowly decrease the reward. This would lead to the same amount of DFI spent as rewards but the transition will not be as abrupt and sudden for all the newcomers. My hope with this is, that we keep more new people with us for the long term. Thanks.

**Comment by maetu1** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by uzyn** [comment]
Masternode votes from Cake DeFi (https://cakedefi.com) for DFIP #3 

## Raw voting results 

To be posted shortly.

### 15 masternodes for **YES**

```
$ defi-cli signmessage 8V8epB69taZSr9kbnsgFQa3AiDgjqkLW92 "dfip-3 yes"
INEu4ATpBu1DxSI$bLjSPk7mtS1oRzSEVCd1qx/OrcPxDyotbqeJR$B/7s0dFD58LIAHEi5ZVTeAg9Qa6UtBZxY=
$ defi-cli signmessage 8YSxAdFc9476SYjP4oP9GTcffu3Mp2QBPB "dfip-3 yes"
IKzVDWQ7jg4EdNSsIrgpD70nT50aSp5sN3FMu31AvQcOeP/U5Mj81GreOHAlc9JiNfH6uKoElPcsKNsqVgo3iRI=
$ defi-cli signmessage 8MMCHMVi4Hgh2GMhrXn239ZsYsMng3pTgT "dfip-3 yes"
IJlRz999DEy4iI6ql4e9MF2JMNg8Hy0EoWPmP/mO5CG7Hu7HmeKZrn9spxF0XjqSjI3hl4du6S4r4a0LhOpf61Y=
$ defi-cli signmessage 8Qv3ogu3t7hm128F98qU8KsJuSDxU1UVpZ "dfip-3 yes"
H6BZgZS7lTyvQsEmLTViKo5JuW$m16EYH7HpHq3SllgLNsc0zkiKZR1wGLKu2yrDS2/bmNg7JP01j5qERMmC3Tg=
$ defi-cli signmessage 8X9chwcKCzpG2QUKozYo3dcaff885TmBxp "dfip-3 yes"
H6AoKigxRxxVKT8rXQPfSEVUOamyNhmtjEZ48CDEwp3af77Tt08JL5zRHR8u0HrkZUx83V4vW2UeKwHXVApuT4o=
$ defi-cli signmessage 8UdHjvi29eU6jEbVDSRsXugJu2k2e3zY2W "dfip-3 yes"
IGBSijgA2lkZgsRE6ctLuPMs5XI6KnHs2NKWhOejAk8FdcXe4WkqHwjIBo30RYhHqL9JY8z/tQWDdujwzGePGF8=
$ defi-cli signmessage 8e3YAhew2CEUqyr8BtH6baJwE991dMXVoU "dfip-3 yes"
IFvW$EJtNBEQDTMOYjoaa/mf3cd41tl4mEQMBQn0rUJmFSpOdbVU4jGjZvbDJ6mPpLBGMTH3vBqTEPWQz84rq$4=
$ defi-cli signmessage 8dEfagfYUXAd2DsUfvDLdhicRbBmEj9da5 "dfip-3 yes"
H/QISaIUEbm1$Ouh/bYRAzOU4ub9lkeEJvzVemftDYs7bRh9QAG/rErCtQZL6c$k6/lEvp6Ren5LhTdFec4icAE=
$ defi-cli signmessage 8XYsRxbQ89w48paRWXwLAjU3GStNB5cKad "dfip-3 yes"
H7itHvVHxuGy3AGDnGvRyY4q4X52po7dXlLCZZBBhvW/LHM0DRi$0gCPb3I/6mWa94h30jgIMBhmduKY9p2L3aE=
$ defi-cli signmessage 8JmTVRQzJzWwHeegDUzofKUvn4FpBxTk5h "dfip-3 yes"
H2OVGl9IUo5Rp3qcO4Rm6gxCPDa99wAgDWRUoXkqOyBMJxrohlOfDDf7MZJVd9hs36fEunH/lEDHE7E25OCbAC0=
$ defi-cli signmessage 8Lr2RpnL5RrZnXwzd9N5j4vJ3mNjUk35TV "dfip-3 yes"
H03xY29JHvNIW5FXEj8hTV9P5FDmu72zSd6XvD7vqdnZQhVHnZiK9hojMHqB7ZXSO26BrvzUAqSZH9IKDFqMZ3A=
$ defi-cli signmessage 8SygZNJey81ksvqoLGrE8Hk85Yg5bwp6N4 "dfip-3 yes"
H7NtB7lGgeht5hcpDdpviOqAI35j2hcdg6/aiaYiarbAMpm5MLmnFD/$dBKY1FDrXYh3UoFctYDBXNb0XWKJKA4=
$ defi-cli signmessage 8SNzL79x2vQBxbsji8x3Tsu515UfjtfUgk "dfip-3 yes"
HzeGB4yAMZm5q2v/xwnv$6D57qesKo773TP3qbfSmT1QfkS$p7lcQZ5Z9jaTApmq3vqxdYj1JMP$JUOXI39OEYY=
$ defi-cli signmessage 8bGJntENwPDCENjFKECJb5KtXbX1CHeXoP "dfip-3 yes"
H7Ivzdv3lmAVtH4S6UWRWzDjoXUpKn6UvkljT0Tva9hlXwkKPo/YWNFkwxSCrCPSbggEcVbfducE2BK/nFxFDAo=
$ defi-cli signmessage 8XpNN5Koco6sDmDgL618qntUdE2D65HC8s "dfip-3 yes"
IFyZnxfAgKe$U/ncXoiuz6rglehdkwCCtqJMAkuzyCcHENVQawF0HsxBwmMrT/WmUHoOiDiDG96L0gT7CRo17lU=
```

### 1 masternode for **NO**

```
$ defi-cli signmessage 8cLPN4diDtw8oG2ZxD58SQsprfyHyccnG4 "dfip-3 no"
HzhRPaULxtk/UCmo9C1mlz/4euJuWgQGSigx7AmOu57oDrM03ARe8toRHkASZ0HgIKyk0NOqy91aQ1jyUEYfcuc=
```

**Comment by andreattafabio** [comment]
**Raw voting results - Cake** 

Survey is carried out by Cake DeFi to their stakers.

Details: https://cakedefi.medium.com/cake-defichain-improvement-community-proposals-voting-results-4712a58efe4c

Raw voting results: https://docs.google.com/spreadsheets/d/1fHCmtdUchFhFO4clY-Wi_57NTBUkD5hula3vskRfgKk/edit#gid=438739612

**Comment by uzyn** [comment]
As per DFIP 3, ETH-DFI DeFi incentives have been adjusted to 15% (+5% from 10%), and BTC-DFI to 80% (-5% from 85%).

<img width="1352" alt="increase" src="https://user-images.githubusercontent.com/280505/104323316-fdc82980-5520-11eb-9529-260098c532b2.png">
