### ISSUE TITLE
Announcement: September 2021 voting round

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#53]
## Key notes
1. We will be having another round of manual DFIPs and CFPs in September 2021.
2. Please submit your DFIPs and CFPs by Monday, 13 September 2021 23:59:59 UTC to https://github.com/DeFiCh/dfips/issues. Use the CFP or DFIP template when you create the proposal.
3. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal, 50 DFI for Vote of Confidence or 500 DFI for reallocation of block rewards. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
4. Once the fees are paid, update the issue with the txid.
5. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. All proposals are to be submitted by Monday, 13 September 2021 23:59:59 UTC and have its fee paid by the first block mined after the time.
1. There will be one week of project presentations and Q&A.
1. Voting starts on Monday, 20 September 2021 23:59:59 UTC with masternode snapshot taken on the first block mined after the time.
1. Voting concludes on Monday, 27 September 2021 23:59:59 UTC. Final votes are to be posted on respective GitHub issue before the time.
1. Announcements of results should be in by Wednesday, 29 September 2021.

**Comment by uzyn** [comment]
# Confirmed proposals

- 18 CFPs 

## Community Funding Proposals 

1. #51 
2. #52 
3. #54 
4. #56 
5. #57 
6. #58 
7. #59 
8. #60 
9. #61 
10. #62 
11. #63 
12. #65 
13. #66 
14. #68 
15. #69 
16. #70 
17. #71 
18. #72

**Comment by uzyn** [comment]
Voting has ended. Vote tallying, verification and summary will be posted soon on the individual CFPs.

On the interim, please refer to these sites for results:
- https://www.defichain-masternode-monitor.com/#/votings
- https://mydeficha.in/cfp/

**Comment by uzyn** [comment]
Thank you @surangap & @Kolibri1990 for working through the differences and arriving at a consensus on the vote validation.

It has been fully tallied and finalized. The results can be viewed at either one of the following links:

1. The individual CFP GitHub issue threads.
2. https://www.defichain-masternode-monitor.com/#/votings
3. https://mydeficha.in/cfp/

With this we are seeing 13 approved CFPs and 5 declined CFPs. 

Payouts will be done this week.

**Comment by uzyn** [comment]
Payouts are being processed.

It is also to be made aware that 2 CFPs have been removed, due to the underlying GitHub account being deleted.

- CFP 2109-13: DFX Smartphone App (26 000 DFI) #66 **DECLINED**
- CFP 2109-16: DFX - Decentralized Finance Exchange (135 000 DFI) #70 **APPROVED**

Due to the removal of the approved CFP, payout is unable to be made for CFP 2109-16.

It is also to be noted that 2 key GitHub accounts behind these proposals, along with its corresponding open source repositories seem to have been deleted. 

- https://github.com/RobinTorque _(the proposer)_
- https://github.com/DeFiChange _(the organization with open source repos)_

**Comment by Mark76DefiChain** [comment]
Web-Archive Links to the deleted CFPs:
https://web.archive.org/web/20210922083102/https://github.com/DeFiCh/dfips/issues/66
https://web.archive.org/web/20210914203407/https://github.com/DeFiCh/dfips/issues/70
https://web.archive.org/web/20211001053659/https://webcache.googleusercontent.com/search?q=cache%3AjhYJUGTd5gcJ%3Ahttps%3A%2F%2Fgithub.com%2FDeFiCh%2Fdfips%2Fissues%2F40

**Comment by uzyn** [comment]
Thanks @Mark76DefiChain 

Also https://www.reddit.com/r/defiblockchain/comments/pnnf1p/cfp_dfx_decentralized_finance_exchange_135000_dfi/

Payout is being processed for CFP 2109-16
- Address: `dXz2YUUA4b1SVej5G6BrQf6Tz5QmsNiDT7`
- Amount: 135 000 DFI

**Comment by DFXAdmin** [comment]
@uzyn @Mark76DefiChain 

Thank you 🙏

**Comment by Mark76DefiChain** [comment]
your welcome

**Comment by John-Gee** [comment]
@uzyn maybe it's time to remove the announcement. ;)
