### ISSUE TITLE
DFIP #4: Reduction of masternode collateral to 20,000 DFI

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#6]
## Overview

Currently, the collateral to run a masternode is 1,000,000 DFI.

With the steady increase of price of DFI to now $2, it is getting very costly to set up a DFI masternode, both on the collateral and on the creation fee (100 DFI).

## Proposal

2 parts to this proposal:

1. Proposal collateral to be reduced to 20,000 DFI.

2. Matsernode creation fee to be reduced to 10 DFI.

Upon approval, this proposal will be implemented during one of the the upcoming hard forks.

## Stage

- [X] Voting
- [x] Results

## Voting

Masternode snapshot will be taken at block 556,100 of DeFiChain mainnet.

Voting will open until Monday, 11 January 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `dfip-4 yes`
- No, I do not agree. Sign: `dfip-4 no`
- Neutral. Sign: `dfip-4 neutral`.

## Results

DFIP 4 passes with 14 yeses to 1 no.

**Comment by ipungcaem** [comment]
RFC

**Comment by ipungcaem** [comment]
Yes, I agree. Sign: dfip-4 yes
No, I do not agree. Sign: dfip-4 no
Neutral. Sign: dfip-4 neutral.

**Comment by ipungcaem** [comment]
# OWNER_ADDRESS being your masternode's owner address with the collateral
$ defi-cli signmessage OWNER_ADDRESS "dfip-4

**Comment by ipungcaem** [comment]
8cmz6gLGJD7sTcjhkS6xG3CKkf68zKQHqF

**Comment by ipungcaem** [comment]
$ defi-cli signmessage 8cmz6gLGJD7sTcjhkS6xG3CKkf68zKQHqF "dfip-1 yes"
H7LnPPnRScYON/dbAAQ7qKYJw41D2QocPghFfWfNJAMnTVYL6lPMSPESPpXPTL7Gp4rJJAnKCmfEICIS+P4G3U8

**Comment by ipungcaem** [comment]
$ defi-cli signmessage 8cmz6gLGJD7sTcjhkS6xG3CKkf68zKQHqF "dfip-4 yes"
H7LnPPnRScYON/dbAAQ7qKYJw41D2QocPghFfWfNJAMnTVYL6lPMSPESPpXPTL7Gp4rJJAnKCmfEICIS+P4G3U8

**Comment by ipungcaem** [comment]
verifymessage RPC

**Comment by ipungcaem** [comment]
$ defi-cli verifymessage 8cmz6gLGJD7sTcjhkS6xG3CKkf68zKQHqF H7LnPPnRScYON/dbAAQ7qKYJw41D2QocPghFfWfNJAMnTVYL6lPMSPESPpXPTL7Gp4rJJAnKCmfEICIS+P4G3U8= "dfip-4 yes"
true

**Comment by pixell72** [comment]
Yes, I agree. Sign: dfip-4 yes

**Comment by krishna-83** [comment]
dfip-4 yes

**Comment by Petra-bit** [comment]
dfip-4 yes

**Comment by marsmanXmachina** [comment]
Yes, I agree. Sign: dfip-4 yes

**Comment by chilli01** [comment]
dfip-4 yes

**Comment by uzyn** [comment]
Masternode votes from Cake DeFi (https://cakedefi.com) for DFIP #4

## Raw voting results 

To be posted shortly.

### 14 masternodes for **YES**

```
$ defi-cli signmessage 8V8epB69taZSr9kbnsgFQa3AiDgjqkLW92 "dfip-4 yes"
IMOZP/Qks4XdvCcx8uTUHZsus1Jy2y/I9SuHFDOktqRAXPlnBan20lqhKiAw3hK1MJISn0wB0r9nBCpi1llbc1k=
$ defi-cli signmessage 8YSxAdFc9476SYjP4oP9GTcffu3Mp2QBPB "dfip-4 yes"
IDiTRQnATA8ayn7Hv2Nu35jpiLD39u243+h3C9mt/66/RxW3CTADTUEzRBPlzkWbSTsMSpIcXKpChhLAPDBIq3U=
$ defi-cli signmessage 8MMCHMVi4Hgh2GMhrXn239ZsYsMng3pTgT "dfip-4 yes"
IOQOuaNtIPoB/VBHSLb1fN+LMhc9UGQamvhduR1+Eg7hB42415q3FRKYbLSSbfD4FMNbjSrxEcgJihj5JPu9eBc=
$ defi-cli signmessage 8Qv3ogu3t7hm128F98qU8KsJuSDxU1UVpZ "dfip-4 yes"
IO0L0Q2d3GY3VwAgZDf6R0dPiLdOoVcEtqz47jhcvFisBFEtfTdruxB+d/OrAZwrcs0hb8hBKLuvaSYV3Srt4+0=
$ defi-cli signmessage 8X9chwcKCzpG2QUKozYo3dcaff885TmBxp "dfip-4 yes"
HwEjeu+zNTjKTAqySUrp/+Kb8FNUxxeXgQZwK4vS1nUtTtPMsp4B6kPtSHOPInKzImw8aeBo187thBMdF2FsUc8=
$ defi-cli signmessage 8UdHjvi29eU6jEbVDSRsXugJu2k2e3zY2W "dfip-4 yes"
ILG1NROPuVTY+X9QTUEuLfRhg10H8uVZvYsS9Vlpe8XjWNslGEv0666vMXhDyZg40YyeD5V5wW4hRdWnZ8CjnMs=
$ defi-cli signmessage 8e3YAhew2CEUqyr8BtH6baJwE991dMXVoU "dfip-4 yes"
IJ4mltmlu7iw4Ftp9Ciq7TQXSNFxpSSsptrvYrr/nlvLEplX0mCP+DQ5vRkUs2cujBkaTBhXo2BlSUAm0iemYdE=
$ defi-cli signmessage 8dEfagfYUXAd2DsUfvDLdhicRbBmEj9da5 "dfip-4 yes"
HxJHB9l7oXybnGeqLbupavcqcozp2nQv3XysnBQ22jm6WiXLQ0EhN6MO8tcd1rDfHdsInUrugyj1EE/0WLvY4f4=
$ defi-cli signmessage 8XYsRxbQ89w48paRWXwLAjU3GStNB5cKad "dfip-4 yes"
Hy+G5c6KfLj02CzK8kxow3aTPWyX4lDKyrDejKwYJ9kLAj2oswbJ8ElBwYKS3hn3VDI2TN/DVDAdDD0sTjQqPnQ=
$ defi-cli signmessage 8JmTVRQzJzWwHeegDUzofKUvn4FpBxTk5h "dfip-4 yes"
H3AkO+vh6D76I7sXESc3RmLp+JZdM2ov3nNs+bwksTZSEAcJN9K9ODTf81bhHVUzjQgGMeJGmXVwLNwzeVn6b+c=
$ defi-cli signmessage 8Lr2RpnL5RrZnXwzd9N5j4vJ3mNjUk35TV "dfip-4 yes"
H7wjGyD9DBADjEviwDYco/J/FIKYWQG6AUuigVgeyNl/N+6IeuNK6eZEnqfyALknUJB6o9p3+sO63FlYWVRdcYs=
$ defi-cli signmessage 8SygZNJey81ksvqoLGrE8Hk85Yg5bwp6N4 "dfip-4 yes"
H+CsxY4waKbhtlEnsQmi++o7lggHs2HI5FN+7Trsm9T+PkTxqrCWUnd4BtzCEjo16t+1GA5tJNjhgeujvBDlBic=
$ defi-cli signmessage 8SNzL79x2vQBxbsji8x3Tsu515UfjtfUgk "dfip-4 yes"
IASYGjAwH9SZNaYNRviqEL8APDUrFYsbx+m1VwF7gJMeLfkIffr8qXnCHyUV2jquJzwBeJB0/squVwm2zZ+1UMQ=
$ defi-cli signmessage 8bGJntENwPDCENjFKECJb5KtXbX1CHeXoP "dfip-4 yes"
IGMOHKeM483cFgdJnKOAahmcSQWrKNQBm9E9Y4jCwRXjCGQJ2HLtB9wWFe1vTae1Upy+h+WbGUqclVwtEYNqveo=
```

### 1 masternode for **NO**

```
$ defi-cli signmessage 8XpNN5Koco6sDmDgL618qntUdE2D65HC8s "dfip-4 no"
H1RcSGfWJ9hlahgYb7LxuY6FPXcmjvx8JioGY/m6EDkYeFl3RMQgH+nnSgw4yryAAhYQ03hT5iDgOklLERO/AoA=
```

**Comment by andreattafabio** [comment]
**Raw voting results - Cake** 

Survey is carried out by Cake DeFi to their stakers.

Details: https://cakedefi.medium.com/cake-defichain-improvement-community-proposals-voting-results-4712a58efe4c

Raw voting results: https://docs.google.com/spreadsheets/d/1fHCmtdUchFhFO4clY-Wi_57NTBUkD5hula3vskRfgKk/edit#gid=438739612

**Comment by ipungcaem** [comment]
0x9648380814AB1a967C0E70aCf3f85D6E65A4EBd2

Pada tanggal Sen, 15 Mar 2021 20.30, U-Zyn Chua ***@***.***>
menulis:

**Comment by wilfred1005** [comment]
Done
