### ISSUE TITLE
DFIP #5: Introduction & Funding of Litecoin LTC-DFI Liquidity Pool

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#7]
## Overview

Decentralized exchange (DEX) has been operating for a month now at DeFiChain and it has been stable. It is time to introduce the more liquidity pool pairs to the DEX.

## Proposal

1. Introduction of Litecoin LTC-DFI Liquidity Pool.
2. Based on market cap of LTC, it is proposed for a funding of **2 DFI per block** incentive as liquidity mining reward for this pool. Funding is sourced from [the remainder of airdrop fund](https://explorer.defichain.io/#/DFI/mainnet/address/dMysnhSbg8VbJJjdj273bNQi6i69z4WL6Z). 

Upon approval, this proposal will be implemented during one of the the upcoming hard forks, allowing LP to be funded via token deposits.

## Stage

- [X] Voting
- [x] Results

## Voting

Masternode snapshot will be taken at block 556,100 of DeFiChain mainnet.

Voting will open until Monday, 11 January 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `dfip-5 yes`
- No, I do not agree. Sign: `dfip-5 no`
- Neutral. Sign: `dfip-5 neutral`.

## Results

DFIP 5 passes with 14 yeses to 2 nos.

**Comment by krishna-83** [comment]
dfip-5 neutral

**Comment by Petra-bit** [comment]
dfip-5 neutral

**Comment by uzyn** [comment]
Masternode votes from Cake DeFi (https://cakedefi.com) for DFIP #5

## Raw voting results 

To be posted shortly.

### 14 masternodes for **YES**

```
$ defi-cli signmessage 8V8epB69taZSr9kbnsgFQa3AiDgjqkLW92 "dfip-5 yes"
H2vZu34a62EVY2Ayp9CeXf2tMxB9plyTyQoRlGU96KpIGgofzyqTcPTQY5iGmtOnUeVvFqObJl00FiDWIcROBZA=
$ defi-cli signmessage 8YSxAdFc9476SYjP4oP9GTcffu3Mp2QBPB "dfip-5 yes"
IKYZFs5/zktrqaxpldYUdcu/Ma1dT1tW4xN00E6PGwvcZ3ap43Vzurj3hbv73HmL8UWxw7CtKFmr0LyEY4HHfYM=
$ defi-cli signmessage 8MMCHMVi4Hgh2GMhrXn239ZsYsMng3pTgT "dfip-5 yes"
HyErmVledlai6$OU6mvMcSsEvH$9DKfkygAY4D9fgfl8VvNVvm9urY$0lLajykKNj4el1SXyVHOMWxjfCNxCS1U=
$ defi-cli signmessage 8Qv3ogu3t7hm128F98qU8KsJuSDxU1UVpZ "dfip-5 yes"
H7K1qfaMDlwI82J02j7Ib4w9pN9hjZd4xebMDlgIUGVQYwIZrOagaBcHvoWLh1gn3lXVmd43IsjlQ9hEEK7sCKg=
$ defi-cli signmessage 8X9chwcKCzpG2QUKozYo3dcaff885TmBxp "dfip-5 yes"
IFrD/2tVcGSudJIFSUfHwFTu9uuspL20QJlxIQPGxL0bZGN7cI/JV2/ZazTfY43$0PAzbx9U3Rje$IgHzKwgdxE=
$ defi-cli signmessage 8UdHjvi29eU6jEbVDSRsXugJu2k2e3zY2W "dfip-5 yes"
H6jKfgSjl$Tc7gH5OMeIjP47I52qo58c2/G/WAAT3H$$FaHsOWK557OSm9Iwh0lSbvXFffhtKtigO3ux86MOrjM=
$ defi-cli signmessage 8e3YAhew2CEUqyr8BtH6baJwE991dMXVoU "dfip-5 yes"
HxaZ78FMjCuS5UpZA4LofI0tpqzRjHrarLyPZoDgTnQzD6S2MiudzRoicH6PgtizmS8bZEnOuSBNyOO1RCEhHwY=
$ defi-cli signmessage 8dEfagfYUXAd2DsUfvDLdhicRbBmEj9da5 "dfip-5 yes"
ILWMVnNP/sgZV0CXGK7Xa8DKcLKmKILpPZASrf2hdK/XIIdo2hghPFEYXIJPy9K9r3FR/aTHiccFQvW7n2jx/uA=
$ defi-cli signmessage 8XYsRxbQ89w48paRWXwLAjU3GStNB5cKad "dfip-5 yes"
IJ93BZm0yWa0$T5vJG0DTnah8hYEzToG8qqQ6TvHxsOaaMirRMfYPlC7GTPtBAjXvu54Vke9IJqv7nGQD7avL00=
$ defi-cli signmessage 8JmTVRQzJzWwHeegDUzofKUvn4FpBxTk5h "dfip-5 yes"
IGZWIheI96NbwLXppZi45vgooReSCugnQw2qjKoA7q07EVuuaiNP8SWEEBZ/mGLv8jVkwx6My0wbCOyMy69OrNE=
$ defi-cli signmessage 8Lr2RpnL5RrZnXwzd9N5j4vJ3mNjUk35TV "dfip-5 yes"
IMFz9YFYpBkxHcqUC4mXdW3whKq7$fwMdY2HK/aWsBRSQxtF3yb9SCmmH2$z67nfC3t/8duHwQWdi5eJ7VmIGXk=
$ defi-cli signmessage 8SygZNJey81ksvqoLGrE8Hk85Yg5bwp6N4 "dfip-5 yes"
ILpZ6UKUf81b1QwNT1$/RX7Dm1ddOr0T14JfLR/o8fUEPxFiGtA3ea7VpWuhkxzhWnkJ923IrPxObKi1KhbCgIk=
$ defi-cli signmessage 8SNzL79x2vQBxbsji8x3Tsu515UfjtfUgk "dfip-5 yes"
HyhGbNEMOFVYlvVXWimjme3ecngLtLiutMFPReurI9plMhbFbrKVlcKYY9LTVeA2RRqui58UpHLeGvBdAQQS4/c=
$ defi-cli signmessage 8bGJntENwPDCENjFKECJb5KtXbX1CHeXoP "dfip-5 yes"
H$ZnIdW2towE7BB0fpd4Y7IZnxeNftN81wVOOpWIRkVdM2fprxQLnoH06WC6XomkJ7P3pQJEmB/LwwPiKyrFWJE=

```

### 2 masternodes for **NO**

```
$ defi-cli signmessage 8XpNN5Koco6sDmDgL618qntUdE2D65HC8s "dfip-5 no"
IBVdmZxz1jkkm3KDSAHhrJQdlJgwYNbOrJ2N1s6bjqmhPNfnbRf$M0RKCGDJTuwTN749Yu/xoVRRia9caNn1w2Y=
$ defi-cli signmessage 8cLPN4diDtw8oG2ZxD58SQsprfyHyccnG4 "dfip-5 no"
H3uyWfSrpY5L5tp34mrlNZlEs4eff/XS/y4AyzVtnf3pQ8$d3fdKpUcKM0DvgMfVe2PunqRKHE9i$FKaT3H7wLg=
```

**Comment by andreattafabio** [comment]
**Raw voting results - Cake** 

Survey is carried out by Cake DeFi to their stakers.

Details: https://cakedefi.medium.com/cake-defichain-improvement-community-proposals-voting-results-4712a58efe4c

Raw voting results: https://docs.google.com/spreadsheets/d/1fHCmtdUchFhFO4clY-Wi_57NTBUkD5hula3vskRfgKk/edit#gid=438739612

**Comment by sloth8871** [comment]
I am very interested in this pool. What is the implantation timeline for this proposal?

**Comment by uzyn** [comment]
Implemented
