### ISSUE TITLE
Announcement: November 2021 voting round

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#73]
## Key notes
1. Please submit your DFIPs and CFPs by the cutoff dates to https://github.com/DeFiCh/dfips/issues. Use the CFP or DFIP template when you create the proposal.
2. As part of DFIP #9 (https://github.com/DeFiCh/dfips/issues/19), each proposal that would be voted on would be required to be paid a fee of either 10 DFI for Community Fund Proposal, 50 DFI for Vote of Confidence or 500 DFI for reallocation of block rewards. Fee is to be paid to the burn address `8defichainBurnAddressXXXXXXXdRQkSm`.
1. Once the fees are paid, update the issue with the txid.
1. Optionally, you may also want to start a Reddit thread at https://www.reddit.com/r/defiblockchain for community discussions.

### Key dates:
1. All proposals are to be submitted by Monday, 15 November 2021 23:59:59 UTC and have its fee paid by the first block mined after the time.
1. There will be one week of project presentations and Q&A.
1. Voting starts on Monday, 22 November 2021 23:59:59 UTC with masternode snapshot taken on the first block mined after the time.
1. Voting concludes on Monday, 29 November 2021 23:59:59 UTC. Final votes are to be posted on respective GitHub issue before the time.
1. Announcements of results should be in by Wednesday, 1 December 2021.

**Comment by uzyn** [comment]
# Confirmed proposals for voting

- 2 DFIPs
- 21 CFPs for a total of 495 900 DFI requested

## DeFi Improvement Proposals (DFIPs)

1. https://github.com/DeFiCh/dfips/issues/79
2. https://github.com/DeFiCh/dfips/issues/96

## Community Funding Proposals (CFPs)

1. https://github.com/DeFiCh/dfips/issues/74	
2. https://github.com/DeFiCh/dfips/issues/75
3. https://github.com/DeFiCh/dfips/issues/76
4. https://github.com/DeFiCh/dfips/issues/77
5. https://github.com/DeFiCh/dfips/issues/78
6. https://github.com/DeFiCh/dfips/issues/80
7. https://github.com/DeFiCh/dfips/issues/81
8. https://github.com/DeFiCh/dfips/issues/82
9. https://github.com/DeFiCh/dfips/issues/83
10. https://github.com/DeFiCh/dfips/issues/84
11. https://github.com/DeFiCh/dfips/issues/85
12. https://github.com/DeFiCh/dfips/issues/86
13. https://github.com/DeFiCh/dfips/issues/87
14. https://github.com/DeFiCh/dfips/issues/88
15. https://github.com/DeFiCh/dfips/issues/89
16. https://github.com/DeFiCh/dfips/issues/90
17. https://github.com/DeFiCh/dfips/issues/91
18. https://github.com/DeFiCh/dfips/issues/92
19. https://github.com/DeFiCh/dfips/issues/93
20. https://github.com/DeFiCh/dfips/issues/94
21. https://github.com/DeFiCh/dfips/issues/95

**Comment by prasannavl** [comment]
### CFP payments processed. 

---

- https://github.com/DeFiCh/dfips/issues/75

  - c99083a3a161c2867ea4a2f754e54d5c8a0eb99393431cf76232d4471c18d501
  - 920e7585cef726983fa403a17e0475bebba3842e059b2ae1df365264ed45b19e
  - 94656a93b5eb908a32c6c34e6102835270a862c762856e829684359c39ea7d8f
  - 9794f080c6f9ec108fbd649d4499df88c075215580e5bff4dc358a4f8b9afa61
  - 57ff9792a5c7dbfa80edeef948c08651b5739388a231b6babe2e326adfa55678

- https://github.com/DeFiCh/dfips/issues/78

  - ae1daa5b99a88e84f8ececc62c1b75ecc9d550c252d963a55ffceb577f808f5c
  - 18d7074ec714c434034e0e3f21d09db77407a656f09275f2a6b7207aafaf3bc9
  - 7562770a094345608cddce12daedddab37e3b6b9d24c9ea007babc89cef3ada5

- https://github.com/DeFiCh/dfips/issues/80

  - a8a7ec435abd4c68425325dda2bce0ccd0971f77442365a50499c08d4cbf022a

- https://github.com/DeFiCh/dfips/issues/81

  - d96df4461e75873e6ef208ca1caeb50c27076a93703b42f92f2641f8010c0965

- https://github.com/DeFiCh/dfips/issues/87

  - a64998dd19a5f7bb4d62801ea1df43adec7fb1b1ccb01eeb586992420b03a470
  - b774d9a83ffa42995fa4aa5153769eb0402a1ae1a1a989db2e6e8b9771b823a2
  - 49c9e7bed1e2b35482d19134e8b84fb0797eeae5bd1ec9d653b08556521831f6
  - 57ff9792a5c7dbfa80edeef948c08651b5739388a231b6babe2e326adfa55678

- https://github.com/DeFiCh/dfips/issues/89

  - d039a35c3adb18d427cbc051b5b77569a6f0ab26bd016a39e23aa2e120d98219

- https://github.com/DeFiCh/dfips/issues/90

  - 6e6c4e81eeee7e971656599a0f8c1c7754f2c086b57accf632b529827916aed4
  - dc83cb7827317ff0f50002f6fd05ef45526eb3247caaa555facd054a2e84d2f8
  - e19b43975c245d17d831923f206f2f4b4c8b05c0bff4ffd368cbff1bac529d18
  - 63f88ab5ae2db2dd994686a10a64780dbd6abf87d76951fe604314903632013a
  - 84fb8d0bb127262e3ddbe563853db70f6d3bc41e5f6051cb910eabe8c353991e
  - e2b7453ad61257988966f4c0178780e8d88c1d581e3e6b1e40f723d6daf6a610
  - f05e5cc569101a73e6bf0aa255b27691a417999cf5939412ce79c781145ed4b5
  - f0fe9ced871e40ca34b0970556ee9f552b2130d7d5f4dce8a3bd145979d59542
  - d498aa25cdf7b8fb6a54d6587df3a5bae14d62b683f2e8bcc0922558f335ab25
  - d475fd421f6bd346ed1d76ab5a13616b896d31576e70d9b43600169cd7319c01

- https://github.com/DeFiCh/dfips/issues/91

  - 1b9931d12adac3ab648054c70fc10ad6c808d43aa4d3124eb96421d2192bf939

- https://github.com/DeFiCh/dfips/issues/92

  - c99083a3a161c2867ea4a2f754e54d5c8a0eb99393431cf76232d4471c18d501
  - 920e7585cef726983fa403a17e0475bebba3842e059b2ae1df365264ed45b19e
  - 94656a93b5eb908a32c6c34e6102835270a862c762856e829684359c39ea7d8f
  - 9794f080c6f9ec108fbd649d4499df88c075215580e5bff4dc358a4f8b9afa61

- https://github.com/DeFiCh/dfips/issues/93

  - 41412fceb19fcb27534d4de7f678ed2cfa206c12e449e780059493901118ffd4

- https://github.com/DeFiCh/dfips/issues/94

  - 2dbd699d7942fddef72974a67075db784d9a0dbd53bfb14df33ab4ae8c9a7afc
  - c3802677c3f82d1051e64fb60fe08ab22611bb43cb0a0e420f9762d9d28e9cbd

- https://github.com/DeFiCh/dfips/issues/95

  - 17f5bdd9e451f870228f912272df03a6322c05cacfe6916450aa786f2af0555c
  - a2518518731e893c298b605b1cd5a33d9cb8d929c8163e32fb3d50dc5fad1431
  
---

If there's any issues or discrepancies, please feel free to let us know. Thanks and cheers!
