### ISSUE TITLE
DFIP #6: Introduction & Funding of Bitcoin Cash BCH-DFI Liquidity Pool

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#8]
## Overview

Decentralized exchange (DEX) has been operating for a month now at DeFiChain and it has been stable. It is time to introduce the more liquidity pool pairs to the DEX.

## Proposal

1. Introduction of Bitcoin Cash BCH-DFI Liquidity Pool.
2. Based on market cap of BCH, it is proposed for a funding of **1 DFI per block** incentive as liquidity mining reward for this pool. Funding is sourced from [the remainder of airdrop fund](https://explorer.defichain.io/#/DFI/mainnet/address/dMysnhSbg8VbJJjdj273bNQi6i69z4WL6Z). 

Upon approval, this proposal will be implemented during one of the the upcoming hard forks, allowing LP to be funded via token deposits.

## Stage

- [X] Voting
- [x] Results

## Voting

Masternode snapshot will be taken at block 556,100 of DeFiChain mainnet.

Voting will open until Monday, 11 January 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `dfip-6 yes`
- No, I do not agree. Sign: `dfip-6 no`
- Neutral. Sign: `dfip-6 neutral`.

## Results

DFIP 6 passes with 13 yeses to 3 nos.

**Comment by krishna-83** [comment]
dfip-6 neutral

**Comment by Petra-bit** [comment]
Yes, I agree. Sign: dfip-6 yes

**Comment by uzyn** [comment]
Masternode votes from Cake DeFi (https://cakedefi.com) for DFIP #6

## Raw voting results 

To be posted shortly.1

### 13 masternodes for **YES**

```
$ defi-cli signmessage 8V8epB69taZSr9kbnsgFQa3AiDgjqkLW92 "dfip-6 yes"
H8B8VG48ZC9Oe2DcyNzY6UJqzyIarIEJlg+aSvnLsZlZHIKWZt1e0OmNn8gtQ8uSkzVbZ3kdHKsiNb8Zxt9uNGQ=
$ defi-cli signmessage 8YSxAdFc9476SYjP4oP9GTcffu3Mp2QBPB "dfip-6 yes"
IGhsY501iumRHE6x2zNz80hjswHRhlWwMf4Z0mLNngd7ENyp5wIXJHTxNTFuMkZAybLucYzhH30yM6gvjQ7WYBc=
$ defi-cli signmessage 8MMCHMVi4Hgh2GMhrXn239ZsYsMng3pTgT "dfip-6 yes"
H2j6I30199/bBpiTBLbbAk9dR61Gfi4OFAlbumkCFN76fH8ZIu6P6uMZbJQ2NewJmT3ct1hK6TXartNp0NaXthk=
$ defi-cli signmessage 8Qv3ogu3t7hm128F98qU8KsJuSDxU1UVpZ "dfip-6 yes"
H1Vv7WUdUwxJc878Y+UyMS+ukzzrJ/h1d3wUjj0GwAeieaPgbajNBc5wkB9K30VjpzvmJ3HNe26WrqX2g9Cz4og=
$ defi-cli signmessage 8X9chwcKCzpG2QUKozYo3dcaff885TmBxp "dfip-6 yes"
H+iOU3y5jGJYSF+SF/AfV1ItQK1259sMX3cHf0lnsdqrDENcjPz30bGvaAt3l1xvQLM33qCqn9EbzPGSuMiawcI=
$ defi-cli signmessage 8UdHjvi29eU6jEbVDSRsXugJu2k2e3zY2W "dfip-6 yes"
H/YKPDCLRZdJ96bt4PuHBKiRTHKXWL9VtjDu+KyG5Xo3OSJhWfmAFuA1DdPk1O7oPRhKzNF4rTwUUz6R8+9ZzYA=
$ defi-cli signmessage 8e3YAhew2CEUqyr8BtH6baJwE991dMXVoU "dfip-6 yes"
H5YA23uD5LUGUsTZXwnA9AJByJLuuqXtjhmB+QUGfy38d//tqS09+yy1MZmjpEA/OAryosnk/7/UnM9CszPlA6w=
$ defi-cli signmessage 8dEfagfYUXAd2DsUfvDLdhicRbBmEj9da5 "dfip-6 yes"
H7Gfoz1nT82yyT/fIDIQKIql0Q8tULSLxMrfTaYYyN4ddss+pFNGNUMo1WdDn6zduDK/F8NqBcocK9r7E3rojtU=
$ defi-cli signmessage 8XYsRxbQ89w48paRWXwLAjU3GStNB5cKad "dfip-6 yes"
IBfG1f/vgK25ZbE6EEodDElKawK6FUk9pUMxn3qARMQLQABJfFOSdCd4fYeEIhP4GHulsaNVtIsYHgSvABVTZpQ=
$ defi-cli signmessage 8JmTVRQzJzWwHeegDUzofKUvn4FpBxTk5h "dfip-6 yes"
IBmmI410Jb2uDK4tw7gaVkWqpmFnVDjgCNDOpTFwUvheBevRr46FPMPHC9YziZOqAXhVESFByegO+V3wR9NI+H0=
$ defi-cli signmessage 8Lr2RpnL5RrZnXwzd9N5j4vJ3mNjUk35TV "dfip-6 yes"
H6HJq6NUVSVWpuwkWpcfEIwUid/vMonpAZ3vaqUriondNh5FqMM3O8F4A3igHSX+/fW2uFD6l1CeQcGlnPQYSBQ=
$ defi-cli signmessage 8SygZNJey81ksvqoLGrE8Hk85Yg5bwp6N4 "dfip-6 yes"
IEHGclr+6+yyUOagQFXMUaiP+As8bZWBsx0PCKc1cg3sKhcESJE0+DKSlRilUxPRDg/Ewg1yZXKs73Yi0QK3JtY=
$ defi-cli signmessage 8SNzL79x2vQBxbsji8x3Tsu515UfjtfUgk "dfip-6 yes"
H6QNuT0zWMzdLn08mSiWMgIVskMFNeIkqFa6rwsocY/uF25IekN5aFgIVK40y+SGO7+wTG4EoAJ1UbDki3LvfDg=
```

### 3 masternodes for **NO**

```
$ defi-cli signmessage 8bGJntENwPDCENjFKECJb5KtXbX1CHeXoP "dfip-6 no"
IPeSzle9P6YxLxIS4k5Me3Ffy6CFAMmEeTeh5mgG5TtKKgXV93fgUTZe9LduxZ4e3ZXa0AC2CYnU5HZzHmeapdM=
$ defi-cli signmessage 8XpNN5Koco6sDmDgL618qntUdE2D65HC8s "dfip-6 no"
H6998kfd6HaUaKlrj//jlVloaOhLu5zmH6Rm1kUrXXo3M2kmwbD5ZxmgLp5s0LWCFsPIRo07isynjXhJVNzQg38=
$ defi-cli signmessage 8cLPN4diDtw8oG2ZxD58SQsprfyHyccnG4 "dfip-6 no"
H00OqyYusUQv8rEIvk1lfZQICZHAcdvbb+ncNsPjtOfxR/6DEitaGePnXPpbypsM0X152feIZjHo+3+Ibmwvvmc=
```

**Comment by andreattafabio** [comment]
**Raw voting results - Cake** 

Survey is carried out by Cake DeFi to their stakers.

Details: https://cakedefi.medium.com/cake-defichain-improvement-community-proposals-voting-results-4712a58efe4c

Raw voting results: https://docs.google.com/spreadsheets/d/1fHCmtdUchFhFO4clY-Wi_57NTBUkD5hula3vskRfgKk/edit#gid=438739612

**Comment by uzyn** [comment]
Implemented
