### ISSUE TITLE
Community Funding Proposal (CFP) #1: Further development of community-developed DeFiChain Dashboard

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/dfips#9]
## Overview 

Daniel Zirkel (@DanielZirkel) has been actively developing and maintaining DeFiChain dashboard at http://www.cakedefi-review.com/DefiChain. It has been proven to be very useful to the DeFiChain community overall.

## Funding proposal

- Requester: Daniel Zirkel (@DanielZirkel)
- Amount: 10,000 DFI (one-off)
- Receiving address: `dZadfN9rS427CR14ZyFE1GfvgW3uB1m4md`

The fund will be used to make further developments (content depends on API availability), like:
- Showing DFI distributions over time
- Distribution of DST community tokens
- Visualization of Tokens (BTC, ETH, USDT) in the liquidity pools (additional to liquidity token)
- Adding further pool pairs on existing evaluations (when added on DEX)
- Maintenance and rework of SW-Code to handle bigger data in future
and to pay the domain and sever costs. All these topics are planned for 2021.

## About community funding

DeFiChain contributes 19.9 DFI every block to a [community fund](https://explorer.defichain.io/#/DFI/mainnet/address/dZcHjYhKtEM88TtZLjp314H2xZjkztXtRc) to fund for community projects like these.

If you are interested in applying for community fund, please reach out to communityfund@defichain.com with your proposals.

## Stage

- [X] Voting
- [x] Results

## Voting

Masternode snapshot will be taken at block 556,100 of DeFiChain mainnet.

Voting will open until Monday, 11 January 2021 12:00 UTC. Please post your votes and proofs here in this GitHub issue before the closing time.

Refer to [README](https://github.com/DeFiCh/dfips/blob/master/README.md#how-to-vote) for voting instructions.

### Vote options

- Yes, I agree. Sign: `cfp-1 yes`
- No, I do not agree. Sign: `cfp-1 no`
- Neutral. Sign: `cfp-1 neutral`.

## Results

CFP 1 passes with 15 yeses to 1 no.

10,000 DFI has been transferred from community fund to `dZadfN9rS427CR14ZyFE1GfvgW3uB1m4md` with txid: `9c4927d806fa9386d8ac101fc1093a54ec953e9be539ff22afb9515d974dd256`.

**Comment by DanielZirkel** [comment]
Thanks @uzyn for helping setting up this proposal.

**Comment by Petra-bit** [comment]
Yes, I agree. Sign: dfip-3 yes

**Comment by uzyn** [comment]
Masternode votes from Cake DeFi (https://cakedefi.com) for CFP #1

## Raw voting results 

To be posted shortly.

### 15 masternodes for **YES**

```
$ defi-cli signmessage 8V8epB69taZSr9kbnsgFQa3AiDgjqkLW92 "cfp-1 yes"
ICH7QRTt6zJaedQu0WMy5y8NWecVxDI/Y3zdYi3MW9/dda+bhj3CwHlyzKlP4hzOcuBsjc2ERAeq1ZTrstAs0+k=
$ defi-cli signmessage 8YSxAdFc9476SYjP4oP9GTcffu3Mp2QBPB "cfp-1 yes"
IL+gTiWiq/BKCms2l9b+MxunHqZ/vDM18agKf7pRNjbtb2Dr9GSzUFAQiogtyS8h+7Ce62mql1Cy7jk9bqHuH7w=
$ defi-cli signmessage 8MMCHMVi4Hgh2GMhrXn239ZsYsMng3pTgT "cfp-1 yes"
HxheDIOsYfdSaVSg1Z3nu0hxy3+2GtRBaVjTeZBSQx+PI4DKj8iOkhdMMEDqMA29PNeVurgytYGu5pODWm/PJUw=
$ defi-cli signmessage 8Qv3ogu3t7hm128F98qU8KsJuSDxU1UVpZ "cfp-1 yes"
H8B2T1M6UVFtUG3t5BCEq6QqojXe5hkvu5wB/cfiIdTFeMl94Pr4lHSVAHLQ+L1cVn6qoGpqG7hVivy4E4siEs0=
$ defi-cli signmessage 8X9chwcKCzpG2QUKozYo3dcaff885TmBxp "cfp-1 yes"
IIJ1X8+IfSTsu1N/NfsmWGmi/7tFokxRWdpQ6gIPQ5oqBBh6vsVXI2I3opdp/40w9T+Au89llQRaNBpM+gOMvbM=
$ defi-cli signmessage 8UdHjvi29eU6jEbVDSRsXugJu2k2e3zY2W "cfp-1 yes"
IA3PCt5TO/WaKMsAchWW+PkaFnQT7JBsaipegRkk5cSZTJmwbp1y54qtgVnUPqNMLzwud74/BQy42mZJYPy+V70=
$ defi-cli signmessage 8e3YAhew2CEUqyr8BtH6baJwE991dMXVoU "cfp-1 yes"
IM4l0/cjz2wBxg6sAjuW6/ecdz5L46AIQpdib5Gi5wq/GXwwkoh880moxM6lfb2OIOj/r9uE915yRryQ4VaR4HY=
$ defi-cli signmessage 8dEfagfYUXAd2DsUfvDLdhicRbBmEj9da5 "cfp-1 yes"
H5xNmclSRMbq94ex53fHIvgK4Btdbi3izGS9eCfY33u/Tahq8WVNLfi/WxvyMlSskYggPuFg0NsHfHngjHJJzxE=
$ defi-cli signmessage 8XYsRxbQ89w48paRWXwLAjU3GStNB5cKad "cfp-1 yes"
IKIg1ADZQbQKqn1rX5FeejjQfuZoQBtgP97Q2R0mJJnwCAluE5ZqzwsHGn6tP75NEMgyTtnswKSYFuxolFp8Sns=
$ defi-cli signmessage 8JmTVRQzJzWwHeegDUzofKUvn4FpBxTk5h "cfp-1 yes"
INHJpVWzfFuK3H4q7hb+5xBGokzt//GjvcnkGz+gFR+mcO+HeUH+JrseGm4bpEkLN17uN3WKzTCs/tB81s1aNgA=
$ defi-cli signmessage 8Lr2RpnL5RrZnXwzd9N5j4vJ3mNjUk35TV "cfp-1 yes"
IJ76oyKg2L8+vF9L0/Gc31bbEaWgkAdBkawNmlS3eJnmMfISJ4U6uPwANm4jA0FktmZEz0iLfNzXlN45ErS+YgQ=
$ defi-cli signmessage 8SygZNJey81ksvqoLGrE8Hk85Yg5bwp6N4 "cfp-1 yes"
IJ4Bhc83B8IoIZ+MbHrzp5yn/xITjzl/pvOqkUFiN76vAGi4X/l99GC2W3UV/bsS2IkTk0OiWdyxii10wEI35KA=
$ defi-cli signmessage 8SNzL79x2vQBxbsji8x3Tsu515UfjtfUgk "cfp-1 yes"
ICFiiEcHFfCJrlnrttVBJkSoZXJF31gsdHxkw5SfESB6aGWTXwUD1jEOUoY1B2i3DvGYLZr624KRxi5hi9PrfTU=
$ defi-cli signmessage 8bGJntENwPDCENjFKECJb5KtXbX1CHeXoP "cfp-1 yes"
H6FsG5xbIDAefbyfKN8a4wPlAdjifCKBZEVf1+/gF5qUA1QlsCuEz14ofgW8DTJdkNs0g6jT2F3eNpZ4PChpRro=
$ defi-cli signmessage 8XpNN5Koco6sDmDgL618qntUdE2D65HC8s "cfp-1 yes"
H22Rjgfnk/D0MwC+PiLi5VeVtZt4cZQ2EgyQUSsibOi4QjIRCK8m1ywWw9DNaocmBCGrMIHEYo9W1U8mh4wJyXo=
```

### 1 masternode for **NO**

```
$ defi-cli signmessage 8cLPN4diDtw8oG2ZxD58SQsprfyHyccnG4 "cfp-1 no"
IN1SpnVKkEPUGskojK7pXn+zpb1Ofy9cZH+4rRoUvS4cM5k+w9+A41rk1R+sPMQHbfHinoySWLzsO3Ve+AQdu4Q=
```

**Comment by andreattafabio** [comment]
**Raw voting results - Cake** 

Survey is carried out by Cake DeFi to their stakers.

Details: https://cakedefi.medium.com/cake-defichain-improvement-community-proposals-voting-results-4712a58efe4c

Raw voting results: https://docs.google.com/spreadsheets/d/1fHCmtdUchFhFO4clY-Wi_57NTBUkD5hula3vskRfgKk/edit#gid=438739612

**Comment by uzyn** [comment]
Congratulations on the successful passing of your proposal @DanielZirkel 

10,000 DFI has been transferred from community fund to `dZadfN9rS427CR14ZyFE1GfvgW3uB1m4md` with txid: `9c4927d806fa9386d8ac101fc1093a54ec953e9be539ff22afb9515d974dd256`.
