### ISSUE TITLE
Add DeFiChain Nodes to the FLITS Masternode App

### ISSUE THREAD

**Issue by EasyGoing67** [DeFiCh/dfips#97]
It would be a great thing if we could enable our DeFi Masternodes on the Flits App with a Smartphone, no PC needed at all, big advantage for everyone on the road.

**Comment by Kolibri1990** [comment]
--> https://www.reddit.com/r/defiblockchain/

**Comment by uzyn** [comment]
Closing this as it's not a DFIP/CFP. Please use Reddit as @Kolibri1990 pointed out.
